// ERKAK · English · disciplines, programs, places. Facts and prices are based on the September 2026 market research.
export const directions = {
  fishing:{ name:'Fishing & trophies', short:'Sailfish, marlin, GT and freshwater giants. Legal, with a licensed guide.',
    who:'For families, experienced anglers, trophy seekers and groups of friends who want real fishing, not a tourist excursion.',
    intro:'Trophy fishing in the Andaman Sea and the freshwater giants of Bangkok: the first ERKAK discipline with booking open. Private boats, Stella-grade tackle, a licensed guide and an honest map: we never fish inside marine national parks.',
    incl:['Boat and captain','Tackle and bait','Transfers','Meals on board','Insurance and a licensed guide'] },
  muaythai:{ name:'Muay Thai & martial arts', short:'Camps in Phuket and Bangkok, BJJ, boxing, MMA. From your first session to your first fight.',
    who:'For men who would rather get in shape through fighting than on a treadmill.',
    intro:'Phuket and Bangkok are the world capitals of Muay Thai: thousands of gyms, residential camps and fights almost every night. We match the camp to your level and goal, book you in next to the gym and guide you from the first session to the final review.',
    incl:['Training at a vetted camp','Accommodation near the gym','Airport transfer','Starter gear','English-speaking concierge'],
    note:'Since September 15, 2026, citizens of the EU, UK, US and GCC countries can stay in Thailand visa-free for 30 days. For longer programs we help with a visa, including the DTV (Destination Thailand Visa) for long-term training.' },
  camps:{ name:'Training camps', short:'Hyrox, fat loss, trail, triathlon, marathon and cycling camps, with a coach and a plan.',
    who:'For men who want results in 1–3 weeks and the discipline they can’t find at home.',
    intro:'A training camp is the fastest way to move your fitness forward: a coach, a routine, the right food and a climate that makes you want to train. From a Hyrox camp in Phuket to altitude training in Iten, Kenya.',
    incl:['A program from a specialist coach','Measurements at the start and finish','Meals matched to your training load','Accommodation','Recovery: massage and sauna'] },
  longevity:{ name:'Check-ups & longevity', short:'Executive check-ups, men’s health, heart, sleep and DNA, at accredited clinics.',
    who:'For men 35+ who would rather know their numbers than guess.',
    intro:'Bangkok is one of the world’s leading medical travel hubs: JCI-accredited hospitals, published package prices and a full check-up in a single day. We choose the clinic and package, support you in English throughout and make sure every report is explained clearly. ERKAK is a concierge, not a medical provider: decisions are made by the doctor.',
    incl:['Clinic and package selection','Booking and support in English','Reports explained in plain English','Transfers and hotel','An action plan based on the results'],
    note:'Hospitals publish their own package prices. Promotional prices are sometimes for residents only, so we get written confirmation of the price for international patients.' },
  detox:{ name:'Detox & reset', short:'Detox retreats, weight reset, sober retreats, medically supervised fasting, Ayurveda.',
    who:'For men who are worn out, have put on weight and want a fresh start.',
    intro:'A reset means a new routine, not “flushing out toxins.” Retreats on Koh Samui and in Bali, weight-reset programs in Phuket, supervised fasting in Europe and Ayurveda in Kerala. Before you start, you fill in a health questionnaire: some formats are not for everyone.',
    incl:['Retreat program','Accommodation and meals per protocol','Specialist consultations','Transfers','30 days of support afterward'] },
  recovery:{ name:'Recovery', short:'Sauna and ice, Thai massage, physiotherapy, onsen, banya, the Dead Sea.',
    who:'For men with a sore back, fatigue that won’t go away and broken sleep.',
    intro:'Recovery is half of training and the best way to get your energy back after a hard year. Contrast therapy in Phuket, old-school massage in Chiang Mai, Japanese onsen, a Russian banya and the Dead Sea.',
    incl:['A course of treatments','Vetted studios and spas','A schedule that fits your rhythm','Transfers','English-speaking concierge'] },
  mind:{ name:'Mind & calm', short:'Silent retreats, breathwork and cold, men’s circles, a monastery stay, coaching, a psychologist.',
    who:'For men who have everything except a quiet mind.',
    intro:'Quiet and clarity are the scarcest resources of all. Meditation centers in northern Thailand, breathwork in Bali, men’s retreats in the Altai, coaching and a psychologist online. Where a tradition is free, we charge only for the logistics.',
    incl:['A facilitator or mentor','Quiet accommodation','Meals','Transfers','An integration session afterward'] },
  adventure:{ name:'Adventure', short:'Elbrus, Kilimanjaro, Everest, Kamchatka, motorbike tours, safari, the cliffs of Railay.',
    who:'For men who want to do something they will tell their grandchildren about.',
    intro:'Summits, treks and routes that change the scale of everything else in your life. We work with licensed local operators, build in reserve days and high-altitude insurance, and we are honest about the risks.',
    incl:['Guides and permits','Gear per the kit list','Accommodation along the route','Adventure travel insurance','Photos and video'] },
  ocean:{ name:'Ocean', short:'Diving, freediving, surfing, kitesurfing, sailing courses and yacht weeks.',
    who:'For men who are drawn to the water and want real skills, not just the view.',
    intro:'From your first dive off the Racha islands to a Similan liveaboard and surfing in Bali. Certified instructors, internationally recognized certifications and seasons chosen for wind and swell.',
    incl:['Instructor and certification','Equipment','Boat or spot access','Accommodation nearby','Underwater photos'] },
  golf:{ name:'Golf & padel', short:'Golf weeks in Phuket and Scotland, padel in Dubai, tennis academies.',
    who:'For men who love the game, good company and beautiful courses.',
    intro:'Five Phuket courses in a week, golf from scratch in Hua Hin, the links of St Andrews and padel in Dubai, where the sport is growing fastest. We handle tee times, the pro and transfers with your gear.',
    incl:['Tee times and court bookings','A coach or pro','Transfers with your equipment','Accommodation','A tournament within your group'] },
  aesthetics:{ name:'Men’s aesthetics', short:'Hair transplants, dentistry, vision correction, skincare, style.',
    who:'For men who want to look their best at any age.',
    intro:'Istanbul, Bangkok and Seoul are world centers of aesthetic medicine, with many excellent clinics and just as many conveyor-belt operations. We choose accredited clinics, check exactly who performs the procedure and support you in English.',
    incl:['Choice of an accredited clinic','Consultation before you travel','Support in English','Hotel and transfers','Follow-up afterward'],
    note:'ERKAK is not a medical provider: whether a procedure is right for you, and every medical decision, is up to the doctor. Standard travel insurance does not cover elective surgery.' },
  nutrition:{ name:'Nutrition & ERKAK supplements', short:'A nutritionist who works from your lab results, the ERKAK supplement protocol, a private chef and a meal plan.',
    who:'For men who want their food and supplements guided by their lab results.',
    intro:'Nutrition is the foundation of every program. A lab review with a licensed specialist, the ERKAK supplement protocol with a certificate of analysis for every batch, a private chef for your trip and a journey to the source of shilajit in the mountains of Uzbekistan.',
    incl:['Lab results review','A personal plan','Supplements with a batch certificate','Support over WhatsApp or Telegram','A checkpoint at 90 days'] },
  family:{ name:'Father & son', short:'Trips that leave a father and son with a story of their own.',
    who:'For fathers who want to give their son time together, not another thing.',
    intro:'The ring and the ocean in Phuket, the Himalayas, the cliffs and islands of Krabi. Programs built around your child’s age, with vetted instructors and safety first.',
    incl:['A program matched to your child’s age','Instructors and guides','Accommodation','Transfers','Photos and a film of the trip'] },
  business:{ name:'Teams & friends', short:'Leadership team retreats, regattas, founders’ retreats, premium bachelor parties.',
    who:'For teams and groups of friends who want a shared experience.',
    intro:'A shared experience brings people closer than any team-building exercise. Strategy retreats in Phuket and Bali, corporate regattas and men’s trips without the clichés, with full paperwork and an invoice for your company.',
    incl:['A program built around your goal','Venues and accommodation','A host and a facilitator','Paperwork and a company invoice','A film of the event'] }
};

export const programs = {
  // ── Muay Thai & martial arts ────────────────────────────────────
  'mt-phuket-week':{ title:'Muay Thai week in Phuket', where:'Phuket, Soi Ta-iad',
    short:'Two sessions a day at a camp on the world’s most famous Muay Thai street. Accommodation with a pool, five minutes from the gym.',
    about:'Soi Ta-iad in Chalong is the street where Tiger Muay Thai, Phuket Top Team and AKA stand side by side. We choose the camp for your level: group classes for beginners, sparring for those who already box, or a strength block if the goal is conditioning. You stay at a hotel with a pool near the gym, and your transfer and first session come with English-speaking support.',
    plan:['Transfer, check-in, meeting your trainer and an intro session','Morning technique class, evening pads and bag work, optional sparring','Massage and recovery midweek','Final session, video review and a plan for home'],
    tip:'Camps run year-round, and accommodation is cheaper in the rainy season (May–October). A week fits easily into the 30-day visa-free stay.' },
  'mt-month':{ title:'Four-week transformation: Muay Thai and nutrition', where:'Phuket',
    short:'The most popular “leave and come back a different man” format: two sessions a day, a nutritionist and weekly measurements.',
    about:'Four weeks at a Muay Thai camp with a clear goal: lose the extra weight, build endurance and sharpen your technique. A nutritionist plans your meals around the training load, the food arrives ready to eat, and your body composition is measured once a week. We chose 28 days so the program fits comfortably within the 30-day visa-free stay in place since September 15, 2026.',
    plan:['Adapting to the heat and the load, basic technique, baseline measurements','Two sessions a day, strength work, nutrition tracking','Optional sparring, final measurements and video review','A 90-day training and nutrition plan for home'],
    tip:'Visa-free stays in Thailand are limited to 30 days. For longer programs, we help with a visa.' },
  'mt-bangkok':{ title:'Bangkok Muay Thai: legendary gyms and fight night', where:'Bangkok',
    short:'Train in the gyms of champions and watch from the best ringside seats at Rajadamnern.',
    about:'Bangkok is where Muay Thai history lives: gyms where champions trained, and Rajadamnern Stadium, with fights almost every night. Over five days you train at two or three classic gyms, take a private session every day and watch a fight night from ringside. We buy tickets only at the official box office, with no reseller markups.',
    plan:['Morning and evening sessions at a classic gym','A private session with a former champion','Fight night at the stadium, ringside','Final session and free time in Bangkok'],
    tip:'The best months are November–February: from March to May, Bangkok is very hot.' },
  'mt-private':{ title:'Private Muay Thai coach', where:'Phuket or Koh Samui',
    short:'Ten one-on-one sessions with a fighter as your coach. A flexible schedule that fits a family vacation.',
    about:'For men on vacation with their family who don’t want to fit around a camp schedule. The coach comes to your villa or meets you at the gym at a time that suits you. We match the coach to your language, level and goal: technique, conditioning or getting ready to spar.',
    plan:['Assessing your level and goals','Technique, combinations, pad work','Sparring drills and a plan for training on your own'],
    tip:'Sessions with well-known former champions cost more; we will find a coach to match your budget.' },
  'mt-fight':{ title:'Your first Muay Thai fight', where:'Phuket',
    short:'Six to eight weeks at camp, sparring and stepping into the ring with a professional team in your corner.',
    about:'For men who want a real test. A camp experienced in preparing foreigners for their debut, 10–20 private sessions, sparring, weight management and medical clearance. The gym arranges the fight, at a Phuket stadium or an in-house event. The fight is not guaranteed: your trainer decides when you are ready.',
    plan:['Foundations, endurance, trainer assessment','Sparring, private sessions, tactics','Fight-week taper, weight control, medical clearance and the fight','Recovery and fight review'],
    tip:'The program runs longer than 30 days, so you will need a visa; we help with the paperwork, including the DTV.' },
  'bjj-camp':{ title:'Brazilian jiu-jitsu camp', where:'Phuket',
    short:'BJJ for beginners and blue belts: technique in the morning, rolling in the evening, plus two private lessons.',
    about:'Phuket is one of the best places for BJJ in Asia, with several academies run by black belts on a single street. Mornings are for technique, evenings for rolling with partners your weight, and midweek you get two private lessons. You can rent a gi, but it’s better to bring your own.',
    plan:['Getting to know the academy and a level assessment','Technique in the morning, rolling in the evening','Private lessons: working through your positions','Final rolls and a development plan'] },
  'boxing-camp':{ title:'Boxing camp in Almaty', where:'Almaty',
    short:'The Kazakh school of boxing: pads, bags and sparring with coaches from the Olympic reserve system.',
    about:'Kazakh boxing is one of the strongest schools in the world, and Almaty is its capital. There are almost no ready-made international camps here, so we build the program ourselves: a private coach from a sports school, two sessions a day, sparring matched to your level, a hotel near the gym and the Alatau mountains on your day off.',
    plan:['Arrival, level assessment, first session','Two sessions a day: technique and partner work','Final sparring and a mountain hike'],
    tip:'The best time is April–June and September–October: in winter the city has smog.' },
  'mma-camp':{ title:'MMA camp alongside the pros', where:'Phuket',
    short:'Striking, wrestling and the ground game: two weeks at a gym where fighters from major leagues prepare.',
    about:'MMA in Phuket means gyms where professional league fighters train. You go through the full cycle: Muay Thai, wrestling, BJJ, cage work and four private sessions. Training in the same group as the pros is by the coach’s invitation after a level assessment, and we tell you so up front.',
    plan:['Assessment and fundamentals in three disciplines','The full cycle and private sessions','Intensive block, sparring, review'] },
  'mt-samui-lux':{ title:'Muay Thai and a villa on Koh Samui', where:'Koh Samui',
    short:'A private coach at your villa, a chef and a massage every day. A fight only if you want one.',
    about:'Muay Thai as a private resort experience: a villa with a pool and sea views, a coach who comes twice a day, a chef who cooks for your training load and a massage every evening. Right for you if you are traveling with family or value quiet over camp atmosphere.',
    plan:['Check-in and meeting your coach','Two sessions a day, massage, meals by the chef','Final session and downtime'],
    tip:'The best months on Koh Samui are January–August; October–December is the rainy season.' },
  // ── Training camps ──────────────────────────────────────────────
  'hyrox-camp':{ title:'Hyrox camp in Phuket', where:'Phuket',
    short:'Preparation for the fastest-growing fitness race: running, eight stations and a full race simulation.',
    about:'Hyrox combines 8 km of running with eight functional workout stations, and interest in it is growing faster than in any other fitness race. We build a one-week block at a functional training gym on Soi Ta-iad: station technique, pacing, training in the heat and a full race simulation at the end. Ready-made Hyrox camps are almost nonexistent in Asia.',
    plan:['Testing, station technique, tempo runs','Intervals, combined run-and-station work, recovery','A full, timed race simulation','Review and a training plan for your race'],
    tip:'The best time is November–March, when it’s cooler.' },
  'fatloss-camp':{ title:'Fat-loss camp in Phuket', where:'Phuket',
    short:'Two weeks of cardio, strength and Muay Thai, with calorie-counted meals and measurements. A 90-day plan for afterward.',
    about:'Phuket’s fitness camps mean 2–3 sessions a day in a climate where it’s easy to find your rhythm. We add what most of them lack: calculated nutrition, meal delivery, body composition measurements at the start and finish, and a 90-day plan so the results don’t fade once you’re home. No promises like “minus 10 kg,” just a clear system.',
    plan:['Measurements, consultation, first session','Circuits, strength, Muay Thai and cardio, following the meal plan','Final measurements and a 90-day plan'] },
  'trail-camp':{ title:'Trail running camp in Chiang Mai', where:'Chiang Mai',
    short:'The trails of Doi Suthep and Doi Inthanon, downhill technique and cool mornings at altitude.',
    about:'Northern Thailand means mountains rising to 2,565 meters on Doi Inthanon and a network of trails leading straight from the city up Doi Suthep. Five guided runs, a day on the country’s highest point and a massage after every long session. Ideal for preparing for a mountain race or for rediscovering the joy of running.',
    plan:['An easy run to get to know the trails','Hill intervals, downhill technique, a long run','Doi Inthanon, the highest point in Thailand','Recovery'],
    tip:'November–January only: from February to April, the north has its smoke season from field burning.' },
  'tri-camp':{ title:'Triathlon camp in Phuket', where:'Phuket, Laguna',
    short:'A 50-meter pool, open water, coastal rides and run blocks, from sprint distance to 70.3.',
    about:'The Laguna area of Phuket is the center of triathlon in Thailand: a 50-meter pool, a calm lagoon for open-water swimming and routes along the coast. Your coach sets the load for your distance; ride your own bike or rent one, with a mechanic on hand. The Laguna Phuket Triathlon takes place here in late November.',
    plan:['Pool and bike trainer tests','Swim-bike-run blocks and open water','A benchmark brick session and review'],
    tip:'November–March; from May to October the west coast gets stormy.' },
  'marathon-camp':{ title:'Altitude running camp in Iten', where:'Iten, Kenya',
    short:'Training at 2,400 m in the town of world champions, alongside local runners.',
    about:'Iten is known as the Home of Champions: the world’s best distance runners live and train here. Two weeks at 2,400 meters, full board at a training center, group runs with Kenyan athletes, track sessions and massage. The altitude builds endurance, and the atmosphere gives you motivation you can’t buy at home.',
    plan:['Acclimatization and easy runs','Group training, track sessions, long runs','A benchmark session and the trip home'],
    tip:'The best windows are January–March and June–October. Kenya requires an eTA, applied for online before travel.' },
  'cycling-camp':{ title:'Cycling camp in Mallorca or Girona', where:'Mallorca or Girona',
    short:'Mountain climbs, group rides, a mechanic and a support car.',
    about:'Mallorca and Girona are where professional teams go to train in spring. A guide leads the group on the best routes, a support car carries water and spare parts, and a mechanic prepares your bike. A half-board hotel and a massage after the long days.',
    plan:['Bike fit and an easy ride','80–140 km routes, climbs, group riding','A free ride and rest'],
    tip:'February–May and September–October. Spain is in the Schengen Area; visa requirements depend on your passport.' },
  'strength-40':{ title:'Strength camp 40+ in Dubai', where:'Dubai',
    short:'Strength, mobility, lab tests and a protocol from a sports physician: five days for men over forty.',
    about:'After forty, training “like you’re twenty” is a fast track to injury. Five days with a certified coach and a sports physician: a DEXA body composition scan, lab tests, mobility work, two sessions a day and physiotherapy. You leave with a training and recovery protocol for the year ahead.',
    plan:['DEXA scan, lab tests, physician consultation','Two sessions a day, mobility, physiotherapy','Final consultation and a one-year protocol'],
    tip:'November–March, when Dubai is comfortable for training.' },
  'altitude-camp':{ title:'Altitude training camp in the Caucasus', where:'Tsaghkadzor or Kislovodsk',
    short:'Mid-altitude training for endurance: running, cycling and swimming at Olympic training centers.',
    about:'Tsaghkadzor in Armenia (about 1,850 m) is an Olympic base where national teams train, with a stadium, a pool and trails. Kislovodsk in Russia sits lower (900–1,400 m) and suits a gentler adaptation. A coach, half board, massage and a training plan built around your race.',
    plan:['Adapting to altitude','Main block: running, cycling, swimming','A benchmark session'], tip:'June–September.' },
  'ski-camp':{ title:'Ski camp with a coach', where:'Gudauri or Shymbulak',
    short:'Carving or freeride with a guide. Lift pass, rentals and two hours of coaching a day.',
    about:'A week in the mountains with a private coach: two hours of lessons every day, video analysis of your technique and the rest of the time on the slopes. Gudauri in Georgia is known for its freeride and sunshine, Shymbulak for its runs 30 minutes from Almaty. Lift pass, rentals and a half-board hotel are included.',
    plan:['Level assessment and equipment fitting','Two hours with your coach, skiing, video review','Free skiing'],
    tip:'December–March. You may need travel insurance for a trip to Georgia.' },
  // ── Check-ups & longevity ───────────────────────────────────────
  'checkup-bkk':{ title:'Executive check-up in Bangkok', where:'Bangkok',
    short:'A full check-up at an international hospital in a single day. Report explained in English, hotel and transfers.',
    about:'Bangkok’s hospitals make the city one of the world’s leading medical travel destinations; the top ones are JCI-accredited and publish their package prices. A men’s 40+ package usually includes blood tests and tumor markers (including PSA), an ECG, an exercise stress test, an abdominal ultrasound, an X-ray and a doctor’s consultation the same day. We choose the hospital and package, book the appointment, meet you, make sure the report is explained in plain English and put together an action plan.',
    plan:['The day before: preparation instructions and hotel transfer','Check-up day: 4–8 hours, starting on an empty stomach, with a coordinator by your side','Reviewing the results with the doctor','Report explained in plain English and an action plan'],
    tip:'Hospital promotional prices are sometimes for residents only; we get written confirmation of the price for international patients.' },
  'mens-health':{ title:'Men’s health: urologist, hormones, prostate', where:'Bangkok',
    short:'A urologist-andrologist, a hormone panel, PSA and ultrasound: a calm conversation without the awkwardness.',
    about:'The check-up men put off for years. A consultation with a urologist-andrologist, a hormone panel (total and free testosterone, SHBG, LH/FSH, prolactin, estradiol, TSH), PSA, a kidney and prostate ultrasound and uroflowmetry. Any prescriptions come only from the doctor after an examination; we organize the visit, go with you and take care of communication.',
    plan:['Fasting blood tests','Examination, ultrasound, uroflowmetry','Results review and the doctor’s recommendations'],
    tip:'Hormone medication only on a doctor’s prescription; we do not sell or ship medicines.' },
  'longevity-week':{ title:'Longevity week: check-up and protocol', where:'Bangkok and Phuket',
    short:'A check-up, biological age, VO2max and a one-year plan for sleep, nutrition and training.',
    about:'Seven days to understand how you are aging and what to do about it. An extended check-up at a Bangkok hospital, a biological age test, a cardiopulmonary VO2max test, body composition, and consultations with a doctor and a nutritionist. The second half of the week is at a Phuket resort, where you start your new routine with guidance. Biological age is a reference point, not a diagnosis: we don’t promise “rejuvenation.”',
    plan:['Check-up, VO2max and lab tests in Bangkok','Results review with the doctor','Resort time in Phuket: sleep, training, nutrition','A one-year protocol and checkpoints'] },
  'heart-check':{ title:'Heart check-up and sports clearance', where:'Bangkok',
    short:'ECG, stress test, echocardiogram and calcium score, for men who run and fight.',
    about:'Before a marathon, a fight or a climb, it’s worth knowing how your heart performs under load. The program runs at a specialized heart center: an ECG, an exercise stress test or stress echo, echocardiography, a CT coronary calcium score, a lipid panel and a cardiologist’s report. If anything is found, further procedures are agreed separately and only with your consent.',
    plan:['Blood tests and ECG','Stress test and echocardiography','CT calcium score','Cardiologist’s report and clearance'] },
  'sleep-lab':{ title:'Sleep lab study', where:'Bangkok',
    short:'Overnight polysomnography: sleep apnea, snoring, sleep quality and a recovery plan.',
    about:'If you wake up tired, snore, or your partner notices pauses in your breathing, it’s worth checking your sleep. A night in a sleep lab with polysomnography, a consultation with a sleep specialist and a plan. If sleep apnea is suspected, the doctor may suggest a second night for CPAP titration.',
    plan:['Evening: check-in at the lab and sensor setup','Night: sleep recording under observation','Morning: sleep specialist consultation and a plan'] },
  'dna-plan':{ title:'DNA test and personal plan', where:'Online, kit by mail',
    short:'The genetics of nutrition, training and health risks, reviewed with a clinical geneticist in English.',
    about:'A saliva kit arrives at your home, and results come back in 4–10 weeks. You then go through them with a clinical geneticist: your metabolism, how you respond to training, inherited risks and which of them are actually worth acting on. A DNA test is not a diagnosis, and we are honest about where the science ends and the marketing begins.',
    plan:['Ordering and delivery of the kit','Lab analysis: 4–10 weeks','Review with a clinical geneticist and a plan'],
    tip:'Genetic data is a special category of personal data; we handle it only with your written consent.' },
  'biohack-week':{ title:'Biohacking week in Dubai', where:'Dubai',
    short:'Hyperbaric oxygen, cryotherapy, lab-guided IV drips and HRV tracking, all under medical supervision.',
    about:'Five days at licensed clinics in Dubai: an examination and lab tests with a doctor, daily hyperbaric oxygen and cryotherapy sessions, IV drips only when prescribed, recovery and a final plan. We don’t promise miracles: many of these procedures have weak evidence behind them, so the doctor makes the decisions and you get an honest picture.',
    plan:['Doctor, lab tests, contraindication screening','Hyperbaric chamber, cryotherapy, recovery','Final consultation and plan'],
    tip:'November–March. Many medicines require an import permit in the UAE.' },
  'seoul-checkup':{ title:'Health check-up in Seoul', where:'Seoul',
    short:'Korean medicine: an extended check-up with MRI and endoscopy in two days.',
    about:'Seoul’s leading hospitals offer one of the most thorough check-ups in the world: lab tests, endoscopy under sedation, CT and MRI, cardiac diagnostics and a results consultation, all in two days. We work through medical tourism agencies registered in Korea.',
    plan:['Lab tests, imaging, endoscopy','A night at the hospital or a hotel','Cardiac diagnostics and results consultation'],
    tip:'The best time is spring or fall.' },
  // ── Detox & reset ───────────────────────────────────────────────
  'detox-samui':{ title:'Detox retreat on Koh Samui', where:'Koh Samui',
    short:'Clean food, yoga, massage, sauna and a nutritionist: a reset week by the sea.',
    about:'Koh Samui is the island of classic wellness retreats. A quiet week: juices or light meals, a daily massage, yoga and sauna, and a nutritionist consultation. We are honest about “detox”: it means resetting your routine, not “flushing out toxins.” We find the right format, from a calm boutique retreat to the flagship resorts.',
    plan:['Consultation and program','Meals per the program, massage, yoga, sauna','Easing out of the program and a meal plan'],
    tip:'January–September; October–December is rainy on Koh Samui. Fasting is not for everyone, so we check in advance.' },
  'weight-reset':{ title:'21-day weight reset', where:'Phuket',
    short:'A doctor, a nutritionist, a coach and a clear plan. Measurements before and after, 90 days of support.',
    about:'Three weeks to get a stalled weight moving again. An initial examination and an ECG for men 40+, 2–3 sessions a day, delivered meals and weekly body composition measurements. Then 90 days of online support. Weight-loss medication is discussed only with a doctor and is not part of the program.',
    plan:['Examination, ECG, measurements and a plan','Training, meal plan and weekly measurements','Final measurements and a 90-day plan'],
    tip:'The 21 days fit within the 30-day visa-free stay.' },
  'sober-retreat':{ title:'Sober retreat: 14 days alcohol-free', where:'Bali',
    short:'A men’s group, sport, work with a psychologist and new habits, without moralizing.',
    about:'Not a clinic and not “treatment,” but two weeks to see life without alcohol from the inside: the group, sport, group sessions and one-on-one work, food and sleep. Before you start there is a questionnaire: if the dependence is significant, we refer you to a clinic with medical detox, because stopping abruptly can be dangerous.',
    plan:['Questionnaire and a call before the trip','Routine, sport and the group','New habits and a plan for home','Online support after you return'] },
  'digital-detox':{ title:'Digital detox in the Khao Sok jungle', where:'Khao Sok, floating raft house',
    short:'No connection. Just the lake, the cliffs, silence and fishing at dawn.',
    about:'Cheow Lan Lake, set among limestone cliffs, is one of the most beautiful places in Thailand. Four days in a floating raft house: kayaks, caves, jungle walks and morning fishing from a longtail boat. Your phone goes into the safe for the whole stay: some raft houses now get 4G, so we set the rules ourselves.',
    plan:['Transfer, longtail boat, check-in','Kayaks, caves, jungle and fishing','Sunrise on the lake and the trip back'], tip:'December–April.' },
  'fasting':{ title:'Medically supervised fasting', where:'Germany or Austria',
    short:'Classic fasting clinics: medical supervision, therapies and a proper return to eating.',
    about:'European fasting clinics have followed the Buchinger and Mayr methods for decades: an examination and lab tests, daily medical supervision, therapies and a gradual return to food. We book the clinic and help with transfers and, if your passport requires one, the visa. Fasting is contraindicated for a number of conditions, and the clinic checks for them before you start.',
    plan:['The clinic’s questionnaire before the trip','Examination, lab tests, preparation','The program under medical supervision','Breaking the fast and recommendations'],
    tip:'Book 2–4 months ahead. Schengen entry rules depend on your passport.' },
  'ayurveda':{ title:'Ayurveda: panchakarma in Kerala', where:'Kerala, India',
    short:'A traditional 14-day cleansing program at an Ayurvedic center.',
    about:'Kerala is the home of Ayurveda. Two weeks at an accredited center: an assessment by an Ayurvedic doctor, a preparation phase, the main panchakarma therapies, meals and yoga. We choose accredited centers and advise against taking remedies home without checking what is in them.',
    plan:['Assessment and preparation phase','Main therapies','Recovery and recommendations'],
    tip:'Traditionally the best times are the monsoon (June–September) or the dry season (November–March).' },
  'burnout':{ title:'Burnout retreat', where:'Chiang Mai',
    short:'Sleep, mountains, a psychologist, body-based practices and a plan for getting back to work.',
    about:'Ten days to catch up on sleep, breathe out and work out what needs to change. An initial screening, daily one-on-one sessions, body-based practices, meditation, mountain walks and a plan for returning to work. Burnout is not a diagnosis, but if there are signs of depression we bring in the right specialists.',
    plan:['Screening, sleep and routine','Sessions, practices and the mountains','A plan for returning to work'],
    tip:'October–January: from February to April, Chiang Mai is smoky.' },
  // ── Recovery ────────────────────────────────────────────────────
  'sauna-ice':{ title:'Sauna and ice bath course', where:'Phuket',
    short:'Contrast protocols, breathwork and HRV tracking. The best thing you can do after a long flight.',
    about:'Five sessions at a contrast therapy studio: sauna, ice bath, breathing practices and heart rate variability (HRV) tracking on your own watch. It helps you recover after training and flights. Before the course there is a short questionnaire: with heart or blood pressure problems, cold exposure isn’t for everyone.',
    plan:['Briefing and a gentle protocol','Longer in the cold, breathing practices','Final HRV measurements'] },
  'thai-massage':{ title:'Thai massage and stretching in Chiang Mai', where:'Chiang Mai',
    short:'A two-hour massage every day from old-school masters, plus stretching for your back.',
    about:'Chiang Mai is the capital of traditional Thai massage. Five days of two-hour sessions with old-school masters: work on your back and hips, plus stretching. If you want to learn it yourself, we can enroll you in a course at a school attached to a traditional medicine hospital.',
    plan:['Assessment and a gentle massage','Deep work and stretching','Final session and exercises for home'], tip:'November–February.' },
  'sports-recovery':{ title:'Sports recovery week', where:'Phuket',
    short:'A physiotherapist, sports massage, mobility and cold exposure, for men who came to fight and overdid it.',
    about:'A recovery week after a camp, a marathon or an injury: four physiotherapy sessions, five sports massages, contrast therapy and mobility work. Accommodation can be added if needed.',
    plan:['Physiotherapist assessment','Massage, mobility, cold','Final assessment and exercises'] },
  'spa-week':{ title:'Men’s spa week in Bali', where:'Bali',
    short:'A villa with a pool, daily treatments, yoga for the inflexible and silence.',
    about:'Balinese massage, a villa among the rice terraces of Ubud, yoga for men who have never tried it and no schedule except your treatments. Ideal after a hard year or between two projects.',
    plan:['Check-in and your first massage','Treatments, yoga and walks','Departure'], tip:'April–October is the dry season.' },
  'onsen':{ title:'Onsen and ryokan stays in Japan', where:'Hakone and Kyoto',
    short:'Hot springs, a kaiseki dinner and the best sleep of your life. Price per person.',
    about:'Two nights at a Hakone ryokan with a private onsen and mountain views, two in Kyoto, with a train ride and a guided day in between. The Japanese ritual of bathing and a kaiseki dinner resets you better than any spa. The price is per person, based on double occupancy.',
    plan:['Hakone: ryokan and onsen','Train to Kyoto','Temples with a guide and a ryokan'],
    tip:'November and late March–April; January–February has the best prices. Guests with tattoos are often not allowed into shared baths.' },
  'banya':{ title:'Russian banya with a steam master', where:'Moscow region or Altai',
    short:'A real steam session, a cold plunge, herbal tea and massage, over two days.',
    about:'A session with a steam master is more than a sauna: the venik (leafy birch or oak whisks), the temperature, the rhythm and the cold plunge are all tailored to you. Two sessions with a steam master, a massage, a night at a country retreat and transfers.',
    plan:['Arrival, first session and dinner','Second session, massage and departure'], tip:'October–March.' },
  'dead-sea':{ title:'Dead Sea: back and joints', where:'Jordan',
    short:'Mud, mineral water and physiotherapy at the lowest point on land.',
    about:'About 430 meters below sea level: dense water, mineral mud and distinctive air. Seven nights at a spa hotel, a doctor’s assessment, six treatments and three physiotherapy sessions. The effects are best studied for skin conditions; for joints the evidence is moderate, and we say so openly.',
    plan:['Doctor’s assessment and program','Treatments and physiotherapy','Wrap-up and recommendations'], tip:'October–April.' },
  // ── Mind & calm ─────────────────────────────────────────────────
  'silent-retreat':{ title:'Silent retreat: 10 days of meditation', where:'Chiang Mai',
    short:'Meditation, silence and simple food. We take care of the journey and support.',
    about:'Classic ten-day meditation courses (such as Vipassana in the tradition of S.N. Goenka) are run free of charge, on donations, and that is how it should stay. So we don’t sell the course itself: we help you choose a center and register, and arrange the transfer, a hotel before and after, and someone to meet you when you finish. For a gentler option, there is a private retreat with a mentor (from $1,500).',
    plan:['Choosing a center and registering','Transfer and the night before the start','Ten days of the course','Pickup, rest and a conversation afterward'],
    tip:'Intensive meditation is not for everyone. Tell us about any mental health conditions in advance.' },
  'breathwork':{ title:'Breathwork and cold in Bali', where:'Bali',
    short:'Breathing practices, ice water and stress management, over five days.',
    about:'Five days of breathwork and contrast cold exposure with a certified instructor, plus yoga, sauna and a quiet villa. The safety rule: breath-hold practices never in or near water. Before you start, there is a health questionnaire.',
    plan:['Fundamentals and safety','Practices, ice and sauna','Integration and a plan for home'] },
  'mens-retreat':{ title:'Men’s retreat in the Altai', where:'Altai',
    short:'A men’s group, mountains, a campfire, a banya and honest conversations with a facilitator.',
    about:'Five days in the Altai Mountains with a small group of men: hikes, rafting, a banya and evening circles around the fire with an experienced facilitator. For men who want to put into words the things they usually keep to themselves, in the company of men like them.',
    plan:['The group gathers at base','Hikes, rafting, banya and circles','Closing'],
    tip:'June–September. Get vaccinated against tick-borne encephalitis beforehand; some areas are border zones that require a permit.' },
  'coaching':{ title:'Performance coaching', where:'Online',
    short:'Goals, energy and focus: six sessions with a coach who has worked with business owners.',
    about:'Six 60-minute video sessions with an ICF-certified coach: assessment, quarterly goals, energy management, delegation and focus. Between sessions, you stay in touch over WhatsApp or Telegram. Coaching is not psychotherapy: if your state of mind needs attention, we bring in a psychologist.',
    plan:['Assessment and goals','Working through the plan','Results and a plan for the next quarter'] },
  'monk-week':{ title:'A week in a Buddhist monastery', where:'Northern Thailand',
    short:'Early mornings, meditation, work and silence. We handle the journey and your preparation.',
    about:'A monastery stay is not a tourist product, and we don’t sell it: the abbot decides whether to accept you, and you make any donation yourself. We prepare you for the trip, explain the rules (the eight precepts, no food after noon, no phone), and arrange a car from Chiang Mai, a hotel before and after, and white clothing.',
    plan:['Preparation: rules and etiquette','Transfer and a night in Chiang Mai','Five days at the monastery','Return and rest'], tip:'November–January.' },
  'psychologist':{ title:'Psychologist for men', where:'Online',
    short:'Crisis, divorce, anxiety, anger: eight sessions with a psychologist who understands men.',
    about:'We match you with a psychologist based on your needs and communication style: eight 50-minute online sessions in English. A psychologist is not a medical doctor: if medical care is needed, we refer you to a psychiatrist. There is a crisis protocol for acute situations.',
    plan:['Matching you with a specialist through a questionnaire','Weekly sessions','Wrap-up and recommendations'] },
  'meditation-21':{ title:'Meditation for busy men: 21 days', where:'Online',
    short:'Ten minutes a day with a mentor and progress tracking.',
    about:'Twenty-one short practices, three live group sessions and a chat with your mentor. For men who want to learn to switch off and sleep better without heading off to the mountains.',
    plan:['Intro session','Daily 10-minute practice','Final session'] },
  // ── Adventure ───────────────────────────────────────────────────
  'elbrus':{ title:'Mount Elbrus climb', where:'Caucasus',
    short:'The highest point in Europe, 5,642 m, with acclimatization, guides and a reserve day.',
    about:'A climb via the classic south route: eight days with guides, acclimatization hikes above 4,000 meters, mountain huts, an optional snowcat ride and the summit push. The route is not technical, but the weather at the top is dangerous, so the guide makes the calls and a reserve day is mandatory.',
    plan:['Arrival and acclimatization on Cheget','Hikes above 4,000 m and the mountain hut','Summit push and reserve day','Descent and the trip home'],
    tip:'June–September. For foreign visitors: Visa and Mastercard cards don’t work in Russia, and Western insurance policies often don’t cover trips there.' },
  'kilimanjaro':{ title:'Kilimanjaro via the Machame route', where:'Tanzania',
    short:'The roof of Africa, 5,895 m. Guides, porters, camps and an optional safari.',
    about:'Machame is the most scenic route up Kilimanjaro, with good acclimatization: a climb through five climate zones and a night summit push to Uhuru Peak. Park fees, guides, porters, tents, meals and two nights in Moshi are included. A safari after the climb is the best way to celebrate.',
    plan:['Moshi and briefing','The Machame route, camp to camp','Uhuru summit push and descent','Summit certificate and rest'],
    tip:'January–March and June–October; April–May and November are rainy. Park fees are revised from time to time, so we confirm them when you book.' },
  'ebc':{ title:'Everest Base Camp trek', where:'Nepal',
    short:'Lukla, Namche Bazaar, 5,364 m. Lodges, a licensed guide and porters.',
    about:'The classic trek through the Khumbu Valley: a flight to Lukla, Namche Bazaar, Tengboche Monastery and Everest Base Camp at 5,364 m. A licensed guide is required under Nepal’s rules, with one porter for every two trekkers. In peak season, flights to Lukla leave from Ramechhap, so we build in spare days.',
    plan:['Kathmandu and the flight to Lukla','Ascent via Namche and Tengboche, with acclimatization','Base Camp and Kala Patthar','Descent and back to Kathmandu'],
    tip:'March–May and October–November. You need insurance that covers helicopter evacuation.' },
  'kamchatka':{ title:'Kamchatka: volcanoes and fishing', where:'Kamchatka',
    short:'A helicopter to the Valley of Geysers, a volcano climb and salmon on the river.',
    about:'Ten days at the edge of the world: a climb up Avachinsky or Gorely volcano, a helicopter day with landings in the Valley of Geysers and the Uzon Caldera, and rafting and fishing on the Bystraya River. Helicopters depend on the weather, so two days of the program are kept flexible.',
    plan:['Arrival and hot springs','Volcano climb','Helicopter to the Valley of Geysers (weather permitting)','Rafting and fishing'], tip:'July–September.' },
  'moto-north':{ title:'Motorbike tour of northern Thailand', where:'Mae Hong Son Loop',
    short:'1,864 curves, mountains, mist and nights in mountain lodges.',
    about:'The legendary Mae Hong Son Loop: seven days on an enduro or touring motorcycle with a guide and a support vehicle, mountain passes, villages and mist over the valleys. You need a category A motorcycle license and an International Driving Permit endorsed for “A”; without them, the insurance is not valid.',
    plan:['Chiang Mai and choosing your bike','The loop via Pai and Mae Hong Son','Return to Chiang Mai'],
    tip:'November–February; March–April brings smoke, June–October brings rain.' },
  'safari':{ title:'Safari in Kenya and Tanzania', where:'Maasai Mara and Serengeti',
    short:'The Great Migration, lodges and top guides, over eight days.',
    about:'Eight days in a pop-top 4x4 through the Maasai Mara and the Serengeti: the wildebeest migration, the Mara River crossings and the Big Five. Full-board lodges, park fees and the transfer between the two countries are included. Nobody can guarantee a crossing, but the guides know where to wait.',
    plan:['Maasai Mara','Crossing into Tanzania','Serengeti and Ngorongoro Crater','Departure'],
    tip:'July–October for the migration in the Mara; January–February for calving season in the southern Serengeti.' },
  'railay-climb':{ title:'Rock climbing in Railay', where:'Krabi',
    short:'Limestone cliffs above the sea. From zero to your first lead climb.',
    about:'Railay is one of the best climbing areas in Asia, with limestone walls rising right above the beach. A three-day course with an instructor, from top-roping to your first lead climb, plus three nights on Railay, which you can only reach by boat.',
    plan:['Technique and top-roping','Lead belaying and lowering off','Your first lead climb'], tip:'November–April.' },
  'altai-horse':{ title:'Horseback trek in the Altai', where:'Altai',
    short:'Mountain passes, alpine lakes and nights in tents: seven days in the saddle.',
    about:'A week in the saddle across the Altai Mountains: passes, glacial lakes, nights in tents and at mountain camps, full board and experienced guides. No riding experience needed: the horses are matched to each rider. Routes toward Belukha require a border zone permit, which we arrange in advance.',
    plan:['Base and briefing','The route over passes and past lakes','Return'], tip:'Late June to early September.' },
  'uzbek-mountains':{ title:'Uzbekistan’s mountains: Chimgan and Pskem', where:'Uzbekistan',
    short:'ERKAK’s homeland: trekking, mountain rivers and plov by the fire.',
    about:'Six days in the Western Tian Shan, two hours from Tashkent: Greater Chimgan (3,309 m), the Beldersay and Pskem gorges, and nights in tents and guesthouses. These are the very mountains that ERKAK shilajit comes from. Routes near the Kyrgyz border require a permit, which we arrange.',
    plan:['Tashkent and the drive into the mountains','Trekking in Chimgan and Pskem','Return'], tip:'June–September.' },
  // ── Ocean ───────────────────────────────────────────────────────
  'padi-ow':{ title:'Learn to dive: PADI Open Water', where:'Phuket',
    short:'An internationally recognized certification in four days. Your first dives are at the Racha islands.',
    about:'The PADI Open Water course: theory, pool sessions and four open-water dives from a boat. The certification is recognized worldwide and lets you dive to 18 meters (60 feet). Three nights at a hotel near the dive center are included. Before the course there is a medical questionnaire; after your last dive you can’t fly for 18 hours.',
    plan:['Theory and pool','Pool and first dives','Dives at the Racha islands and certification'], tip:'November–April; from May to October, expect swell and cancellations.' },
  'similan-dive':{ title:'Similan Islands liveaboard', where:'Khao Lak',
    short:'Thailand’s best diving: Koh Bon, Koh Tachai and Richelieu Rock, four days on board.',
    about:'The Similans are a national park and the country’s top dive area: manta rays and whale sharks in February–April, the reefs of Koh Bon and Koh Tachai, and Richelieu Rock. Four days on a liveaboard, about 14 dives, a cabin and meals. Fishing is banned in the park: this is a program for divers, not anglers.',
    plan:['Departure from Tap Lamu and first dives','Koh Bon, Koh Tachai, Richelieu Rock','Final dives and return'],
    tip:'The park is open roughly from October 15 to May 15. We recommend an Advanced certification and 20+ logged dives.' },
  'freediving':{ title:'Learn to freedive on Koh Tao', where:'Koh Tao',
    short:'Breathing, breath-holds and your first 10–20 meters on a single breath.',
    about:'Koh Tao is one of Asia’s freediving centers. An entry-level course (AIDA, SSI or Molchanovs): theory, breath-holds in the pool, line diving in the sea and certification. The golden rule: always with a buddy and an instructor.',
    plan:['Theory and pool','Open water: line dives','Final dives and certification'], tip:'March–September; November is the worst month in the Gulf of Thailand.' },
  'surf-camp':{ title:'Surf camp in Bali', where:'Bali',
    short:'An instructor, a board and video review. Most beginners stand up within the first few days.',
    about:'A week at a surf camp: 5–10 lessons, a board, transfers to the breaks, video review and yoga. The season decides the coast: from April to October, conditions are good on the west side and the Bukit, from November to March on the east. Beginners can surf year-round.',
    plan:['Safety and first attempts in the whitewater','Lessons and video review','Surfing on your own with an instructor nearby'],
    tip:'In March, Bali observes the Day of Silence (Nyepi), and the whole island shuts down for 24 hours.' },
  'kite':{ title:'Learn to kitesurf', where:'Hua Hin and Pranburi',
    short:'IKO certification and steady wind from November to April.',
    about:'An IKO course: 9–12 hours with an instructor, a radio helmet, all equipment and certification. Hua Hin and Pranburi are the best kite spots on the Gulf of Thailand during the northeast monsoon. You can’t order the wind, so we build in two spare days.',
    plan:['Kite control on the beach','Body dragging and first water starts','Riding and certification'], tip:'November–April; in summer, kitesurfers head to Phuket.' },
  'sailing':{ title:'Skipper sailing course', where:'Phuket',
    short:'Hands-on sailing in the Andaman Sea and an international certificate.',
    about:'A week on a yacht with an instructor (up to five students on board): navigation, mooring, night passages and sail handling. You finish with an international skipper certificate; the certifying body depends on the school. To charter a yacht on your own you will also need a radio operator’s license, and we can tell you how to get one.',
    plan:['Theory and maneuver drills','Island-to-island passages and a night passage','Exam and certificate'], tip:'November–April.' },
  'yacht-week':{ title:'Yacht week with friends', where:'Andaman Sea',
    short:'A catamaran, a skipper, a cook and the islands of Phang Nga. Price per person, based on eight guests.',
    about:'A week on a 45–50-foot sailing catamaran with a skipper and a cook: Phang Nga Bay, the islands of Krabi and Phi Phi, fishing from the boat outside the national parks, snorkeling and dinners on deck. The price assumes eight guests; fuel and provisions are charged at cost.',
    plan:['Boarding and Phang Nga Bay','The islands of Krabi and Phi Phi','Return'], tip:'November–April; Maya Bay is closed from August 1 to September 30.' },
  'wakeboard':{ title:'Wakeboard camp in Pattaya', where:'Pattaya',
    short:'A cable wake park with a coach: from your first starts to tricks.',
    about:'Five days at a cable wake park: a coach, equipment and video review. A cable is easier to learn on than a boat, and most people are up on the board on the first day.',
    plan:['Starts and basic stance','Turns, jumps and video review','First tricks'], tip:'November–February.' },
  'maldives-surf':{ title:'Maldives surf charter', where:'Maldives',
    short:'A boat, the best reef breaks and fishing at sunset.',
    about:'A week on a surf boat with a guide: reef breaks you can’t reach from the resorts, full board and fishing at sunset. For confident surfers only: the reefs are shallow.',
    plan:['Boarding in Malé','Surfing the atoll’s reefs','Return'], tip:'March–October; the biggest swells come in June–August.' },
  // ── Golf & padel ────────────────────────────────────────────────
  'golf-phuket':{ title:'Golf week in Phuket', where:'Phuket',
    short:'The island’s five best courses, caddies, a hotel and transfers with your clubs.',
    about:'Five rounds on Phuket’s best courses, including Blue Canyon, Red Mountain and Laguna, a caddie on every course (they are mandatory in Phuket), a 4★ hotel and transfers with your bags. We book peak tee times from December to March well in advance.',
    plan:['Arrival and hotel','Five rounds on different courses','A rest day or a day of fishing'], tip:'November–April; from May to October, green fees are 20–40% lower.' },
  'golf-school':{ title:'Learn to play golf', where:'Hua Hin',
    short:'Daily lessons with a PGA pro, and out on the course by the end of the week.',
    about:'Hua Hin is Thailand’s classic golf destination. Five days of lessons with a certified pro: stance, swing, short game, rules and etiquette, and at the end, your first nine holes.',
    plan:['Stance, swing, driving range','Short game and putting','Your first holes on the course'], tip:'November–April.' },
  'padel-camp':{ title:'Padel camp in Dubai', where:'Dubai',
    short:'The fastest-growing sport: technique, tactics and a tournament within the group.',
    about:'Interest in padel in the UAE has multiplied in recent years, and Dubai has become one of its capitals. Five days with a coach: 10–15 hours of technique and tactics, games with partners at your level and a tournament at the end.',
    plan:['Level assessment','Technique, tactics and games','Tournament'], tip:'November–March; in summer, indoor courts only. We plan around the dates of Ramadan.' },
  'tennis-camp':{ title:'Tennis camp in Mallorca', where:'Mallorca',
    short:'Academy coaches, video analysis and match play.',
    about:'A week in the adult program of a tennis academy in Mallorca: 15–20 hours of tennis, fitness training, video analysis of your strokes and accommodation at the academy.',
    plan:['Assessment and video analysis','Training and match play','Final matches'], tip:'March–June and September–November. Spain is in the Schengen Area; visa requirements depend on your passport.' },
  'golf-scotland':{ title:'Golf in Scotland: St Andrews', where:'St Andrews',
    short:'The home of golf: the Old Course and classic links.',
    about:'A week at the home of golf: a shot at the Old Course through the daily ballot (or a pricier guaranteed package), Kingsbarns, Carnoustie and other links, a hotel and a driver. The Old Course requires a handicap: 24 or lower for men.',
    plan:['Arrival in St Andrews','Rounds on the links and the Old Course ballot','Departure'], tip:'May–September. Depending on your passport, the UK requires an ETA (electronic travel authorization) or a visa; we help with the paperwork.' },
  'padel-bali':{ title:'Padel and wellness in Bali', where:'Bali',
    short:'Padel in the morning, surf in the afternoon, spa in the evening.',
    about:'A week with sport and rest in the right proportion: padel with a coach in the early morning, surf or the pool during the day, a massage in the evening and a villa in Canggu.',
    plan:['Check-in and first game','Padel, surf and spa','Departure'], tip:'April–October.' },
  // ── Men’s aesthetics ────────────────────────────────────────────
  'hair':{ title:'Hair transplant in Istanbul', where:'Istanbul',
    short:'An accredited clinic, a photo consultation before you travel, hotel and support.',
    about:'Turkey is the world center of hair transplants, which is exactly why it has so many conveyor-belt clinics where technicians do the surgery. We work only with clinics where a doctor performs the extraction and the incisions and the number of grafts is documented. A photo consultation, FUE or DHI surgery, PRP, medication, 2–3 nights at a hotel and transfers.',
    plan:['Consultation and a plan based on photos','Arrival, blood tests and hairline marking','Surgery','Dressing change, follow-up and flight home'],
    tip:'October–April. Standard travel insurance does not cover elective surgery.' },
  'dental':{ title:'Dental implants and veneers in Bangkok', where:'Bangkok',
    short:'International clinics, a treatment plan before you fly and a hotel nearby. Price per implant.',
    about:'Bangkok is one of the world’s leading dental travel destinations. An implant with abutment and crown (Korean systems or Straumann/Nobel) and ceramic veneers. The clinic draws up a treatment plan from your X-rays before you fly. Implants require two trips 3–6 months apart; veneers take about a week.',
    plan:['X-rays and a treatment plan before the trip','CT scan and implant placement','Crowns 3–6 months later','Warranty and follow-up'],
    tip:'We make sure healthy teeth are not ground down without good reason.' },
  'lasik':{ title:'Laser vision correction', where:'Bangkok',
    short:'Diagnostics, surgery and follow-up. The next day, you can be on the beach in sunglasses.',
    about:'Femto-LASIK or SMILE at a specialized eye clinic: full diagnostics, surgery on both eyes, medication and follow-ups on day one and day seven. It is not suitable for everyone: the doctor decides after the examination.',
    plan:['Diagnostics','Surgery','Follow-up and rest'], tip:'No pool or sea swimming for 2–4 weeks.' },
  'skin-seoul':{ title:'Men’s skincare in Seoul', where:'Seoul',
    short:'Skin, pigmentation and care: Korean protocols for men.',
    about:'Five days at Seoul clinics: a dermatologist consultation, device-based treatments where indicated, skincare and recovery. We work through registered agencies: foreigners in Korea are often quoted higher prices, and we keep that in check.',
    plan:['Consultation and plan','Treatments','Follow-up and recommendations'], tip:'October–April.' },
  'style':{ title:'Personal styling in Dubai', where:'Dubai',
    short:'A stylist, a barber and a wardrobe that fits the way you live.',
    about:'Two days with a stylist: a wardrobe review, a day of shopping at Dubai’s best department stores, a barber and a tailor. You buy the clothes yourself; we take no commission on your purchases. Tourists can reclaim the 5% VAT.',
    plan:['Style brief and barber','Shopping and fittings'], tip:'November–March; the Dubai Shopping Festival runs December–January.' },
  // ── Nutrition & supplements ─────────────────────────────────────
  'nutritionist':{ title:'Nutritionist guided by your lab results', where:'Online',
    short:'A review of your lab results, a meal plan and four weeks of support.',
    about:'A questionnaire, a referral for lab tests, a review of the results with a doctor specializing in nutrition, a meal plan for your goals and two follow-up meetings. Only a doctor can make a diagnosis, which is why we work with licensed specialists.',
    plan:['Questionnaire and lab tests','Review and meal plan','Two follow-up meetings'] },
  'erkak-stack':{ title:'ERKAK 90-day protocol', where:'Worldwide delivery',
    short:'D3+K2, zinc, magnesium and omega-3, with a certificate of analysis for every batch. A follow-up lab test at 90 days.',
    about:'A set of four ERKAK products for the full cycle up to your follow-up test: vitamin D3 with K2, zinc with selenium, magnesium and omega-3. Every jar carries its batch certificate of analysis. Not a medicinal product.',
    plan:['Baseline lab tests','90 days on the protocol','Follow-up lab test'] },
  'chef-prep':{ title:'Private chef and a meal plan', where:'Phuket',
    short:'A chef who cooks for your goals and training. Price for two, groceries included.',
    about:'Seven days with a private chef at your villa: a menu built around calories and macros, grocery shopping, breakfast and dinner, and kitchen cleanup. The alternative is daily delivery of ready-made meals. All allergies in writing before you start.',
    plan:['Brief and menu','Seven days of eating to plan','Recipes to take home'] },
  'shilajit-tour':{ title:'Shilajit trip to the Chimgan mountains', where:'Uzbekistan',
    short:'Where ERKAK shilajit comes from: the mountains, the gatherers and the lab.',
    about:'Three days in the Western Tian Shan: a trip with a guide to the places where shilajit is gathered, meeting the gatherers, a visit to the lab where the raw material is purified and tested, and an evening of plov in the mountains.',
    plan:['Tashkent and the Chimgan mountains','Gathering sites and gatherers','The lab and the return trip'], tip:'May–October.' },
  // ── Father & son ────────────────────────────────────────────────
  'father-son-thai':{ title:'Father and son: fishing and Muay Thai', where:'Phuket',
    short:'The ring in the morning, the ocean in the afternoon. For sons aged 10 and up. Price for two.',
    about:'Five days your son will remember for the rest of his life: five Muay Thai sessions together with a coach, two days of fishing on a private boat, a hotel and transfers. Kids’ classes at the camps start from age 6–8, and there are children’s life jackets on the boat.',
    plan:['Arrival and first session','Training and fishing','Fishing and a final session'], tip:'November–April, when the sea is calm.' },
  'family-krabi':{ title:'Family adventure in Krabi', where:'Krabi',
    short:'Cliffs, kayaks, islands and elephants at an ethical sanctuary. Price per person.',
    about:'A week for the whole family: kayaking through mangrove mazes, islands by private boat, an ethical elephant sanctuary with no riding, the beaches of Railay and a resort with a kids’ club.',
    plan:['Resort and beaches','Kayaks, islands and the sanctuary','Downtime'], tip:'November–April; Maya Bay is closed in August–September.' },
  'teen-camp':{ title:'Sports camp for teens', where:'Phuket',
    short:'Sport and English lessons while parents relax nearby.',
    about:'Two weeks for teens aged 12–17: Muay Thai, swimming, surfing, daily English lessons and camp counselors. Ready-made international residential camps in Phuket are few, so we build the program on request, with vetted staff and written parental consent.',
    plan:['Sport and English','Tournament, excursions and wrap-up'], tip:'December–January and spring break.' },
  'father-son-nepal':{ title:'Father and son in the mountains of Nepal', where:'Nepal',
    short:'A trek to Poon Hill or Annapurna Base Camp, for sons aged 14 and up.',
    about:'Ten days in the Himalayas, just the two of you: a trek to Poon Hill (3,210 m), the gentler option for teenagers, or to Annapurna Base Camp (4,130 m) for those who are well prepared. Guide, porter, lodges and permits are included. The price is per person.',
    plan:['Kathmandu and Pokhara','The trek','Return to Kathmandu'], tip:'March–May and October–November.' },
  // ── Teams & friends ─────────────────────────────────────────────
  'corp-retreat':{ title:'Leadership team retreat', where:'Phuket',
    short:'Strategy sessions in the morning, sport and the ocean in the afternoon. Price per participant.',
    about:'Four days for a leadership team: morning strategy sessions with a facilitator, a yacht, fishing or Muay Thai in the afternoon, and dinners in the evening. A 5★ hotel with meeting rooms, full paperwork and an invoice for your company.',
    plan:['Arrival and dinner','Strategy sessions and activities','Wrap-up and departure'], tip:'November–April.' },
  'founders':{ title:'Founders’ retreat', where:'Bali',
    short:'A small group of business owners: strategy, health and quiet.',
    about:'Five days in a small group of founders: strategy sessions, working through each other’s cases, training, sleep and quiet. A villa, a facilitator and a program you come home from with a plan.',
    plan:['Introductions and goals','Sessions and practices','Plans and closing'], tip:'April–October. A visa on arrival does not give you the right to work.' },
  'regatta':{ title:'Corporate regatta', where:'Phuket',
    short:'Teams on identical yachts, judges, trophies and dinner. Price per participant.',
    about:'Two days of sailing races for your team: identical yachts with skippers, a race officer and official results, trophies and an awards dinner. The King’s Cup Regatta takes place in Phuket in the first week of December, so we book hotels well ahead for those dates.',
    plan:['Briefing and a practice race','Regatta and awards ceremony'], tip:'November–April.' },
  'bachelor':{ title:'Premium bachelor party', where:'Phuket or Dubai',
    short:'A yacht, fishing, Muay Thai and a chef’s dinner. No clichés. Price per participant.',
    about:'Three days you can safely tell stories about at the wedding: a villa or a 5★ hotel, a day on a yacht with fishing, a Muay Thai session for the whole group and a chef’s dinner. The rules are simple: vapes are banned in Thailand, and the UAE has zero tolerance for drugs.',
    plan:['Check-in and dinner','Yacht and fishing','Muay Thai and the final night'] }
};

export const destinations = {
  phuket:{ name:'Phuket', title:'Phuket for men: fishing, Muay Thai, golf and the ocean',
    intro:'Phuket is ERKAK’s main base and the best island in Thailand for an active men’s getaway. Trophy fishing off the Racha islands, Muay Thai camps on Soi Ta-iad, five golf courses, diving, yachts and recovery, all within an hour’s drive.',
    season:'November–April is the dry season, with calm seas and peak prices in December–February. May–October is the monsoon: offshore trips are often canceled, but camps and golf courses cost less.',
    access:'Direct flights from Europe, the Gulf and Asia; connections via Dubai, Doha, Istanbul and Bangkok. Citizens of the EU, UK, US and GCC countries enter visa-free for 30 days; for other passports, we check the rules and help with a visa.' },
  bangkok:{ name:'Bangkok', title:'Bangkok for men: check-ups, Muay Thai and freshwater giants',
    intro:'Bangkok is one of the world’s medical travel hubs and the capital of Muay Thai. This is where you can do an executive check-up in a day, get dental work or laser eye surgery, train in legendary gyms and catch Mekong giant catfish an hour from the city.',
    season:'The best time is November–February. March to May is very hot and June to October is rainy, but medical programs and freshwater fishing run year-round.',
    access:'Suvarnabhumi Airport is a major hub with direct flights from Europe, the Gulf and across Asia. Hospitals are 40–60 minutes away.' },
  samui:{ name:'Koh Samui and Koh Tao', title:'Koh Samui: detox, villa Muay Thai and freediving on Koh Tao',
    intro:'Koh Samui is an island of classic wellness retreats, villas overlooking the Gulf of Thailand and an unhurried pace. Nearby is Koh Tao, one of Asia’s freediving and diving centers.',
    season:'January–September is the best time. October–December is the rainy season in the Gulf of Thailand.',
    access:'Samui Airport has flights from Bangkok and Singapore; Koh Tao is a 1.5–2-hour ferry ride away.' },
  'chiang-mai':{ name:'Chiang Mai', title:'Chiang Mai: mountains, calm, massage and motorbike trips',
    intro:'Northern Thailand means cool mountain air, meditation centers, old-school massage, mountain trails for running and the legendary Mae Hong Son motorbike loop.',
    season:'November–January is cool and clear. From February to April the north is smoky from field burning, and we don’t recommend those months. June–October is rainy.',
    access:'Direct flights from Bangkok (about an hour) and other Asian hubs.' },
  krabi:{ name:'Krabi and Khao Lak', title:'Krabi and Khao Lak: cliffs, the Similans, jungle and islands',
    intro:'The limestone cliffs of Railay, Similan liveaboards from Khao Lak, Cheow Lan Lake in the Khao Sok jungle and quiet islands for families: the best of nature on the Andaman coast.',
    season:'November–April. Similan Islands National Park is open roughly from October 15 to May 15.',
    access:'Krabi and Phuket airports; Khao Lak is about an hour from Phuket airport.' },
  gulf:{ name:'Hua Hin and Pattaya', title:'Hua Hin and Pattaya: kite, golf and wake near Bangkok',
    intro:'The Gulf of Thailand coast, two to three hours from Bangkok: the kite spots of Pranburi, the classic golf courses of Hua Hin, wake parks and fishing around the islands off Pattaya.',
    season:'November–April is dry and windy, the best season for kitesurfing and golf.',
    access:'A 2–3-hour transfer from Bangkok; Pattaya also has its own airport, U-Tapao.' },
  bali:{ name:'Bali', title:'Bali: surf, sober retreats, spa and founders’ retreats',
    intro:'Bali is an island of surf, spas and retreats: surf camps on the west coast, breathwork and spas in Ubud, sober and men’s retreats, padel and a strong community of founders.',
    season:'April–October is the dry season. In March comes the Day of Silence (Nyepi), when the island shuts down for 24 hours.',
    access:'Denpasar airport; visa on arrival for many passports, plus a tourist levy.' },
  dubai:{ name:'Dubai', title:'Dubai: biohacking, padel, strength 40+ and style',
    intro:'Dubai is a city of licensed recovery clinics, padel and top-tier service: medically supervised biohacking, strength programs for men 40+, padel camps and style.',
    season:'November–March. In summer, everything moves indoors. We plan around the dates of Ramadan.',
    access:'Direct flights from most major cities; UK, US, EU and GCC passport holders don’t need to apply for a visa in advance.' },
  caucasus:{ name:'Caucasus', title:'Caucasus: Elbrus, altitude camps and skiing',
    intro:'The highest point in Europe, the Olympic base at Tsaghkadzor and the freeride of Gudauri: the Caucasus for men who love altitude.',
    season:'June–September for climbs and training camps; December–March for skiing.',
    access:'Mineralnye Vody or Nalchik (Russia) for Elbrus; Yerevan for Tsaghkadzor; Tbilisi for Gudauri.' },
  'central-asia':{ name:'Central Asia', title:'Central Asia: boxing in Almaty and Uzbekistan’s mountains',
    intro:'ERKAK’s homeland: the Kazakh school of boxing in Almaty, the mountains of the Western Tian Shan and the places in Chimgan where shilajit is gathered.',
    season:'May–October in the mountains; boxing in spring and fall.',
    access:'Direct flights to Almaty and Tashkent from Dubai, Istanbul and a number of European and Asian cities.' },
  russia:{ name:'Altai and Kamchatka', title:'Altai and Kamchatka: men’s retreats, horse treks and volcanoes',
    intro:'Russia’s wild nature: men’s retreats and horseback treks in the Altai, the volcanoes and Valley of Geysers of Kamchatka, and a real banya.',
    season:'July–September; banya season is October–March.',
    access:'Barnaul or Gorno-Altaysk; Petropavlovsk-Kamchatsky. For foreign visitors: Visa and Mastercard cards don’t work in Russia, and entry requirements depend on your passport; we check them for you.' },
  'east-africa':{ name:'East Africa', title:'East Africa: Kilimanjaro, safari and running in Iten',
    intro:'The roof of Africa, the Great Migration and the town of world running champions: the continent’s three great adventures for men.',
    season:'January–March and June–October; the migration in the Maasai Mara runs July–October.',
    access:'Kilimanjaro and Nairobi airports; apply online in advance for Kenya’s eTA and Tanzania’s e-visa.' },
  europe:{ name:'Europe', title:'Europe: golf in Scotland, tennis, cycling camps and fasting',
    intro:'European classics: St Andrews, a tennis academy and cycling camps in Mallorca, and the fasting clinics of Germany and Austria.',
    season:'Spring and fall; Scotland in May–September.',
    access:'Schengen rules for Spain, Germany and Austria depend on your passport; the UK requires an ETA or a visa, depending on your passport.' },
  'east-asia':{ name:'Japan and Korea', title:'Japan and Korea: onsen, check-ups and skincare',
    intro:'Japanese ryokan with hot springs, check-ups at Seoul’s leading hospitals and Korean skincare protocols.',
    season:'Spring and fall; onsen season runs from November to March.',
    access:'Visa rules for Japan and Korea depend on your passport — we check them for you.' },
  nepal:{ name:'Nepal' }, india:{ name:'India' }, jordan:{ name:'Jordan' }, maldives:{ name:'Maldives' }, istanbul:{ name:'Istanbul' }, online:{ name:'Online' }
};
