// ERKAK · English · “Fishing in Thailand” section: landing, tours, spots, calendar, quiz.
export default {
  metaTitle:'Phuket & Andaman Sea Fishing Charters with Concierge | ERKAK',
  metaDesc:'Fishing in Phuket, Khao Lak and Bangkok: sailfish, marlin, GT, tuna, Mekong catfish. Private boats, licensed guide, English-speaking concierge. From 4,900 THB.',
  chip:'Season open · Andaman Sea',
  title:'Trophy fishing in Thailand. *Legal, in plain English, fully arranged.*',
  lede:'Sailfish, marlin, GT and tuna in the Andaman Sea. Private boats, a licensed guide and an English-speaking concierge.',
  proof:[['0','fishing trips in national parks'],['≤ 6','anglers per group'],['30%','deposit'],['24/7','concierge on call']],
  subnav:[['Tours','tours'],['Who it’s for','who'],['Concierge','concierge'],['Map','map'],['Season','season'],['FAQ','faq']],
  pains:{ kicker:'Why fishing trips disappoint', title:'Four ways to lose a day at sea. *We’ve ruled out every one.*', items:[
    ['A tour boat with 40 people','An old launch, a crowd, a handline wrapped around a stick, and twenty minutes of fishing squeezed between snacks and snorkeling.','Private boats and small groups of up to six anglers. The time goes to fishing.'],
    ['A fine for fishing in a national park','Fishing trips to the Similans and Phi Phi are still being sold, even though fishing there is illegal: fines of up to 500,000 THB and criminal liability.','Permitted waters only: the shelf, FADs, the Racha islands. A licensed operator and a licensed Thai guide on board.'],
    ['A captain who doesn’t get what you want','Hand signals, a translation app, and a trip to “the usual spot” instead of the fish you came for.','An English-speaking concierge on call before, during and after the trip. We brief the captain in advance.'],
    ['An empty trip out of season','You’re sold sailfish in a month when there are none, or a day so windy you can’t get past the reef.','We pick the date and format by the bite calendar, the forecast and the moon phase. If your fish is out of season, we’ll tell you straight.'],
    ['Tackle that can’t handle a trophy','Tired braid, rusty hooks and a reel that gives up on the first 20 kg fish.','Shimano Stella and Daiwa Saltiga, PE 6–10 braid, fresh hooks for every Pro trip.'],
    ['Paying a stranger up front','Cash in advance or a transfer to the captain’s personal account, with no receipt and no recourse if the trip falls through.','International cards, bank transfer or company invoice, USDT, cash (THB/USD) on site. A 30% deposit and a contract in English.'] ] },
  who:{ kicker:'Who it’s for', title:'Choose who you are — *see the trip that fits*' },
  segments:[
    { id:'family', label:'Families & beginners', title:'A first real fishing trip, without seasickness, crowds or tourist traps',
      quote:'“We want to fish with the kids, but we’re afraid we’ll end up on an old tour boat with forty tourists and a handline on a stick.”',
      points:['A private boat just for your family, 5 hours on the water','Calm water off Racha Yai, life jackets for kids','The captain rigs the tackle and helps you land the fish','Your catch cooked on board: sashimi and grill'], picks:['family-half','first-strike','bangkok-monsters'] },
    { id:'angler', label:'Experienced angler', title:'Popping and jigging for GT and tuna on the right marks, not where everyone else goes',
      quote:'“Tourist boats don’t do popping. I need a captain who knows the banks, the currents and the moon phases.”',
      points:['A fast speedboat: more time on the spot, less time in transit','Stella- and Saltiga-grade tackle, PE 6–10, stinger rigs','Shelf and FAD spots outside the national parks, with no risk of a fine','A plan built around the tide, moon and wind on your date'], picks:['pro-gt','bigame-day','khaosok-jungle'] },
    { id:'trophy', label:'Trophy hunter', title:'Sailfish, marlin, dogtooth tuna: an expedition built around one target',
      quote:'“I’m flying halfway around the world for one particular fish. I don’t need a boat ride, I need a real shot.”',
      points:['A sportfisher with a cockpit and a fighting chair','A night on the shelf: morning and evening bites right on the spot','A window chosen by season and forecast, rescheduling with no penalty','IGFA-standard catch & release, measurement and a certificate'], picks:['overnight-shelf','expedition-khaolak','stingray'] },
    { id:'corp', label:'Corporate', title:'A tournament on 3–5 boats, prizes, dinner and video, all under one contract',
      quote:'“I need to take twelve partners on a trip they’ll talk about all year. And I don’t want to think about any of it.”',
      points:['A fleet of 3–5 identical boats and a tournament judge','Trophies, award categories, a host, dinner at a villa','An event video within 48 hours','Paperwork, a company invoice, a contract'], picks:['tournament','bigame-day','signature-week'] },
    { id:'vip', label:'VIP', title:'One person handles everything: villa, yacht, chef, transfers',
      quote:'“I want a week of the best fishing in Asia without a single phone call or any waiting around.”',
      points:['A personal concierge 24/7 before and during the trip','The best boats on peak dates, booked a season ahead','A private chef, photo and drone, privacy','Helicopter, seaplane, family program on request'], picks:['signature-week','bigame-day','overnight-shelf'] }
  ],
  toursBlock:{ kicker:'Tours and prices', title:'From your first bite to a *marlin expedition*', lede:'Prices include the boat, tackle, transfers, meals, insurance and a licensed guide. No extra charges at the pier.',
    filters:[['all','All'],['sea','Sea'],['fresh','Freshwater'],['group','Groups'],['vip','VIP']] },
  concierge:{ kicker:'Concierge service', title:'You fish. *We handle the rest.*', lede:'One English-speaking person runs the whole trip, from choosing the date to the trophy.',
    items:[['boat','The right boat and captain for your target','We compare boats on speed, tackle and reviews, and book peak dates well ahead.'],['rod','Premium tackle','Stella, Saltiga, fresh braid. Or we’ll get your own gear ready.'],['car','Business-class transfers','Airport pickup, a car to the pier, a driver for every day of your stay.'],['home','A villa by the sea','Near Chalong or in Khao Lak, so you can sleep a little longer.'],['chef','A chef and a menu from your catch','Sashimi on board, dinner from your trophy at the villa.'],['cam','Photo, drone, film','A camera operator on board and an edited video within 48 hours.'],['shield','Insurance and paperwork','Vetted boats, a contract, a company invoice.'],['star','A program for the family','Spa, islands and nature while you’re out at sea.']],
    sigKicker:'Signature Week · 7 days', sigTitle:'A week of Thailand’s best fishing *without a single phone call*', sigPoints:['Big Game on a sportfisher and a night on the shelf','The Khao Sok jungle and Bangkok’s record-fish lakes','Villa, chef, driver, photos and film','A personal concierge 24/7 and the best boats in peak season'],
    fee:'A concierge can be added to any tour, from 15,000 THB per day. A club card for those who winter in Thailand: five trips per season at 15% off, with priority on dates.', sigCta:'See the week’s program' },
  mapPage:{ link:'Fishing map of all Thailand →', crumb:'Map', metaTitle:'Where to fish in Thailand: map of spots and no-fishing zones | ERKAK', metaDesc:'Fishing map of Thailand: the Andaman Sea, the Gulf of Thailand, Bangkok and Khao Sok. Where fishing is legal, which national parks carry fines and which trip goes where.',
    title:'Where you can fish *in Thailand*', lede:'Four areas where we fish, and the zones where fishing is banned by law. Tap an area or a spot.',
    regions:{ andaman:['Andaman Sea', 'Phuket and Khao Lak: sailfish, marlin, GT and tuna. Season: November–April.'], gulf:['Gulf of Thailand', 'Pattaya and Samui: barracuda, grouper and mackerel. Fishable in the monsoon too.'], bangkok:['Bangkok', 'Freshwater: Mekong catfish, carp and stingray over 100 kg. All year.'], khaosok:['Khao Sok', 'Cheow Lan Lake in the jungle: snakehead, hampala and mahseer.'] },
    tourCta:'Trip here: {tour}', rulesTitle:'Rules that *protect you*', allTours:'All trips and prices',
    rules:['Fishing is banned in marine national parks: the Similans, Surin, Phi Phi, Ang Thong, Mu Ko Lanta. Fines reach 500,000 THB.', 'We only go out with a licensed operator: the boat holds a Marine Department permit and a Thai guide is on board.', 'On freshwater we fish in fishing parks and with local guides. Big fish are released.', 'Andaman: November–April. In the monsoon (May–October) we fish the Gulf of Thailand and freshwater.'] },
  map:{ kicker:'Where we fish — and where we never do', title:'An honest map of the *Andaman*', lede:'Fishing in marine national parks is prohibited by law. We fish the shelf, the FADs and the Racha islands, and enter the parks only to moor and snorkel. Select a spot for details.' },
  spots:{
    'racha-yai':{ name:'Racha Yai', run:'30–45 minutes from Chalong', fish:'Barracuda, mackerel, snapper, grouper', how:'Trolling, bottom fishing, light jigging', note:'Not part of any national park. The main spot for families and groups.' },
    'racha-noi':{ name:'Racha Noi', run:'about an hour from Chalong', fish:'GT, yellowfin tuna, wahoo, amberjack, grouper', how:'Popping, vertical jigging, trolling', note:'Deeper and farther out, with a seamount to the south. The Pro Day spot.' },
    'shelf':{ name:'Shelf and FADs', run:'1.5–2.5 hours', fish:'Sailfish, marlin, wahoo, mahi-mahi, tuna', how:'Trolling, popping around FADs', note:'The shelf drop-off and fish aggregating devices. This is where you go for sailfish.' },
    'khaolak-fad':{ name:'Khao Lak FADs', run:'from 6 km off Tap Lamu', fish:'Mahi-mahi, wahoo, GT, mackerel, sailfish', how:'Popping, jigging at 60–80 m, fly fishing', note:'We fish strictly short of the Similan National Park boundary.' },
    'phangnga':{ name:'Phang Nga Bay', run:'from Bang Rong', fish:'Barracuda, trevally, grouper, snapper', how:'Casting, bottom fishing', note:'Sheltered water: the backup plan in monsoon season, outside the national park boundary.' },
    'similan':{ name:'Similan Islands', run:'65–70 km from Tap Lamu', fish:'—', how:'Mooring and snorkeling only', note:'National park: fishing is banned year-round, including Koh Bon and Koh Tachai. Closed May 16 – October 15.' },
    'surin':{ name:'Surin and Richelieu Rock', run:'—', fish:'—', how:'—', note:'National park: fishing is banned. Closed from mid-May to mid-October.' },
    'phiphi':{ name:'Phi Phi', run:'—', fish:'—', how:'—', note:'Hat Noppharat Thara – Mu Ko Phi Phi National Park: fishing is banned, including Bamboo Island and the “4 Islands”.' },
    'shark':{ name:'Shark Point', run:'—', fish:'—', how:'—', note:'A marine sanctuary since 1992: fishing and anchoring are prohibited.' },
    'lanta':{ name:'Koh Rok · Hin Daeng', run:'—', fish:'—', how:'—', note:'Mu Ko Lanta National Park. We treat it as a no-fishing zone.' },
    'khaosok':{ name:'Khao Sok · Cheow Lan', run:'2.5 hours by road', fish:'Snakehead, hampala barb, mahseer', how:'Spinning, fly fishing from a longtail', note:'Fishing is allowed only from local longtail boats.' },
    'pattaya':{ name:'Pattaya islands: Ko Larn, Ko Sak', run:'30–60 min from Pattaya', fish:'Barracuda, grouper, snapper, mackerel', how:'Trolling, bottom fishing, jigging', note:'We fish in permitted areas, outside the Sattahip naval zones.' },
    'samui-south':{ name:'South Samui: Ko Tan, Ko Madsum', run:'30–45 min from south Samui', fish:'Barracuda, mackerel, trevally, grouper', how:'Trolling, jigging, bottom fishing', note:'Outside the Ang Thong marine park boundary.' },
    'angthong':{ name:'Ang Thong', run:'—', fish:'—', how:'—', note:'Mu Ko Ang Thong Marine National Park: fishing is banned. We only stop there to anchor and snorkel.' },
    'bungsamran':{ name:'Bungsamran, Bangkok', run:'40–60 min from central Bangkok', fish:'Mekong giant catfish, Siamese carp, arapaima', how:'Bottom fishing, feeder', note:'A paid fishing park; all fish are released.' },
    'maeklong':{ name:'Mae Klong River', run:'about 1.5 h from Bangkok', fish:'Giant freshwater stingray', how:'Bottom fishing from a boat, heavy tackle', note:'Catch and release only, with a licensed guide.' }
  },
  season:{ sailfish:['Sailfish','trolling'], marlin:['Black marlin','big game'], gt:['GT (giant trevally)','popping'], yellowfin:['Yellowfin tuna','popping, jigging'], wahoo:['Wahoo and mahi-mahi','trolling'], mackerel:['King mackerel','trolling'], reef:['Grouper, snapper, barracuda','reef'], fresh:['Freshwater','lakes and rivers'] },
  sea:['Calm sea','Andaman'], levels:['none or rare','possible','good','peak'],
  cal:{ kicker:'Bite calendar', title:'When to go *for your fish*', lede:'Andaman Sea: the calm season runs from November to April, the monsoon from May to October. The outlined column marks the current month.',
    notes:[['May–October: monsoon','Waves of 2–3 meters, and offshore trips are often canceled. Sheltered Phang Nga Bay, freshwater and good-weather windows still work, and we track the forecast for you.'],['Sailfish timing varies by year','Captains see peaks in both January–March and June–November. Give us your dates and we’ll tell you what’s biting right now, based on fresh reports.']] },
  guar:{ kicker:'Guarantees', title:'The risk is *on us*', items:[['100%','Refund if weather cancels your trip','Or free rescheduling. The captain and the forecast make the call.'],['7 days','Free cancellation','After that, you can move the date within the season at no extra cost.'],['0 THB','Extra charges at the pier','Everything included is listed in your confirmation.'],['48 h','Photos and video of your day','Or 20% off your next trip.']] },
  quiz:{ kicker:'Your match in 60 seconds', title:'Let’s plan your *perfect trip*', lede:'Five questions, and the concierge sends you an option with the boat, spot, forecast and price.',
    q1:'Who’s coming?', h1:'Choose one option', q2:'Your fishing experience?', h2:'We’ll match the tackle and format', q3:'What matters most to you?', h3:'Your goal decides the boat and the spot', q4:'Where will you be?', h4:'Not decided yet? We’ll advise', q5:'Fishing budget', h5:'So we don’t suggest more than you need', q6:'Where should we send the plan and price?', result:'Your best match',
    who:[['solo','Just me','or with a friend'],['couple','A couple','the two of us'],['family','Family with kids','kids aged 5+'],['friends','Group of 4–8','friends, a guys’ trip'],['corp','Corporate 8+','team, partners'],['vip','VIP trip','a concierge for everything']],
    exp:[['zero','Never fished','want to try'],['casual','Fish now and then','at home and on vacation'],['pro','Experienced lure angler','popping, jigging'],['trophy','Trophy hunter','big game, expeditions']],
    goal:[['fun','Downtime and dinner from the catch','no pressure'],['gt','Trophy: GT and tuna','popping, jigging'],['billfish','Sailfish or marlin','big game'],['fresh','Freshwater giants','catfish, carp, stingray'],['event','A team event','tournament and prizes'],['all','All of it','a week with a concierge']],
    where:[['phuket','Phuket','Chalong, Rawai'],['khaolak','Khao Lak or Krabi','north and east'],['bkk','Bangkok or Pattaya','freshwater and the Gulf'],['any','Not decided yet','please advise']],
    budget:[['b1','Up to 10,000 THB per person','group trip'],['b2','20,000–40,000 THB','private boat for a day'],['b3','50,000–200,000 THB','sportfisher, overnight'],['b4','Budget isn’t the point','I want the best result']] },
  faqTitle:'Answers *before you ask*',
  faq:[
    ['Is this legal? I’ve heard about arrests for fishing.','Yes, and it’s our core principle. Tours are run by a licensed operator, with a licensed Thai guide on board and boats holding Marine Department permits. We don’t fish in marine national parks (Similan, Surin, Phi Phi, Koh Rok, Hin Daeng) or marine sanctuaries: fishing there is prohibited by law.'],
    ['How do I pay?','A 30% deposit secures your booking. We accept international cards, bank transfer or company invoice, USDT, and cash in THB or USD on site. The balance is paid on the day of the trip. Invoice and confirmation in English.'],
    ['What if there’s a storm?','The captain decides whether to go out based on the Thai Meteorological Department forecast. If a trip is canceled because of weather, you get free rescheduling or a full refund of your deposit. In monsoon season we suggest sheltered spots or freshwater in advance.'],
    ['I get seasick. Will this work for me?','Choose November to April, a private half-day trip and a boat with a wide hull. We’ll plan a route with short runs. For the most sensitive, there are freshwater lakes, where there is no swell at all.'],
    ['Do I need experience or my own tackle?','No. The captain and deckhand will set everything up and show you how. For Pro Day and expeditions we provide Shimano Stella and Daiwa Saltiga-grade tackle. You’re welcome to bring your own; we’ll tell you what will be useful in your season.'],
    ['Can I keep my catch?','Edible fish, yes: the cook will turn it into sashimi and grilled fish right on board. Sailfish, marlin and large GT are released under catch & release rules: we measure, photograph and give you a certificate.'],
    ['Can I bring children?','Yes, from age 5, on Family Day and First Strike. Kids’ life jackets, light rods, shade and a toilet on board. Sportfisher trips from age 10.'],
    ['Do I need a visa?','Since September 15, 2026, most nationalities, including EU, UK, US and GCC citizens, can enter Thailand visa-free for 30 days. It depends on your passport: we’ll check yours and help with documents, including a DTV for longer stays. Details are in our visa guide.']
  ],
  legalNote:'We don’t fish in marine national parks or sanctuaries: Similan, Surin, Phi Phi, Koh Rok, Hin Daeng, Shark Point. That’s Thai law, and it protects you.',
  tours:{
    'first-strike':{ title:'First Strike', where:'Phuket · Racha Yai', kind:'Group trip',
      short:'A small group of up to six anglers on a comfortable boat. Trolling and bottom fishing around the Racha islands.',
      pitch:'The easiest way to try sea fishing in the Andaman. Not 15–40 people, as on mass-market tours, but six anglers at most, on a boat with a toilet and shade.',
      species:['Barracuda','Mackerel','Snapper','Grouper'],
      day:[['07:30','Transfer from your Phuket hotel'],['08:30','Departure from Chalong and briefing'],['09:15','Trolling on the way to Racha Yai'],['10:30','Bottom fishing and jigging on the reefs'],['12:30','Lunch on board: grilled catch, fruit'],['14:00','Afternoon session, snorkeling if you like'],['16:00','Return and transfer to your hotel']],
      incl:['Transfers from Phuket hotels','Tackle and bait','Lunch, water, fruit','Passenger insurance','Licensed guide on board','Photos of your catch sent to the chat'],
      excl:['Alcohol','A private boat: see Family Day'],
      upsell:[['Private boat','The whole boat to yourselves: Family Day'],['Drone video','+4,500 THB per trip'],['Kids’ kit','Free: life jacket and a light rod']] },
    'family-half':{ title:'Family Day', where:'Phuket · Racha Yai', kind:'Private boat',
      short:'A boat just for your family. Five hours on calm water, with a captain who helps kids and beginners.',
      pitch:'For those who want a day of fishing, not an ordeal. We head out in the morning while the sea is calm, fish around Racha Yai, have the catch for lunch and are back before the heat.',
      species:['Barracuda','Mahi-mahi','Snapper','Trevally'],
      day:[['08:00','Hotel transfer'],['08:45','Departure and safety briefing'],['09:15','Trolling: the first bites'],['10:30','Reef fishing, with help for the kids'],['12:00','Sashimi and grilled catch'],['13:30','Back in Chalong']],
      incl:['Private boat with captain and deckhand','Round-trip transfer','Tackle for adults and kids','Lunch from the catch and drinks','Kids’ life jackets','Insurance and a licensed guide'],
      excl:['Alcohol','Photographer, on request'],
      upsell:[['Photographer on board','+6,000 THB, 100+ shots'],['Full day','+12,000 THB, with a beach stop'],['Cake and decorations','For a birthday on board']] },
    'pro-gt':{ title:'Pro Day: GT and Jigging', where:'Phuket · Racha Noi · shelf', kind:'Speedboat · up to 4 anglers',
      short:'Popping for giant trevally and vertical jigging on the Racha Noi banks. For anglers who know what they’re doing and want a trophy.',
      pitch:'A fast speedboat, a captain who specializes in popping, and tackle that will hold a 30+ kg GT. We choose spots for the tide and moon on your date, outside national park boundaries.',
      species:['GT (giant trevally)','Yellowfin tuna','Dogtooth tuna','Amberjack','Grouper'],
      day:[['06:00','Transfer and coffee on board'],['06:45','Run out at 30 knots'],['07:30','Morning popping on the Racha Noi reefs'],['10:00','Vertical jigging at 60–120 m'],['12:30','Lunch and a move to follow the current'],['14:00','Afternoon popping on the tide'],['16:30','Return and debrief']],
      incl:['Speedboat with a specialist captain','Shimano Stella / Daiwa Saltiga tackle, PE 6–10','Poppers, stickbaits, 150–400 g jigs','Lunch, water, energy drinks','Licensed guide and insurance','Action-cam photos and video'],
      excl:['Lost lures beyond three, charged at cost'],
      upsell:[['Drone operator','+9,000 THB, video within 48 hours'],['Second day','15% off when you book two days'],['Your own tackle','3,000 THB off']] },
    'bigame-day':{ title:'Big Game on a Sportfisher', where:'Phuket · shelf and FADs', kind:'44–50 ft sportfisher',
      short:'Trolling for sailfish and marlin from the cockpit of a real sportfisher. Fighting chair, outriggers, a chef on board.',
      pitch:'The main format for a trophy. An air-conditioned 44–50 ft sportfisher with a fighting chair and a crew that knows where on the shelf the sailfish are holding this month.',
      species:['Sailfish','Black marlin','Wahoo','Mahi-mahi','Tuna'],
      day:[['06:30','Transfer by business-class car'],['07:00','Departure and breakfast from the chef'],['08:00','Trolling the shelf and FADs'],['12:30','Lunch: sashimi from the catch and a hot dish'],['13:30','Afternoon trolling session'],['17:00','Return, and champagne for the first sailfish']],
      incl:['Sportfisher with crew','Chef and all meals on board','Big-game tackle and fighting chair','Business-class transfer','Licensed guide and insurance','Photos and a short video of the day'],
      excl:['Premium alcohol, from the menu','National park fees when mooring inside a park'],
      upsell:[['Overnight on the shelf','Extend to Night on the Shelf'],['Drone filming','+9,000 THB'],['Trophy replica','A full-size replica of your fish, made from photos and measurements']] },
    'overnight-shelf':{ title:'Night on the Shelf', where:'Andaman Sea · 2 days / 1 night', kind:'Overnight sportfisher',
      short:'Two morning bites and one evening bite, right on the spot. Night squid fishing, dinner under the stars, sunrise on the shelf.',
      pitch:'The most productive format: instead of spending three hours a day in transit, you are already on the spot for the best bite at dawn and dusk.',
      species:['Sailfish','Marlin','Yellowfin tuna','Wahoo','Squid'],
      day:[['Day 1 · 07:00','Departure and trolling the shelf'],['Day 1 · 18:00','Dinner from the chef and night squid fishing'],['Day 2 · 05:30','The dawn bite, your best chance at a sailfish'],['Day 2 · 12:00','Lunch and a final session'],['Day 2 · 17:00','Back in Chalong']],
      incl:['Sportfisher with cabins and a shower','Chef and five meals','All tackle and bait','Transfers','Licensed guide and insurance','Photos and video of the trip'],
      excl:['Premium alcohol','Fuel for runs beyond 60 miles'],
      upsell:[['3 days / 2 nights','+85,000 THB'],['Drone operator','A film of your trip'],['Villa after the trip','Booked by the concierge']] },
    'expedition-khaolak':{ title:'Khao Lak Expedition', where:'Khao Lak · FADs and shelf · 4 days', kind:'Liveaboard · per angler',
      short:'Four days on board: popping and jigging the FAD fields between Khao Lak and the Similans, strictly outside the park boundary.',
      pitch:'An expedition for anglers who want as many casts a day as possible. The FAD fields start 6 km from Tap Lamu and stretch toward the Similans. We fish the shelf and spend the nights at anchor; inside the park we only rest, because fishing there is prohibited.',
      species:['GT','Yellowfin tuna','Mahi-mahi','Wahoo','King mackerel'],
      day:[['Day 1','Transfer from Phuket, departure from Tap Lamu, first FADs'],['Day 2','Dawn popping, daytime jigging at 60–80 m'],['Day 3','Offshore FADs and trolling for sailfish'],['Day 4','Morning session, return and transfer']],
      incl:['Liveaboard with cabins','Full board','Premium tackle','Phuket – Tap Lamu transfer','Licensed guide and insurance','Photos and video of the expedition'],
      excl:['National park mooring fee (500 THB per day)','Alcohol','Crew tips'],
      upsell:[['Private charter','The whole boat for your group'],['Extension to 6 days','On request'],['Mergui (Myanmar)','Expedition on request when the border is open']] },
    'gulf-private':{ title:'Gulf of Thailand: Pattaya and Samui', where:'Pattaya · Koh Khram · Samui', kind:'Private speedboat',
      short:'For those who live or vacation on the Gulf. A short run to the islands for barracuda, cobia and king mackerel.',
      pitch:'Pattaya’s best season is October to March, Samui’s is January to May. We head out to Koh Khram, Koh Phai and Samae San, or to the reefs of northern Samui, outside Ang Thong National Park, where fishing is not allowed.',
      species:['Barracuda','Cobia','King mackerel','Grouper','Queenfish'],
      day:[['07:00','Transfer from your hotel or condo'],['07:45','Departure by speedboat'],['08:30','Trolling toward the islands'],['10:30','Jigging and live bait on the reefs'],['12:30','Lunch on board and a swim'],['14:30','Return']],
      incl:['Private speedboat with captain','Transfer','Tackle and bait','Lunch and drinks','Licensed guide and insurance','Photos of your catch'],
      excl:['Alcohol','Night squid fishing, on request'],
      upsell:[['Night squid','An evening trip with dinner'],['Arapaima lake','A second day on freshwater'],['A yacht instead of a speedboat','For groups of up to 12 guests']] },
    'bangkok-monsters':{ title:'Bangkok Monsters', where:'Bangkok · New Bungsamran', kind:'Freshwater · day',
      short:'Giant Mekong catfish and Siamese carp of 30–100 kg at the country’s best lake. Transfer from your Bangkok hotel.',
      pitch:'Ideal for a Bangkok stopover and for the rainy season, when the sea is rough. A lake with fish up to 100 kg, an air-conditioned fishing pavilion and a guide who sets up the tackle and groundbait.',
      species:['Mekong catfish','Siamese carp','Arapaima'],
      day:[['06:00','Transfer from your Bangkok hotel (about an hour)'],['07:30','Pavilion, tackle, groundbait'],['08:00','Fishing, with the guide on hand all day'],['13:00','Lunch at the lake restaurant'],['19:30','Trophy photos and return']],
      incl:['Transfers from Bangkok hotels','Session ticket','Tackle and groundbait','Guide at the lake','Air-conditioned pavilion','Trophy photos'],
      excl:['Meals at the lake','Night session, on request'],
      upsell:[['Night session','Big catfish after dark'],['Giant stingray','A second day on the Mae Klong River'],['Riverside hotel','Booked by the concierge']] },
    'stingray':{ title:'Giant Stingray', where:'Mae Klong River · Samut Songkhram', kind:'Freshwater · day',
      short:'Hunting a 100+ kg freshwater stingray from a boat on the Mae Klong River. Catch & release.',
      pitch:'One of the largest freshwater species on the planet. In 2015, a stingray about four meters long was caught and released on the Mae Klong. This is fishing that takes patience, for one chance you will remember for the rest of your life.',
      species:['Giant freshwater stingray','Catfish'],
      day:[['05:30','Transfer from Bangkok (about 1.5 hours)'],['07:30','Boat on the river and heavy tackle'],['08:00','Live-bait fishing and waiting for the bite'],['13:00','Lunch on the river'],['17:30','Return to Bangkok']],
      incl:['Transfer','Boat and local guide','Heavy tackle, 80–130 lb','Bait','Lunch','Photos and measurement of your trophy'],
      excl:['A guaranteed bite: these are wild fish'],
      upsell:[['Second day','Doubles your chances'],['Bangkok Monsters','A two-day combo'],['Video','A camera operator on the boat']] },
    'khaosok-jungle':{ title:'Jungle Fishing in Khao Sok', where:'Cheow Lan Lake · 2 days', kind:'Floating raft house · per angler',
      short:'Snakehead and hampala among karst cliffs. A night in a floating raft house on the lake and a dawn bite.',
      pitch:'The most beautiful fishing in Thailand. We fish from local longtails (no other boats are allowed on the lake) with spinning and fly tackle, and stay in a floating raft house in the middle of the national park.',
      species:['Giant snakehead','Hampala barb','Mahseer','Catfish'],
      day:[['Day 1 · 07:00','Transfer from Phuket or Khao Lak (about 2.5 hours)'],['Day 1 · 11:00','Longtail and first casts for snakehead'],['Day 1 · 17:00','Evening bite and dinner at the raft house'],['Day 2 · 06:00','Dawn fishing'],['Day 2 · 12:00','Lunch and transfer back']],
      incl:['Transfers','Floating raft house with meals','Longtail with a local guide','National park fees','Light tackle','Photos'],
      excl:['Fly tackle: best to bring your own','Alcohol'],
      upsell:[['Third day','Remote bays'],['Jungle safari','For the family'],['Private raft house','The whole house to yourselves']] },
    'tournament':{ title:'Corporate Tournament', where:'Phuket · 3–5 boats · 2 days', kind:'Group of 8–30 guests',
      short:'A tournament on identical boats with a judge, award categories and trophies. An awards dinner at a villa and a film within 48 hours.',
      pitch:'An event your team will remember for the fight for the cup, not for waiting on the bus. Fleet, judging, prizes, dinner, filming and paperwork are all on us.',
      species:['Sailfish','Tuna','Barracuda','Trevally'],
      day:[['Day 1 · morning','Briefing and boat assignments'],['Day 1 · daytime','Tournament round one'],['Day 1 · evening','Dinner at the villa and interim results'],['Day 2 · daytime','Final round'],['Day 2 · evening','Ceremony, trophies and a teaser film']],
      incl:['3–5 boats with crews','Judge, rules and score sheets','Trophies and award categories','Awards dinner and a host','Photos, drone and a video within 48 hours','Contract and company invoice'],
      excl:['Accommodation: we’ll find it for you','Flights'],
      upsell:[['Branding','T-shirts, flags and trophies with your logo'],['Group villa','For the whole trip'],['Partners’ program','Spa, yacht, shopping']] },
    'signature-week':{ title:'Signature Week', where:'Phuket · Khao Lak · Bangkok', kind:'Concierge · 7 days',
      short:'A fully arranged week of Thailand’s best fishing: villa, sportfisher, freshwater giants, chef, filming and a personal concierge.',
      pitch:'For those who value their time. We build the program around your goals: three days at sea, a night on the shelf, a day in the jungle and a record-fish lake. You stay at a villa, and the concierge handles everything else.',
      species:['Sailfish','Marlin','GT','Mekong catfish','Snakehead'],
      day:[['Day 1','Airport pickup, villa, dinner from the chef'],['Days 2–3','Big Game on a sportfisher'],['Day 4','Night on the shelf'],['Day 5','Khao Sok jungle'],['Day 6','Rest, spa, family time, as you like'],['Day 7','Bangkok Monsters or departure']],
      incl:['Personal concierge 24/7','Villa with a pool','All trips and boats','Private chef','Photos, drone and a film of the trip','All transfers and VIP airport meet-and-greet'],
      excl:['Flights','Personal requests outside the program, quoted separately'],
      upsell:[['Seaplane','Flights between locations'],['Family program','For those who don’t fish'],['Trophy replica','For your office']] }
  }
};
