// ERKAK · Deutsch · Bereiche, Programme, Reiseziele. Fakten und Preise nach der Marktanalyse vom September 2026.
export const directions = {
  fishing:{ name:'Angeln & Trophäen', short:'Segelfisch, Marlin, GT und Süßwasser-Giganten. Legal und mit lizenziertem Guide.',
    who:'Für Familien, erfahrene Angler, Trophäenjäger und Freundesgruppen, die richtig angeln wollen – statt nur einen Ausflug zu machen.',
    intro:'Trophäenangeln in der Andamanensee und die Süßwasser-Giganten Bangkoks – der erste Bereich von ERKAK, der bereits buchbar ist. Private Boote, Gerät auf Stella-Niveau, ein lizenzierter Guide und eine ehrliche Karte: In Meeresnationalparks angeln wir nie.',
    incl:['Boot und Kapitän','Gerät und Köder','Transfer','Verpflegung an Bord','Versicherung und lizenzierter Guide'] },
  muaythai:{ name:'Muay Thai & Kampfsport', short:'Camps auf Phuket und in Bangkok, BJJ, Boxen, MMA. Vom ersten Training bis zum ersten Kampf.',
    who:'Für Männer, die im Ring in Form kommen wollen – nicht auf dem Laufband.',
    intro:'Phuket und Bangkok sind die Welthauptstädte des Muay Thai: Tausende Gyms, Camps mit Unterkunft und Kämpfe fast jeden Abend. Wir wählen das Camp nach Niveau und Ziel, bringen Sie in der Nähe des Gyms unter und begleiten Sie vom ersten Training bis zur Auswertung.',
    incl:['Training in einem geprüften Camp','Unterkunft nahe dem Gym','Flughafentransfer','Ausrüstung für den Start','Concierge auf Englisch'],
    note:'Seit dem 15. September 2026 können Staatsangehörige Deutschlands, Österreichs und der Schweiz 30 Tage ohne Visum in Thailand bleiben. Für längere Programme helfen wir beim Visum, auch beim DTV für längere Trainingsaufenthalte.' },
  camps:{ name:'Trainingscamps', short:'Hyrox, Fettabbau, Trailrunning, Triathlon, Marathon, Radcamps – mit Trainer und Plan.',
    who:'Für alle, die in 1–3 Wochen Ergebnisse sehen wollen – mit einer Disziplin, die zu Hause fehlt.',
    intro:'Ein Trainingscamp ist der schnellste Weg, die eigene Form voranzubringen: Trainer, fester Tagesablauf, passende Ernährung und ein Klima, in dem man gern trainiert. Vom Hyrox-Camp auf Phuket bis zum Höhentraining im kenianischen Iten.',
    incl:['Programm eines spezialisierten Trainers','Messungen zu Beginn und am Ende','Ernährung passend zur Belastung','Unterkunft','Regeneration: Massage, Sauna'] },
  longevity:{ name:'Check-up & Longevity', short:'Executive Check-ups, Männergesundheit, Herz, Schlaf, DNA – in akkreditierten Kliniken.',
    who:'Für Männer ab 35, die ihre Werte kennen wollen, statt zu raten.',
    intro:'Bangkok ist eines der wichtigsten Zentren des Medizintourismus: JCI-akkreditierte Krankenhäuser, offen ausgewiesene Paketpreise und Untersuchungen an einem Tag. Wir wählen Klinik und Paket aus, begleiten Sie auf Englisch und gehen die Befunde mit Ihnen durch. ERKAK ist ein Concierge, keine medizinische Einrichtung: Entscheidungen trifft der Arzt.',
    incl:['Auswahl von Klinik und Paket','Terminbuchung und Begleitung auf Englisch','Befunde auf Englisch erklärt','Transfers und Hotel','Plan für die nächsten Schritte'],
    note:'Die Paketpreise veröffentlichen die Krankenhäuser selbst; Aktionspreise gelten manchmal nur für Einwohner Thailands – wir lassen uns den Preis für ausländische Patienten schriftlich bestätigen.' },
  detox:{ name:'Detox & Neustart', short:'Detox-Retreats, Gewichts-Reset, Retreats ohne Alkohol, ärztlich begleitetes Fasten, Ayurveda.',
    who:'Für alle, die erschöpft sind, zugenommen haben und neu anfangen wollen.',
    intro:'Ein Neustart bedeutet einen neuen Tagesrhythmus, keine „Entgiftung“. Retreats auf Koh Samui und Bali, Programme zur Gewichtsreduktion auf Phuket, ärztlich begleitetes Fasten in Europa und Ayurveda in Kerala. Vorab gibt es einen Gesundheitsfragebogen: Nicht jedes Format passt für jeden.',
    incl:['Retreat-Programm','Unterkunft und Verpflegung nach Protokoll','Beratung durch Fachleute','Transfers','30 Tage Begleitung danach'] },
  recovery:{ name:'Regeneration', short:'Sauna und Eis, Thai-Massage, Physiotherapie, Onsen, Banja, Totes Meer.',
    who:'Für alle, denen der Rücken wehtut, die ständig müde sind und deren Schlaf aus dem Takt geraten ist.',
    intro:'Regeneration ist das halbe Training und der beste Weg, nach einem harten Jahr wieder Energie zu tanken. Kontrasttherapie auf Phuket, Massage der alten Schule in Chiang Mai, japanische Onsen, russische Banja und das Tote Meer.',
    incl:['Anwendungsreihe','Geprüfte Studios und Spas','Zeitplan nach Ihrem Rhythmus','Transfers','Concierge auf Englisch'] },
  mind:{ name:'Geist & Ruhe', short:'Schweige-Retreats, Atem und Kälte, Männerkreise, Kloster, Coaching, Psychologe.',
    who:'Für Männer, die alles haben – außer Ruhe im Kopf.',
    intro:'Stille und Klarheit sind die knappste Ressource. Meditationszentren in Nordthailand, Atemarbeit auf Bali, Männer-Retreats im Altai, Coaching und psychologische Begleitung online. Wo eine Tradition kostenlos ist, verkaufen wir nur die Logistik.',
    incl:['Leitung oder Mentor','Unterkunft in Stille','Verpflegung','Transfers','Integrationsgespräch danach'] },
  adventure:{ name:'Abenteuer', short:'Elbrus, Kilimandscharo, Everest, Kamtschatka, Motorradtouren, Safari, die Felsen von Railay.',
    who:'Für alle, die etwas erleben wollen, wovon sie noch den Enkeln erzählen.',
    intro:'Gipfel, Trekkings und Routen, nach denen die eigenen Aufgaben in einem anderen Maßstab erscheinen. Wir arbeiten mit lizenzierten lokalen Veranstaltern, planen Reservetage und eine Versicherung für große Höhen ein – und sprechen offen über die Risiken.',
    incl:['Guides und Genehmigungen','Ausrüstung nach Liste','Unterkunft entlang der Route','Versicherung für Aktivreisen','Fotos und Video'] },
  ocean:{ name:'Ozean', short:'Tauchen, Freediving, Surfen, Kitesurfen, Segelkurse und Yachtwochen.',
    who:'Für alle, die es ans Wasser zieht und die es selbst können wollen, statt nur zuzusehen.',
    intro:'Vom ersten Tauchgang vor den Racha-Inseln bis zur Tauchsafari zu den Similan-Inseln und zum Surfen auf Bali. Zertifizierte Instruktoren, international anerkannte Zertifikate und Reisezeiten, abgestimmt auf Wind und Welle.',
    incl:['Instruktor und Zertifizierung','Ausrüstung','Boot oder Spot','Unterkunft in der Nähe','Unterwasserfotos'] },
  golf:{ name:'Golf & Padel', short:'Golfwochen auf Phuket und in Schottland, Padel in Dubai, Tennisakademien.',
    who:'Für alle, die das Spiel, gute Gesellschaft und schöne Plätze lieben.',
    intro:'Fünf Plätze auf Phuket in einer Woche, Golf für Einsteiger in Hua Hin, die Links von St Andrews und Padel in Dubai, wo der Sport am schnellsten wächst. Startzeiten, Pro und Transfers mit Ausrüstung übernehmen wir.',
    incl:['Startzeiten und Courts','Trainer oder Pro','Transfers mit Ausrüstung','Unterkunft','Turnier in der Gruppe'] },
  aesthetics:{ name:'Ästhetik & Stil', short:'Haartransplantation, Zahnmedizin, Augenlasern, Hautpflege, Stil.',
    who:'Für Männer, die in ihrem Alter so gut wie möglich aussehen wollen.',
    intro:'Istanbul, Bangkok und Seoul sind Weltzentren der ästhetischen Medizin – mit vielen ausgezeichneten Kliniken, aber auch mit „Fließbandbetrieben“. Wir wählen akkreditierte Kliniken aus, prüfen, wer den Eingriff tatsächlich durchführt, und begleiten Sie auf Englisch.',
    incl:['Auswahl einer akkreditierten Klinik','Beratung vor der Reise','Begleitung auf Englisch','Hotel und Transfers','Nachkontrolle'],
    note:'ERKAK ist keine medizinische Einrichtung: Indikation und Entscheidung liegen beim Arzt. Eine normale Reiseversicherung deckt geplante Eingriffe nicht ab.' },
  nutrition:{ name:'Ernährung & ERKAK-Supplements', short:'Ernährungsberatung nach Laborwerten, das ERKAK-Supplement-Protokoll, Privatkoch und Ernährung nach Plan.',
    who:'Für alle, die Ernährung und Supplements an ihren Laborwerten ausrichten wollen.',
    intro:'Ernährung ist die Grundlage jedes Programms. Auswertung der Laborwerte mit einer zugelassenen Fachkraft, das ERKAK-Supplement-Protokoll mit Analysezertifikat für jede Charge, ein Privatkoch während der Reise und eine Tour zu den Ursprüngen des Shilajit (Mumijo) in die Berge Usbekistans.',
    incl:['Auswertung der Laborwerte','Persönlicher Plan','Supplements mit Chargenzertifikat','Begleitung per Messenger','Kontrolltermin nach 90 Tagen'] },
  family:{ name:'Vater & Sohn', short:'Reisen, nach denen Vater und Sohn eine gemeinsame Geschichte haben.',
    who:'Für Väter, die ihrem Sohn statt eines Geschenks gemeinsame Zeit schenken wollen.',
    intro:'Ring und Ozean auf Phuket, der Himalaya, Felsen und Inseln in Krabi. Programme passend zum Alter des Kindes, mit geprüften Instruktoren und Sicherheit an erster Stelle.',
    incl:['Programm passend zum Alter des Kindes','Instruktoren und Guides','Unterkunft','Transfers','Fotos und ein Film über die Reise'] },
  business:{ name:'Firmen & Freunde', short:'Retreats für Führungsteams, Regatten, Gründer-Retreats, Premium-Junggesellenabschiede.',
    who:'Für Teams und Freundeskreise, die ein gemeinsames Erlebnis suchen.',
    intro:'Gemeinsame Erlebnisse verbinden stärker als jedes Teambuilding. Strategie-Retreats auf Phuket und Bali, Firmenregatten und Männerreisen ohne Klischees – mit Unterlagen und Rechnung für Ihr Unternehmen.',
    incl:['Programm nach Zielsetzung','Locations und Unterkunft','Moderation und Facilitator','Unterlagen und Rechnung für das Unternehmen','Film über das Event'] }
};

export const programs = {
  // ── Muay Thai & Kampfsport ──────────────────────────────────────
  'mt-phuket-week':{ title:'Muay-Thai-Woche auf Phuket', where:'Phuket, Soi Ta-iad',
    short:'Zwei Trainings am Tag in einem Camp an der bekanntesten Muay-Thai-Straße der Welt. Unterkunft mit Pool, fünf Minuten vom Gym.',
    about:'Die Soi Ta-iad in Chalong ist die Straße, an der Tiger Muay Thai, Phuket Top Team und AKA direkt nebeneinander liegen. Wir wählen das Camp nach Ihrem Niveau: Gruppenklassen für Einsteiger, Sparring für alle, die schon boxen, oder einen Kraftblock, wenn es um die Form geht. Sie wohnen in einem Hotel mit Pool nahe dem Gym; Transfer und erstes Training begleiten wir auf Englisch.',
    plan:['Transfer, Check-in, Kennenlernen des Trainers und Einführungstraining','Morgens Techniktraining, abends Pratzen und Sandsack, Sparring nach Wunsch','Massage und Regeneration zur Wochenmitte','Abschlusstraining, Videoanalyse und Plan für zu Hause'],
    tip:'Die Camps sind ganzjährig geöffnet; in der Regenzeit (Mai–Oktober) ist die Unterkunft günstiger. Eine Woche passt problemlos in die 30 Tage visumfreie Einreise.' },
  'mt-month':{ title:'Vier Wochen Transformation: Muay Thai und Ernährung', where:'Phuket',
    short:'Das beliebteste Format nach dem Motto „abreisen und verändert zurückkommen“: zwei Trainings am Tag, Ernährungsberater und wöchentliche Messungen.',
    about:'Vier Wochen im Muay-Thai-Camp mit einem klaren Ziel: überflüssige Kilos abbauen, Ausdauer und Technik aufbauen. Ein Ernährungsberater berechnet die Kost passend zur Belastung, die Mahlzeiten werden fertig geliefert, einmal pro Woche wird die Körperzusammensetzung gemessen. Wir haben 28 Tage gewählt, damit das Programm mit Puffer in die 30-tägige visumfreie Einreise passt, die seit dem 15. September 2026 gilt.',
    plan:['Eingewöhnung an Hitze und Belastung, Grundtechnik, Ausgangsmessungen','Zwei Trainings am Tag, Kraftblock, Ernährungskontrolle','Sparring nach Wunsch, Abschlussmessungen und Videoanalyse','Trainings- und Ernährungsplan für 90 Tage zu Hause'],
    tip:'Ohne Visum können Sie 30 Tage in Thailand bleiben. Für längere Programme helfen wir beim Visum.' },
  'mt-bangkok':{ title:'Bangkok: Woche bei Legenden, Abend im Stadion', where:'Bangkok',
    short:'Training in den Gyms der Champions und die besten Plätze am Ring im Rajadamnern-Stadion.',
    about:'Bangkok ist Muay-Thai-Geschichte: Gyms, in denen Champions trainiert haben, und das Rajadamnern-Stadion, in dem fast jeden Abend gekämpft wird. In fünf Tagen trainieren Sie in zwei bis drei klassischen Gyms, nehmen täglich ein Personal Training und verfolgen einen Kampfabend von Plätzen direkt am Ring. Tickets kaufen wir nur an offiziellen Kassen – ohne Aufschläge von Zwischenhändlern.',
    plan:['Morgen- und Abendeinheiten in einem klassischen Gym','Personal Training bei einem ehemaligen Champion','Kampfabend im Stadion mit Plätzen am Ring','Abschlusseinheit und Bangkok auf eigene Faust'],
    tip:'Die besten Monate sind November bis Februar: Von März bis Mai ist es in Bangkok sehr heiß.' },
  'mt-private':{ title:'Personal Trainer für Muay Thai', where:'Phuket oder Koh Samui',
    short:'Zehn Einheiten eins zu eins mit einem Trainer, der selbst gekämpft hat. Flexible Zeiten, passend zum Familienurlaub.',
    about:'Das Format für alle, die mit der Familie reisen und sich nicht nach dem Stundenplan eines Camps richten wollen. Der Trainer kommt zu Ihrer Villa oder erwartet Sie zur passenden Zeit im Gym. Wir wählen ihn nach Niveau und Ziel aus: Technik, Kondition oder Vorbereitung aufs Sparring.',
    plan:['Einschätzung von Niveau und Ziel','Technik, Kombinationen, Arbeit an den Pratzen','Sparring-Elemente und Plan für das eigene Training'],
    tip:'Training bei bekannten Ex-Champions kostet mehr – wir finden eine Lösung für Ihr Budget.' },
  'mt-fight':{ title:'Vorbereitung auf den ersten Kampf', where:'Phuket',
    short:'Sechs bis acht Wochen Camp, Sparring und der Gang in den Ring – mit einem Profiteam in Ihrer Ecke.',
    about:'Für alle, die sich wirklich auf die Probe stellen wollen. Ein Camp mit Erfahrung darin, Ausländer auf ihr Debüt vorzubereiten, 10–20 Personal Trainings, Sparring, Gewichtskontrolle und ärztliche Freigabe. Den Kampf organisiert das Gym – in einem Stadion auf Phuket oder bei einem internen Turnier. Ein Kampf ist nicht garantiert: Der Trainer entscheidet, wann Sie bereit sind.',
    plan:['Grundlagen, Ausdauer, Einschätzung durch den Trainer','Sparring, Personal Trainings, Taktik','Unmittelbare Wettkampfvorbereitung, Gewichtskontrolle, ärztliche Freigabe und Kampf','Regeneration und Kampfanalyse'],
    tip:'Das Programm dauert länger als 30 Tage, Sie brauchen also ein Visum; wir helfen mit den Unterlagen, auch beim DTV.' },
  'bjj-camp':{ title:'Brazilian-Jiu-Jitsu-Camp', where:'Phuket',
    short:'BJJ für Einsteiger und Blaugurte: morgens Technik, abends Sparring, dazu zwei Personal Trainings.',
    about:'Phuket ist einer der besten BJJ-Standorte Asiens: mehrere Gyms mit Schwarzgurten an einer einzigen Straße. Morgens Technik, abends Sparring mit Partnern Ihrer Gewichtsklasse, zur Wochenmitte zwei Personal Trainings. Einen Gi kann man leihen, besser ist aber der eigene.',
    plan:['Kennenlernen des Gyms und Einschätzung des Niveaus','Morgens Technik, abends Sparring','Personal Trainings: Analyse Ihrer Positionen','Abschluss-Sparring und Entwicklungsplan'] },
  'boxing-camp':{ title:'Boxcamp in Almaty', where:'Almaty',
    short:'Die kasachische Boxschule: Pratzen, Sandsack und Sparring mit Trainern aus der olympischen Nachwuchsförderung.',
    about:'Das kasachische Boxen ist eine der stärksten Schulen der Welt, und Almaty ist ihre Hauptstadt. Fertige internationale Camps gibt es hier kaum, deshalb stellen wir das Programm selbst zusammen: ein Personal Trainer aus einer Sportschule, zwei Einheiten am Tag, Sparring nach Niveau, ein Hotel nahe der Halle und am freien Tag das Alatau-Gebirge.',
    plan:['Ankunft, Einschätzung des Niveaus, erste Einheit','Zwei Einheiten am Tag – Technik und Partnerarbeit','Abschluss-Sparring und Wanderung in den Bergen'],
    tip:'Beste Zeit: April–Juni und September–Oktober; im Winter liegt Smog über der Stadt.' },
  'mma-camp':{ title:'MMA-Camp an der Seite der Profis', where:'Phuket',
    short:'Schlagtechnik, Ringen und Bodenkampf: zwei Wochen in einem Gym, in dem sich Kämpfer großer Ligen vorbereiten.',
    about:'MMA auf Phuket heißt: Gyms, in denen Kämpfer professioneller Ligen trainieren. Sie durchlaufen den kompletten Zyklus – Muay Thai, Ringen, BJJ, Arbeit am Käfig – und dazu vier Personal Trainings. In eine Gruppe mit den Profis kommt man nur auf Einladung des Trainers nach einer Einschätzung des Niveaus; das sagen wir offen vorab.',
    plan:['Einschätzung und Grundkurse in drei Disziplinen','Kompletter Zyklus und Personal Trainings','Intensivphase, Sparring, Auswertung'] },
  'mt-samui-lux':{ title:'Muay Thai und Villa auf Koh Samui', where:'Koh Samui',
    short:'Personal Trainer in der Villa, Privatkoch und tägliche Massage. Ein Kampf nur, wenn Sie es wollen.',
    about:'Muay Thai im Stil eines privaten Resorts: Villa mit Pool und Meerblick, der Trainer kommt zweimal täglich, ein Privatkoch bereitet die Mahlzeiten passend zur Belastung zu, Massage an jedem Abend. Das Richtige, wenn Sie mit der Familie reisen oder Ruhe mehr schätzen als Camp-Atmosphäre.',
    plan:['Check-in und Kennenlernen des Trainers','Zwei Trainings am Tag, Massage, Küche vom Privatkoch','Abschlusstraining und Erholung'],
    tip:'Die besten Monate auf Koh Samui sind Januar bis August; Oktober bis Dezember ist Regenzeit.' },
  // ── Trainingscamps ──────────────────────────────────────────────
  'hyrox-camp':{ title:'Hyrox-Camp auf Phuket', where:'Phuket',
    short:'Vorbereitung auf den am schnellsten wachsenden Fitnesswettkampf: Laufen, acht Stationen und eine komplette Rennsimulation.',
    about:'Hyrox ist ein Rennen aus 8 km Laufen und acht funktionellen Stationen – und das Interesse daran wächst schneller als an jedem anderen Fitnesswettkampf. Wir stellen einen Wochenblock in einem Gym für funktionelles Training an der Soi Ta-iad zusammen: Technik an den Stationen, Tempo, Training in der Hitze und zum Schluss eine komplette Rennsimulation. Fertige Hyrox-Camps gibt es in Asien kaum.',
    plan:['Leistungstest, Stationstechnik, Tempolauf','Intervalle, kombinierte Abläufe, Regeneration','Komplette Rennsimulation mit Zeitnahme','Auswertung und Vorbereitungsplan für Ihren Wettkampf'],
    tip:'Beste Zeit: November–März, wenn es kühler ist.' },
  'fatloss-camp':{ title:'Fettabbau-Camp auf Phuket', where:'Phuket',
    short:'Zwei Wochen Cardio, Kraft und Muay Thai mit kalorienberechneter Ernährung und Messungen. Danach ein Plan für 90 Tage.',
    about:'Fitnesscamps auf Phuket bedeuten 2–3 Trainings am Tag in einem Klima, in dem man leicht in den Rhythmus findet. Wir ergänzen, was den meisten fehlt: eine berechnete Ernährung, gelieferte Mahlzeiten, Messungen der Körperzusammensetzung zu Beginn und am Ende und einen Plan für 90 Tage, damit das Ergebnis nach der Rückkehr bleibt. Keine Versprechen wie „minus 10 kg“ – nur ein klares System.',
    plan:['Messungen, Beratung, erstes Training','Zirkel, Kraft, Muay Thai und Cardio, Ernährung nach Plan','Abschlussmessungen und Plan für 90 Tage'] },
  'trail-camp':{ title:'Trailrunning-Camp in den Bergen von Chiang Mai', where:'Chiang Mai',
    short:'Trails am Doi Suthep und Doi Inthanon, Bergab-Technik und kühle Morgen in der Höhe.',
    about:'Nordthailand heißt: Berge bis 2565 Meter am Doi Inthanon und ein Netz von Trails, das direkt von der Stadt auf den Doi Suthep führt. Fünf Läufe mit Guide, ein Tag am höchsten Punkt des Landes und Massage nach jeder langen Einheit. Ideal zur Vorbereitung auf einen Berglauf – oder um die Freude am Laufen wiederzufinden.',
    plan:['Lockerer Lauf und erste Trails','Bergintervalle, Bergab-Technik, langer Lauf','Doi Inthanon – der höchste Punkt Thailands','Regeneration'],
    tip:'Nur November–Januar: Von Februar bis April liegt im Norden Rauch von Feldbränden in der Luft.' },
  'tri-camp':{ title:'Triathlon-Trainingslager auf Phuket', where:'Phuket, Laguna',
    short:'50-Meter-Becken, Freiwasser, Radfahren entlang der Küste und Laufblöcke – von der Sprintdistanz bis 70.3.',
    about:'Das Laguna-Gebiet auf Phuket ist das Triathlon-Zentrum Thailands: 50-Meter-Becken, eine ruhige Lagune fürs Freiwasserschwimmen und Radstrecken entlang der Küste. Der Trainer plant die Belastung passend zu Ihrer Distanz; das Rad mieten Sie oder bringen Ihr eigenes mit, ein Mechaniker ist dabei. Ende November findet hier der Laguna Phuket Triathlon statt.',
    plan:['Tests im Becken und auf dem Radtrainer','Blöcke Schwimmen–Rad–Laufen, Freiwasser','Koppeltraining als Test und Auswertung'],
    tip:'November–März; von Mai bis Oktober ist es an der Westküste stürmisch.' },
  'marathon-camp':{ title:'Höhentrainingslager in Iten', where:'Iten, Kenia',
    short:'Training auf 2400 m in der Stadt der Weltmeister – gemeinsam mit einheimischen Läufern.',
    about:'Iten gilt als Heimat der Champions: Hier leben und trainieren die besten Langstreckenläufer der Welt. Zwei Wochen auf 2400 Metern, Vollpension im Trainingszentrum, Gruppenläufe mit kenianischen Athleten, Stadion und Massage. Die Höhe fördert die Ausdauer, die Atmosphäre bringt eine Motivation, die man zu Hause nicht kaufen kann.',
    plan:['Akklimatisierung und lockere Läufe','Gruppentraining, Stadion, lange Läufe','Testeinheit und Heimreise'],
    tip:'Die besten Zeitfenster sind Januar–März und Juni–Oktober; für Kenia brauchen Sie eine elektronische Einreisegenehmigung (eTA).' },
  'cycling-camp':{ title:'Radtrainingslager auf Mallorca oder in Girona', where:'Mallorca oder Girona',
    short:'Anstiege, Gruppenausfahrten, Mechaniker und Begleitfahrzeug.',
    about:'Auf Mallorca und in Girona bereiten sich im Frühjahr Profiteams vor. Ein Guide führt die Gruppe über die besten Routen, das Begleitfahrzeug bringt Wasser und Ersatzteile, ein Mechaniker macht das Rad startklar. Hotel mit Halbpension und Massage nach langen Tagen.',
    plan:['Bikefitting und lockere Ausfahrt','Routen über 80–140 km, Anstiege, Fahren in der Gruppe','Freie Ausfahrt und Erholung'],
    tip:'Februar–Mai und September–Oktober. Mit EU- oder Schweizer Pass ohne Visum; für andere Pässe kann ein Schengen-Visum nötig sein.' },
  'strength-40':{ title:'Kraftcamp 40+ in Dubai', where:'Dubai',
    short:'Kraft, Mobilität, Laborwerte und ein Protokoll vom Sportmediziner – fünf Tage für Männer über vierzig.',
    about:'Nach vierzig „wie mit zwanzig“ zu trainieren, ist der direkte Weg zur Verletzung. Fünf Tage mit einem zertifizierten Trainer und einem Sportmediziner: Messung der Körperzusammensetzung (DEXA), Laborwerte, Mobilität, zwei Trainings am Tag und Physiotherapie. Am Ende steht ein Trainings- und Regenerationsprotokoll für das kommende Jahr.',
    plan:['DEXA, Laborwerte, ärztliche Beratung','Zwei Trainings am Tag, Mobilität, Physiotherapie','Abschlussgespräch und Protokoll für ein Jahr'],
    tip:'November–März, wenn sich in Dubai angenehm trainieren lässt.' },
  'altitude-camp':{ title:'Höhentrainingslager im Kaukasus', where:'Zaghkadsor oder Kislowodsk',
    short:'Mittlere Höhenlage für die Ausdauer: Laufen, Rad und Schwimmen in olympischen Zentren.',
    about:'Zaghkadsor in Armenien (rund 1850 m) ist ein olympisches Trainingszentrum, in dem Nationalmannschaften trainieren: Stadion, Schwimmbad und Trails. Kislowodsk liegt tiefer (900–1400 m) und eignet sich für eine sanfte Anpassung. Trainer, Halbpension, Massage und ein Belastungsplan für Ihren Wettkampf.',
    plan:['Anpassung an die Höhe','Hauptblock – Laufen, Rad, Schwimmen','Testeinheit'], tip:'Juni–September.' },
  'ski-camp':{ title:'Skicamp mit Trainer', where:'Gudauri oder Shymbulak',
    short:'Carving oder Freeride mit Guide. Skipass, Verleih und zwei Stunden Training pro Tag.',
    about:'Eine Woche in den Bergen mit Personal Trainer: jeden Tag zwei Stunden Unterricht mit Videoanalyse der Technik, die übrige Zeit freies Fahren. Gudauri in Georgien ist für Freeride und Sonne bekannt, Shymbulak für seine Pisten 30 Minuten von Almaty. Skipass, Verleih und Hotel mit Halbpension sind inklusive.',
    plan:['Einschätzung des Niveaus, Anpassen der Ausrüstung','Zwei Stunden mit dem Trainer, freies Fahren, Videoanalyse','Freies Fahren'],
    tip:'Dezember–März. Für Georgien kann eine Reiseversicherung vorgeschrieben sein.' },
  // ── Check-up & Longevity ────────────────────────────────────────
  'checkup-bkk':{ title:'Executive Check-up in Bangkok', where:'Bangkok',
    short:'Umfassende Untersuchung in einem internationalen Krankenhaus an einem Tag. Befund auf Englisch erklärt, Hotel und Transfers.',
    about:'Die Krankenhäuser Bangkoks gehören zu den wichtigsten Zentren des Medizintourismus weltweit; die führenden sind JCI-akkreditiert und veröffentlichen ihre Paketpreise. Ein Männerpaket 40+ umfasst in der Regel Laborwerte und Tumormarker (darunter PSA), EKG, Belastungstest, Ultraschall des Bauchraums, Röntgen und ein Arztgespräch am selben Tag. Wir wählen Krankenhaus und Paket, buchen den Termin, holen Sie ab, gehen den Befund mit Ihnen auf Englisch durch und fassen die nächsten Schritte in einem Plan zusammen.',
    plan:['Am Vortag: Hinweise zur Vorbereitung und Transfer ins Hotel','Untersuchungstag: 4–8 Stunden, nüchtern, ein Koordinator an Ihrer Seite','Besprechung der Ergebnisse mit dem Arzt','Befund auf Englisch erklärt und Plan für die nächsten Schritte'],
    tip:'Aktionspreise der Krankenhäuser gelten manchmal nur für Einwohner Thailands – wir lassen uns den Preis für ausländische Patienten schriftlich bestätigen.' },
  'mens-health':{ title:'Männergesundheit: Urologe, Hormone, Prostata', where:'Bangkok',
    short:'Urologe und Androloge, Hormonprofil, PSA und Ultraschall – ein ruhiges Gespräch ohne Verlegenheit.',
    about:'Die Untersuchung, die Männer jahrelang aufschieben. Termin bei einem Urologen mit Schwerpunkt Andrologie, Hormonpanel (Gesamt- und freies Testosteron, SHBG, LH/FSH, Prolaktin, Östradiol, TSH), PSA, Ultraschall von Nieren und Prostata, Uroflowmetrie. Alle Verordnungen trifft ausschließlich der Arzt nach der Untersuchung; wir organisieren den Ablauf und begleiten Sie auf Englisch.',
    plan:['Blutabnahme nüchtern','Untersuchung, Ultraschall, Uroflowmetrie','Besprechung der Ergebnisse und ärztliche Empfehlungen'],
    tip:'Hormonpräparate nur auf ärztliche Verordnung; wir verkaufen und versenden keine Medikamente.' },
  'longevity-week':{ title:'Longevity-Woche: Check-up und Protokoll', where:'Bangkok und Phuket',
    short:'Check-up, biologisches Alter, VO2max und ein Jahresplan für Schlaf, Ernährung und Training.',
    about:'Sieben Tage, um zu verstehen, wie Sie altern und was Sie daraus machen können. Erweiterter Check-up in einem Krankenhaus in Bangkok, Test des biologischen Alters, Spiroergometrie (VO2max), Körperzusammensetzung, Gespräche mit Arzt und Ernährungsberater. Die zweite Wochenhälfte verbringen Sie in einem Resort auf Phuket und starten dort unter Anleitung Ihren neuen Tagesrhythmus. Das biologische Alter ist ein Richtwert, keine Diagnose: Eine „Verjüngung“ versprechen wir nicht.',
    plan:['Check-up, VO2max und Labor in Bangkok','Besprechung der Ergebnisse mit dem Arzt','Resort auf Phuket: Schlaf, Training, Ernährung','Jahresprotokoll und Kontrolltermine'] },
  'heart-check':{ title:'Herz-Check-up und Sporttauglichkeit', where:'Bangkok',
    short:'EKG, Belastungstest, Echokardiografie und Koronarkalk-Score – für alle, die laufen und kämpfen.',
    about:'Vor einem Marathon, einem Kampf oder einer Hochtour sollten Sie wissen, wie Ihr Herz unter Belastung arbeitet. Das Programm in einem spezialisierten Herzzentrum: EKG, Belastungstest oder Stressecho, Echokardiografie, CT-Bestimmung des Koronarkalk-Scores, Lipidprofil und kardiologischer Befund. Gibt es einen auffälligen Befund, werden weitere Schritte separat und nur mit Ihrer Zustimmung vereinbart.',
    plan:['Laborwerte und EKG','Belastungstest und Echokardiografie','CT-Koronarkalk-Score','Kardiologischer Befund und Sporttauglichkeit'] },
  'sleep-lab':{ title:'Schlaflabor', where:'Bangkok',
    short:'Polysomnografie mit Übernachtung: Apnoe, Schnarchen, Schlafqualität und ein Plan zur Erholung.',
    about:'Wenn Sie müde aufwachen, schnarchen oder jemand bei Ihnen Atemaussetzer bemerkt, ist das ein Grund, den Schlaf untersuchen zu lassen. Eine Nacht im Schlaflabor mit Polysomnografie, Gespräch mit einem Schlafmediziner und ein Plan. Bei Verdacht auf Apnoe kann der Arzt eine zweite Nacht zur CPAP-Einstellung vorschlagen.',
    plan:['Abends: Aufnahme im Schlaflabor und Anlegen der Sensoren','Nachts: Schlafaufzeichnung unter Beobachtung','Morgens: Gespräch mit dem Schlafmediziner und Plan'] },
  'dna-plan':{ title:'DNA-Test und persönlicher Plan', where:'Online, Testkit per Post',
    short:'Genetik zu Ernährung, Sport und Risiken – mit Befundbesprechung bei einem Humangenetiker auf Englisch.',
    about:'Das Speichel-Testkit kommt zu Ihnen nach Hause, das Ergebnis nach 4–10 Wochen. Besprechung mit einem Humangenetiker: Besonderheiten des Stoffwechsels, Reaktion auf Belastung, erbliche Risiken – und was davon wirklich relevant ist. Ein DNA-Test ist keine Diagnose, und wir sagen offen, wo die Wissenschaft endet und das Marketing beginnt.',
    plan:['Bestellung und Lieferung des Testkits','Laboranalyse: 4–10 Wochen','Besprechung mit dem Humangenetiker und Plan'],
    tip:'Genetische Daten gehören zu den besonderen Kategorien personenbezogener Daten; wir arbeiten nur mit Ihrer schriftlichen Einwilligung.' },
  'biohack-week':{ title:'Biohacking-Woche in Dubai', where:'Dubai',
    short:'Druckkammer, Kryotherapie, Infusionen nach Laborwerten und HRV-Monitoring – unter ärztlicher Aufsicht.',
    about:'Fünf Tage in lizenzierten Kliniken in Dubai: ärztliche Untersuchung und Laborwerte, tägliche Sitzungen mit hyperbarer Sauerstofftherapie und Kryotherapie, Infusionen nur auf ärztliche Verordnung, Regeneration und ein abschließender Plan. Wunder versprechen wir nicht: Für viele Anwendungen ist die Evidenz schwach, deshalb entscheidet der Arzt, und Sie bekommen ein ehrliches Bild.',
    plan:['Arzt, Laborwerte, Prüfung der Kontraindikationen','Druckkammer, Kryotherapie, Regeneration','Abschlussgespräch und Plan'],
    tip:'November–März. Für viele Medikamente ist in den VAE eine Einfuhrgenehmigung nötig.' },
  'seoul-checkup':{ title:'Check-up in Seoul', where:'Seoul',
    short:'Koreanische Medizin: erweiterter Check-up mit MRT und Endoskopie in zwei Tagen.',
    about:'Die führenden Krankenhäuser Seouls bieten einen der gründlichsten Check-ups der Welt: Laborwerte, Endoskopie unter Sedierung, CT und MRT, Herzdiagnostik und Ergebnisbesprechung – in zwei Tagen. Wir arbeiten mit in Korea registrierten Agenturen für Medizintourismus.',
    plan:['Labor, Bildgebung, Endoskopie','Übernachtung im Krankenhaus oder Hotel','Herzdiagnostik und Ergebnisbesprechung'],
    tip:'Beste Zeit: Frühling und Herbst.' },
  // ── Detox & Neustart ────────────────────────────────────────────
  'detox-samui':{ title:'Detox-Retreat auf Koh Samui', where:'Koh Samui',
    short:'Clean Eating, Yoga, Massage, Sauna und Ernährungsberatung – eine Woche Neustart am Meer.',
    about:'Koh Samui ist die Insel der klassischen Wellness-Retreats. Eine Woche in Ruhe: Säfte oder leichte Kost, täglich Massage, Yoga und Sauna, dazu eine Ernährungsberatung. „Detox“ verstehen wir ehrlich: als Neustart des Tagesrhythmus, nicht als „Ausleitung von Giftstoffen“. Wir finden das passende Format – vom ruhigen Boutique-Retreat bis zu den großen Flaggschiff-Resorts.',
    plan:['Beratung und Programm','Kost nach Programm, Massage, Yoga, Sauna','Aufbautage und Ernährungsplan'],
    tip:'Januar–September; von Oktober bis Dezember regnet es auf Koh Samui. Fasten ist nicht für jeden geeignet – wir klären das vorab.' },
  'weight-reset':{ title:'Gewichts-Reset in 21 Tagen', where:'Phuket',
    short:'Arzt, Ernährungsberater, Trainer und ein klarer Plan. Messungen vorher und nachher, 90 Tage Begleitung.',
    about:'Drei Wochen, um das Gewicht wieder in Bewegung zu bringen. Eingangsuntersuchung und EKG für Männer ab 40, 2–3 Trainings am Tag, gelieferte Mahlzeiten und wöchentliche Messungen der Körperzusammensetzung. Danach 90 Tage Online-Begleitung. Medikamente zur Gewichtsreduktion werden nur mit dem Arzt besprochen und sind nicht Teil des Programms.',
    plan:['Untersuchung, EKG, Messungen und Plan','Training, Ernährung und wöchentliche Messungen','Abschlussmessungen und Plan für 90 Tage'],
    tip:'21 Tage passen in die 30 Tage visumfreie Einreise.' },
  'sober-retreat':{ title:'Sober Retreat: 14 Tage ohne Alkohol', where:'Bali',
    short:'Männergruppe, Sport, Arbeit mit einem Psychologen und neue Gewohnheiten – ohne Moralpredigt.',
    about:'Keine Klinik und keine „Behandlung“, sondern zwei Wochen, um das Leben ohne Alkohol von innen zu erleben: Gruppe, Sport, Gruppen- und Einzelsitzungen, Ernährung und Schlaf. Vorab gibt es einen Fragebogen: Bei ausgeprägter Abhängigkeit vermitteln wir an eine Klinik mit medizinisch begleitetem Entzug, denn ein abrupter Verzicht kann gefährlich sein.',
    plan:['Fragebogen und Telefonat vor der Reise','Tagesrhythmus, Sport und Gruppe','Neue Gewohnheiten und Plan für zu Hause','Online-Begleitung nach der Rückkehr'] },
  'digital-detox':{ title:'Digital Detox im Dschungel von Khao Sok', where:'Khao Sok, Floßhaus',
    short:'Kein Netz – dafür ein See, Felsen, Stille und Angeln im Morgengrauen.',
    about:'Der Cheow-Lan-See zwischen Kalksteinfelsen gehört zu den schönsten Orten Thailands. Vier Tage im Floßhaus: Kajak, Höhlen, Dschungelwanderungen und morgendliches Angeln vom Longtail-Boot. Das Telefon kommt für die ganze Zeit in den Safe: Auf manchen Floßhäusern gibt es inzwischen 4G, deshalb setzen wir die Regeln selbst.',
    plan:['Transfer, Longtail-Boot, Check-in','Kajak, Höhlen, Dschungel und Angeln','Sonnenaufgang am See und Rückreise'], tip:'Dezember–April.' },
  'fasting':{ title:'Fasten unter ärztlicher Aufsicht', where:'Deutschland oder Österreich',
    short:'Klassische Fastenkliniken: ärztliche Kontrolle, Anwendungen und ein behutsamer Kostaufbau.',
    about:'Europäische Fastenkliniken arbeiten seit Jahrzehnten nach den Methoden von Buchinger und Mayr: Untersuchung und Laborwerte, tägliche ärztliche Kontrolle, Anwendungen und ein schrittweiser Kostaufbau. Wir buchen die Klinik und kümmern uns um Transfers und, falls nötig, um das Visum. Bei einer Reihe von Erkrankungen ist Fasten kontraindiziert – die Klinik prüft das vor Beginn.',
    plan:['Fragebogen der Klinik vor der Reise','Untersuchung, Laborwerte, Vorbereitung','Programm unter ärztlicher Aufsicht','Kostaufbau und Empfehlungen'],
    tip:'2–4 Monate im Voraus buchen; für Pässe außerhalb von EU und Schweiz kann ein Schengen-Visum nötig sein.' },
  'ayurveda':{ title:'Ayurveda: Panchakarma in Kerala', where:'Kerala, Indien',
    short:'Ein traditionelles Reinigungsprogramm in einem Ayurveda-Zentrum – 14 Tage.',
    about:'Kerala ist die Heimat des Ayurveda. Zwei Wochen in einem akkreditierten Zentrum: Untersuchung durch einen Ayurveda-Arzt, Vorbereitung, die Hauptanwendungen des Panchakarma, Ernährung und Yoga. Wir wählen akkreditierte Zentren aus und raten davon ab, Präparate ohne geprüfte Zusammensetzung mit nach Hause zu nehmen.',
    plan:['Untersuchung und Vorbereitungsphase','Hauptanwendungen','Erholung und Empfehlungen'],
    tip:'Traditionell gelten der Monsun (Juni–September) und die Trockenzeit (November–März) als beste Reisezeit.' },
  'burnout':{ title:'Burn-out-Retreat', where:'Chiang Mai',
    short:'Schlaf, Berge, Psychologe, Körperarbeit und ein Plan für die Rückkehr in den Job.',
    about:'Zehn Tage, um auszuschlafen, durchzuatmen und zu verstehen, was sich ändern soll. Screening Ihres Zustands, tägliche Einzelsitzungen, Körperarbeit, Meditation, Wanderungen in den Bergen und ein Plan für die Rückkehr in den Job. Burn-out ist keine Diagnose, doch bei Anzeichen einer Depression ziehen wir Fachleute hinzu.',
    plan:['Screening, Schlaf und Tagesrhythmus','Sitzungen, Übungen und Berge','Plan für die Rückkehr in den Job'],
    tip:'Oktober–Januar: Von Februar bis April ist die Luft in Chiang Mai rauchig.' },
  // ── Regeneration ────────────────────────────────────────────────
  'sauna-ice':{ title:'Sauna und Eisbad: Kurs', where:'Phuket',
    short:'Kontrastprotokolle, Atemübungen und HRV-Messung. Genau das Richtige nach einem Langstreckenflug.',
    about:'Fünf Sitzungen in einem Studio für Kontrasttherapie: Sauna, Eisbad, Atemübungen und Messung der Herzfrequenzvariabilität (HRV) mit Ihrer Uhr. Das unterstützt die Erholung nach Training und Flug. Vor dem Kurs gibt es eine kurze Abfrage: Bei Herz- oder Blutdruckproblemen ist Kälte nicht für jeden geeignet.',
    plan:['Einweisung und sanftes Protokoll','Mehr Zeit in der Kälte, Atemübungen','Abschließende HRV-Messung'] },
  'thai-massage':{ title:'Thai-Massage und Stretching in Chiang Mai', where:'Chiang Mai',
    short:'Täglich zwei Stunden Massage bei Meistern der alten Schule und Stretching für den Rücken.',
    about:'Chiang Mai ist die Hauptstadt der traditionellen Thai-Massage. Fünf Tage mit je zwei Stunden bei Meistern der alten Schule: Arbeit an Rücken und Hüftgelenken, Stretching. Wenn Sie es selbst lernen möchten, melden wir Sie für einen Kurs an der Schule eines Krankenhauses für traditionelle Medizin an.',
    plan:['Einschätzung und sanfte Massage','Tiefe Arbeit und Stretching','Abschlusssitzung und Übungen für zu Hause'], tip:'November–Februar.' },
  'sports-recovery':{ title:'Regeneration für Sportler', where:'Phuket',
    short:'Physiotherapeut, Sportmassage, Mobilität und Kälte – für alle, die zum Kämpfen kamen und es übertrieben haben.',
    about:'Eine Woche Regeneration nach einem Camp, einem Marathon oder einer Verletzung: vier Sitzungen beim Physiotherapeuten, fünf Sportmassagen, Kontrastanwendungen und Mobilitätstraining. Eine Unterkunft kann bei Bedarf hinzugebucht werden.',
    plan:['Befundaufnahme beim Physiotherapeuten','Massage, Mobilität, Kälte','Abschließende Einschätzung und Übungen'] },
  'spa-week':{ title:'Spa-Woche für Männer auf Bali', where:'Bali',
    short:'Villa mit Pool, tägliche Anwendungen, Yoga für Ungelenkige und Stille.',
    about:'Balinesische Massage, eine Villa zwischen den Reisterrassen von Ubud, Yoga für alle, die noch nie Yoga gemacht haben, und kein Zeitplan außer den Anwendungen. Ideal nach einem harten Jahr oder zwischen zwei Projekten.',
    plan:['Check-in und erste Massage','Anwendungen, Yoga und Spaziergänge','Abreise'], tip:'April–Oktober: Trockenzeit.' },
  'onsen':{ title:'Onsen und Ryokans in Japan', where:'Hakone und Kyoto',
    short:'Heiße Quellen, Kaiseki-Dinner und ein Schlaf, wie Sie ihn lange nicht hatten. Preis pro Person.',
    about:'Zwei Nächte in einem Ryokan in Hakone mit privatem Onsen und Blick auf die Berge, zwei in Kyoto, dazwischen die Bahnfahrt und ein Tag mit Guide. Das japanische Ritual aus Bad und Kaiseki-Dinner erholt tiefer als jedes Spa. Der Preis gilt pro Person bei Doppelbelegung.',
    plan:['Hakone: Ryokan und Onsen','Fahrt nach Kyoto','Tempel mit Guide und Ryokan'],
    tip:'November sowie Ende März bis April; im Januar und Februar sind die Preise am günstigsten. Mit Tattoos wird man in öffentliche Bäder oft nicht eingelassen.' },
  'banya':{ title:'Russische Banja mit Saunameister', where:'Moskauer Umland oder Altai',
    short:'Echtes Banja-Dampfbad, Tauchbecken, Kräutertee und Massage – zwei Tage.',
    about:'Ein Dampfbad beim Meister ist mehr als ein Saunagang: Badebesen, Temperatur, Rhythmus und Tauchbecken werden auf Sie abgestimmt. Zwei Sitzungen mit dem Saunameister, Massage, eine Übernachtung in einer Anlage auf dem Land und Transfers.',
    plan:['Anreise, erste Sitzung und Abendessen','Zweite Sitzung, Massage und Abreise'], tip:'Oktober–März.' },
  'dead-sea':{ title:'Totes Meer: Rücken und Gelenke', where:'Jordanien',
    short:'Schlamm, Mineralwasser und Physiotherapie am tiefsten Landpunkt der Erde.',
    about:'Rund 430 Meter unter dem Meeresspiegel: dichtes Wasser, mineralischer Schlamm und eine besondere Luft. Sieben Nächte im Hotel mit Spa, ärztliche Untersuchung, sechs Anwendungen und drei Physiotherapie-Sitzungen. Am besten untersucht ist die Wirkung bei Hauterkrankungen; für die Gelenke ist die Evidenz mäßig, und das sagen wir offen.',
    plan:['Ärztliche Untersuchung und Programm','Anwendungen und Physiotherapie','Abschluss und Empfehlungen'], tip:'Oktober–April.' },
  // ── Geist & Ruhe ────────────────────────────────────────────────
  'silent-retreat':{ title:'Schweige-Retreat: 10 Tage Meditation', where:'Chiang Mai',
    short:'Meditation, Schweigen und einfaches Essen. Wir kümmern uns um Anreise und Begleitung.',
    about:'Klassische zehntägige Meditationskurse (etwa Vipassana in der Tradition von Goenka) sind kostenlos und werden über Spenden getragen – und so soll es bleiben. Deshalb verkaufen wir den Kurs selbst nicht: Wir helfen bei der Wahl des Zentrums und der Anmeldung, organisieren Transfer, Hotel davor und danach und holen Sie am Ende ab. Wer es sanfter möchte, wählt ein privates Retreat mit Mentor (ab 1500 USD).',
    plan:['Wahl des Zentrums und Anmeldung','Transfer und Übernachtung vor dem Start','Zehn Tage Kurs','Abholung, Erholung und Gespräch danach'],
    tip:'Intensive Meditation ist nicht für jeden geeignet – informieren Sie uns vorab über psychische Besonderheiten oder Vorerkrankungen.' },
  'breathwork':{ title:'Atemarbeit und Kälte auf Bali', where:'Bali',
    short:'Atemübungen, Eiswasser und Umgang mit Stress – fünf Tage.',
    about:'Fünf Tage Atemübungen und Kontrastkälte mit einem zertifizierten Instruktor, Yoga, Sauna und eine ruhige Villa. Sicherheitsregel: Atemübungen mit Atemanhalten niemals im oder am Wasser. Vorab gibt es einen Gesundheitsfragebogen.',
    plan:['Grundlagen und Sicherheit','Übungen, Eis und Sauna','Integration und Plan für zu Hause'] },
  'mens-retreat':{ title:'Männer-Retreat im Altai', where:'Altai',
    short:'Männergruppe, Berge, Lagerfeuer, Banja und ehrliche Gespräche mit einem erfahrenen Leiter.',
    about:'Fünf Tage im Altai-Gebirge mit einer kleinen Männergruppe: Wanderungen, Rafting, Banja und abendliche Runden am Lagerfeuer mit einem erfahrenen Leiter. Für Männer, die offen über das sprechen wollen, worüber man sonst schweigt – unter Männern, denen es ähnlich geht.',
    plan:['Treffen der Gruppe und Basislager','Wanderungen, Rafting, Banja und Gesprächsrunden','Abschluss'],
    tip:'Juni–September. Eine FSME-Impfung ist erforderlich; manche Gebiete liegen in der Grenzzone.' },
  'coaching':{ title:'Performance-Coaching', where:'Online',
    short:'Ziele, Energie und Fokus: sechs Sitzungen mit einem Coach, der mit Unternehmern gearbeitet hat.',
    about:'Sechs Videositzungen à 60 Minuten mit einem ICF-zertifizierten Coach: Standortbestimmung, Quartalsziele, Energiemanagement, Delegieren, Fokus. Zwischen den Sitzungen Kontakt per Messenger. Coaching ist keine Psychotherapie: Geht es um Ihr seelisches Befinden, ziehen wir einen Psychologen hinzu.',
    plan:['Standortbestimmung und Ziele','Arbeit nach Plan','Bilanz und Plan für das nächste Quartal'] },
  'monk-week':{ title:'Eine Woche im buddhistischen Kloster', where:'Nordthailand',
    short:'Frühes Aufstehen, Meditation, Arbeit und Stille. Wir übernehmen Anreise und Vorbereitung.',
    about:'Ein Klosteraufenthalt ist kein touristisches Produkt, und wir verkaufen ihn nicht: Über die Aufnahme entscheidet der Abt, Ihre Spende übergeben Sie selbst. Wir bereiten Sie auf die Reise vor, erklären die Regeln (acht Übungsregeln, nach Mittag kein Essen, kein Telefon) und organisieren den Wagen ab Chiang Mai, das Hotel davor und danach sowie die weiße Kleidung.',
    plan:['Vorbereitung: Regeln und Etikette','Transfer und Übernachtung in Chiang Mai','Fünf Tage im Kloster','Rückkehr und Erholung'], tip:'November–Januar.' },
  'psychologist':{ title:'Psychologe für Männer', where:'Online',
    short:'Krise, Scheidung, Ängste, Wut – acht Sitzungen mit einem Psychologen, der Männer versteht.',
    about:'Wir wählen den Psychologen passend zu Ihrem Anliegen und Gesprächsstil: acht Online-Sitzungen à 50 Minuten auf Englisch oder Russisch. Ein Psychologe ist kein Arzt: Ist eine Behandlung nötig, vermitteln wir an einen Facharzt. Für akute Krisen gibt es ein festes Krisenprotokoll.',
    plan:['Auswahl der Fachperson per Fragebogen','Eine Sitzung pro Woche','Bilanz und Empfehlungen'] },
  'meditation-21':{ title:'Meditation für Vielbeschäftigte: 21 Tage', where:'Online',
    short:'Zehn Minuten am Tag mit Mentor und Fortschrittsmessung.',
    about:'Einundzwanzig kurze Übungen, drei Live-Gruppensitzungen und ein Chat mit dem Mentor. Für alle, die lernen wollen abzuschalten und besser zu schlafen, ohne dafür in die Berge zu fahren.',
    plan:['Einführungssitzung','Tägliche Übung von 10 Minuten','Abschlusssitzung'] },
  // ── Abenteuer ───────────────────────────────────────────────────
  'elbrus':{ title:'Elbrus-Besteigung', where:'Kaukasus',
    short:'Der höchste Punkt Europas – 5642 m – mit Akklimatisierung, Guides und Reservetag.',
    about:'Besteigung über die klassische Südroute: acht Tage mit Guides, Akklimatisierungstouren über 4000 Meter, Hütten, auf Wunsch Auffahrt mit der Pistenraupe und der Gipfelaufstieg. Technisch ist die Route nicht schwierig, doch das Wetter am Gipfel ist gefährlich – deshalb entscheidet der Guide, und ein Reservetag ist Pflicht.',
    plan:['Anreise und Akklimatisierung am Tscheget','Touren über 4000 m und Hütte','Gipfeltag und Reservetag','Abstieg und Heimreise'],
    tip:'Juni–September. Für ausländische Gäste: Visa- und Mastercard-Karten funktionieren in Russland nicht, westliche Versicherungen schließen die Reise oft aus.' },
  'kilimanjaro':{ title:'Kilimandscharo über die Machame-Route', where:'Tansania',
    short:'Das Dach Afrikas – 5895 m. Guides, Träger, Camps und auf Wunsch eine Safari.',
    about:'Machame ist die landschaftlich schönste Route auf den Kilimandscharo und bietet eine gute Akklimatisierung: Aufstieg durch fünf Klimazonen und die Gipfelnacht zum Uhuru Peak. Parkgebühren, Guides, Träger, Zelte, Verpflegung und zwei Nächte in Moshi sind inklusive. Eine Safari nach dem Aufstieg ist der schönste Weg, den Gipfel zu feiern.',
    plan:['Moshi und Briefing','Machame-Route über die Camps','Gipfelaufstieg zum Uhuru und Abstieg','Zertifikat und Erholung'],
    tip:'Januar–März und Juni–Oktober; April–Mai und November sind Regenzeit. Die Parkgebühren werden regelmäßig angepasst – wir prüfen sie bei der Buchung.' },
  'ebc':{ title:'Trekking zum Everest-Basislager', where:'Nepal',
    short:'Lukla, Namche Bazar, 5364 m. Lodges, lizenzierter Guide und Träger.',
    about:'Das klassische Trekking im Khumbu-Tal: Flug nach Lukla, Namche Bazar, das Kloster Tengboche und das Everest-Basislager auf 5364 m. Ein lizenzierter Guide ist nach nepalesischen Regeln Pflicht, ein Träger kommt auf zwei Personen. In der Hochsaison starten die Flüge nach Lukla in Ramechhap – wir planen Puffertage ein.',
    plan:['Kathmandu und Flug nach Lukla','Aufstieg über Namche und Tengboche mit Akklimatisierung','Basislager und Kala Patthar','Abstieg und Kathmandu'],
    tip:'März–Mai und Oktober–November. Nötig ist eine Versicherung mit Hubschrauberbergung.' },
  'kamchatka':{ title:'Kamtschatka: Vulkane und Angeln', where:'Kamtschatka',
    short:'Mit dem Hubschrauber ins Tal der Geysire, Vulkanbesteigung, Lachs im Fluss.',
    about:'Zehn Tage am Ende der Welt: Besteigung des Awatschinski oder des Gorely, ein Hubschraubertag mit Landungen im Tal der Geysire und in der Usson-Caldera, Rafting und Angeln am Fluss Bystraja. Die Hubschrauberflüge hängen vom Wetter ab – zwei Tage im Programm sind flexibel.',
    plan:['Ankunft und Thermalquellen','Vulkanbesteigung','Hubschrauber ins Tal der Geysire (wetterabhängig)','Rafting und Angeln'], tip:'Juli–September.' },
  'moto-north':{ title:'Motorradtour durch Nordthailand', where:'Mae-Hong-Son-Loop',
    short:'1864 Kurven, Berge, Nebel und Übernachtungen in Berglodges.',
    about:'Der legendäre Mae-Hong-Son-Loop: sieben Tage auf einer Enduro oder einem Tourenmotorrad mit Guide und Begleitfahrzeug, Bergpässe, Dörfer und Nebel über den Tälern. Nötig sind ein Führerschein der Klasse A und ein Internationaler Führerschein mit Eintrag „A“ – ohne sie gilt die Versicherung nicht.',
    plan:['Chiang Mai und Auswahl des Motorrads','Rundtour über Pai und Mae Hong Son','Rückkehr nach Chiang Mai'],
    tip:'November–Februar; März–April Rauch, Juni–Oktober Regen.' },
  'safari':{ title:'Safari in Kenia und Tansania', where:'Masai Mara und Serengeti',
    short:'Die Große Migration, Lodges und erfahrene Guides – acht Tage.',
    about:'Acht Tage im Geländewagen mit Aufstelldach durch die Masai Mara und die Serengeti: die Gnu-Migration, Flussüberquerungen am Mara und die Big Five. Lodges mit Vollpension, Parkgebühren und die Fahrt von einem Land ins andere sind inklusive. Flussüberquerungen kann niemand garantieren – aber die Guides wissen, wo man warten muss.',
    plan:['Masai Mara','Fahrt nach Tansania','Serengeti und Ngorongoro-Krater','Abflug'],
    tip:'Juli–Oktober: Migration in der Mara; Januar–Februar: Kalbungszeit in der südlichen Serengeti.' },
  'railay-climb':{ title:'Klettern in Railay', where:'Krabi',
    short:'Kalkfelsen über dem Meer. Von null bis zur ersten Route im Vorstieg.',
    about:'Railay ist eines der besten Klettergebiete Asiens: Kalksteinwände direkt über dem Strand. Ein dreitägiger Kurs mit Kletterlehrer – vom Toprope bis zur ersten Route im Vorstieg – und drei Nächte in Railay, das nur per Boot erreichbar ist.',
    plan:['Technik und Toprope','Vorstieg und Ablassen','Erste Route im Vorstieg'], tip:'November–April.' },
  'altai-horse':{ title:'Wanderritt durch den Altai', where:'Altai',
    short:'Pässe, Bergseen und Nächte im Zelt – sieben Tage im Sattel.',
    about:'Eine Woche im Sattel durch die Berge des Altai: Pässe, Gletscherseen, Übernachtungen im Zelt und in einfachen Berglagern, Vollpension und erfahrene Guides. Reiterfahrung ist nicht nötig – die Pferde werden passend zum Reiter ausgewählt. Für Routen zur Belucha braucht es eine Genehmigung für die Grenzzone; wir beantragen sie rechtzeitig.',
    plan:['Basislager und Einweisung','Route über Pässe und Seen','Rückkehr'], tip:'Ende Juni bis Anfang September.' },
  'uzbek-mountains':{ title:'Berge Usbekistans: Tschimgan und Pskem', where:'Usbekistan',
    short:'Die Heimat von ERKAK: Trekking, Gebirgsflüsse und Plov am Feuer.',
    about:'Sechs Tage im westlichen Tian Shan, zwei Stunden von Taschkent: der Große Tschimgan (3309 m), die Schluchten von Beldersai und Pskem, Übernachtungen im Zelt und in Gästehäusern. Genau aus diesen Bergen stammt das Shilajit von ERKAK. Für Routen nahe der kirgisischen Grenze braucht es eine Genehmigung – darum kümmern wir uns.',
    plan:['Taschkent und Fahrt in die Berge','Trekking am Tschimgan und im Pskem-Tal','Rückkehr'], tip:'Juni–September.' },
  // ── Ozean ───────────────────────────────────────────────────────
  'padi-ow':{ title:'Tauchen lernen: PADI Open Water', where:'Phuket',
    short:'International anerkanntes Zertifikat in vier Tagen. Die ersten Tauchgänge vor den Racha-Inseln.',
    about:'Der Kurs PADI Open Water: Theorie, Pool und vier Freiwassertauchgänge vom Boot. Das Zertifikat gilt weltweit und erlaubt Tauchgänge bis 18 Meter. Drei Nächte im Hotel nahe der Tauchbasis sind inklusive. Vor dem Kurs füllen Sie einen medizinischen Fragebogen aus; nach dem letzten Tauchgang dürfen Sie 18 Stunden nicht fliegen.',
    plan:['Theorie und Pool','Pool und erste Tauchgänge','Tauchgänge vor den Racha-Inseln und Zertifikat'], tip:'November–April; von Mai bis Oktober Wellengang und Absagen.' },
  'similan-dive':{ title:'Tauchsafari zu den Similan-Inseln', where:'Khao Lak',
    short:'Das bekannteste Tauchrevier Thailands: Koh Bon, Koh Tachai, Richelieu Rock – vier Tage an Bord.',
    about:'Die Similan-Inseln sind ein Nationalpark und das wichtigste Tauchgebiet des Landes: Mantas und Walhaie von Februar bis April, die Riffe von Koh Bon und Koh Tachai, der Richelieu Rock. Vier Tage auf einem Liveaboard, rund 14 Tauchgänge, Kabine und Verpflegung. Angeln ist im Park verboten – dies ist ein Programm für Taucher, nicht für Angler.',
    plan:['Abfahrt ab Tap Lamu und erste Tauchgänge','Koh Bon, Koh Tachai, Richelieu Rock','Letzte Tauchgänge und Rückfahrt'],
    tip:'Der Park ist etwa vom 15. Oktober bis 15. Mai geöffnet. Wir empfehlen ein Advanced-Zertifikat und mindestens 20 Tauchgänge.' },
  'freediving':{ title:'Freediving für Einsteiger auf Koh Tao', where:'Koh Tao',
    short:'Atmung, Atemanhalten und die ersten 10–20 Meter mit einem Atemzug.',
    about:'Koh Tao ist eines der Freediving-Zentren Asiens. Einsteigerkurs (AIDA, SSI oder Molchanovs): Theorie, Atemanhalten im Pool, Tauchgänge am Seil im Meer und Zertifikat. Die wichtigste Regel: immer mit Buddy und Instruktor.',
    plan:['Theorie und Pool','Meer: Tauchgänge am Seil','Abschlusstauchgänge und Zertifikat'], tip:'März–September; der November ist im Golf von Thailand der ungünstigste Monat.' },
  'surf-camp':{ title:'Surfcamp auf Bali', where:'Bali',
    short:'Surflehrer, Board und Videoanalyse – aufstehen werden Sie schon in den ersten Tagen.',
    about:'Eine Woche im Surfcamp: 5–10 Unterrichtseinheiten, Board, Transfer zu den Spots, Videoanalyse und Yoga. Die Saison bestimmt die Küste: Von April bis Oktober sind die Bedingungen im Westen und auf der Bukit-Halbinsel gut, von November bis März im Osten. Einsteiger können das ganze Jahr surfen.',
    plan:['Sicherheit und erste Versuche im Weißwasser','Unterricht und Videoanalyse','Freies Surfen mit Surflehrer in der Nähe'],
    tip:'Im März ist auf Bali der Tag der Stille (Nyepi) – die Insel ist dann 24 Stunden lang geschlossen.' },
  'kite':{ title:'Kitesurfen lernen', where:'Hua Hin und Pranburi',
    short:'IKO-Zertifikat und verlässlicher Wind von November bis April.',
    about:'IKO-Kurs: 9–12 Stunden mit Kitelehrer, Helm mit Funk, komplette Ausrüstung und Zertifikat. Hua Hin und Pranburi sind in der Zeit des Nordostmonsuns die besten Kitespots am Golf. Wind lässt sich nicht bestellen – wir planen zwei Reservetage ein.',
    plan:['Kitesteuerung am Strand','Bodydrag und erste Starts','Fahren und Zertifikat'], tip:'November–April; im Sommer wird auf Phuket gekitet.' },
  'sailing':{ title:'Skipper-Segelkurs', where:'Phuket',
    short:'Praxis in der Andamanensee und ein internationales Zertifikat.',
    about:'Eine Woche auf der Yacht mit Ausbilder (bis zu fünf Teilnehmer an Bord): Navigation, An- und Ablegen, Nachtfahrten und Segelführung. Am Ende steht ein internationales Skipper-Zertifikat, je nach Schule. Um später selbst eine Yacht zu chartern, brauchen Sie zusätzlich ein Funkzeugnis – wir erklären, wie Sie es bekommen.',
    plan:['Theorie und Manövertraining','Törns zwischen den Inseln und Nachtfahrt','Prüfung und Zertifikat'], tip:'November–April.' },
  'yacht-week':{ title:'Yachtwoche mit Freunden', where:'Andamanensee',
    short:'Katamaran, Skipper, Koch und die Inseln der Phang-Nga-Bucht. Preis pro Person bei acht Gästen.',
    about:'Eine Woche auf einem 45–50-Fuß-Segelkatamaran mit Skipper und Koch: die Bucht von Phang Nga, die Inseln vor Krabi und Phi Phi, Angeln vom Boot außerhalb der Parks, Schnorcheln und Abendessen an Deck. Der Preis ist für acht Gäste kalkuliert; Treibstoff und Proviant werden nach Verbrauch abgerechnet.',
    plan:['Einschiffung und Phang-Nga-Bucht','Inseln vor Krabi und Phi Phi','Rückkehr'],
    tip:'November–April; die Maya Bay ist vom 1. August bis 30. September gesperrt.' },
  'wakeboard':{ title:'Wakeboard-Camp in Pattaya', where:'Pattaya',
    short:'Cable-Wakepark mit Trainer: von den ersten Starts bis zu den ersten Tricks.',
    about:'Fünf Tage im Cable-Wakepark: Trainer, Ausrüstung und Videoanalyse. An der Seilbahn lernt man leichter als hinter dem Boot – schon am ersten Tag stehen Sie auf dem Board.',
    plan:['Starts und Grundhaltung','Kurven, Sprünge und Videoanalyse','Erste Tricks'], tip:'November–Februar.' },
  'maldives-surf':{ title:'Surf-Charter auf den Malediven', where:'Malediven',
    short:'Boot, erstklassige Riffwellen und Angeln bei Sonnenuntergang.',
    about:'Eine Woche auf einem Surfboot mit Guide: Wellen über Riffen, die von den Resorts aus nicht erreichbar sind, Vollpension und Angeln bei Sonnenuntergang. Ein Format für geübte Surfer – die Riffe sind flach.',
    plan:['Einschiffung in Malé','Surfen an den Riffen des Atolls','Rückkehr'], tip:'März–Oktober; die größten Wellen gibt es von Juni bis August.' },
  // ── Golf & Padel ────────────────────────────────────────────────
  'golf-phuket':{ title:'Golfwoche auf Phuket', where:'Phuket',
    short:'Die fünf besten Plätze der Insel, Caddies, Hotel und Transfers mit Golfgepäck.',
    about:'Fünf Runden auf den besten Plätzen Phukets – Blue Canyon, Red Mountain, Laguna und weiteren –, ein Caddie auf jedem Platz (auf Phuket Pflicht), ein 4★-Hotel und Transfers mit Golfbags. Begehrte Startzeiten von Dezember bis März buchen wir im Voraus.',
    plan:['Anreise und Hotel','Fünf Runden auf verschiedenen Plätzen','Erholung oder ein Angeltag'],
    tip:'November–April; von Mai bis Oktober ist das Greenfee 20–40 % günstiger.' },
  'golf-school':{ title:'Golf für Einsteiger', where:'Hua Hin',
    short:'Täglich Unterricht bei einem PGA-Pro und zum Ende der Woche die erste Runde auf dem Platz.',
    about:'Hua Hin ist der klassische Golfort Thailands. Fünf Tage Unterricht bei einem zertifizierten Pro: Stand, Schwung, kurzes Spiel, Regeln und Etikette – und zum Schluss Ihre ersten neun Löcher.',
    plan:['Stand, Schwung, Driving Range','Kurzes Spiel und Putten','Die ersten Löcher auf dem Platz'], tip:'November–April.' },
  'padel-camp':{ title:'Padel-Camp in Dubai', where:'Dubai',
    short:'Eine der am schnellsten wachsenden Sportarten: Technik, Taktik und ein Turnier in der Gruppe.',
    about:'Das Interesse an Padel ist in den VAE in den letzten Jahren um ein Vielfaches gewachsen, und Dubai ist zu einer seiner Hauptstädte geworden. Fünf Tage mit Trainer: 10–15 Stunden Technik und Taktik, Spiele mit Partnern auf Ihrem Niveau und zum Schluss ein Turnier.',
    plan:['Einschätzung des Niveaus','Technik, Taktik und Spiele','Turnier'],
    tip:'November–März; im Sommer nur Hallenplätze. Die Termine des Ramadan berücksichtigen wir.' },
  'tennis-camp':{ title:'Tenniscamp auf Mallorca', where:'Mallorca',
    short:'Trainer der Akademie, Videoanalyse und Matchsätze.',
    about:'Eine Woche im Erwachsenenprogramm einer Tennisakademie auf Mallorca: 15–20 Stunden Tennis, Athletiktraining, Videoanalyse der Schläge und Unterkunft auf dem Gelände der Akademie.',
    plan:['Einschätzung und Videoanalyse','Training und Matchsätze','Abschlussmatches'],
    tip:'März–Juni und September–November. Mit EU- oder Schweizer Pass ohne Visum; für andere Pässe kann ein Schengen-Visum nötig sein.' },
  'golf-scotland':{ title:'Golf in Schottland: St Andrews', where:'St Andrews',
    short:'Die Heimat des Golfs: Old Course und klassische Links.',
    about:'Eine Woche in der Heimat des Golfs: die Chance auf eine Runde auf dem Old Course über die tägliche Verlosung (Ballot) – oder ein teureres Paket mit garantierter Startzeit –, dazu Kingsbarns, Carnoustie und weitere Links, Hotel und Fahrer. Für den Old Course brauchen Herren ein Handicap von höchstens 24.',
    plan:['Anreise nach St Andrews','Runden auf den Links und Verlosung für den Old Course','Abreise'],
    tip:'Mai–September. Für Großbritannien brauchen EU- und Schweizer Bürger eine ETA, andere Pässe teils ein Visum – wir helfen dabei.' },
  'padel-bali':{ title:'Padel und Wellness auf Bali', where:'Bali',
    short:'Morgens Padel, tagsüber Surfen, abends Spa.',
    about:'Eine Woche, in der Sport und Erholung im richtigen Verhältnis stehen: früh am Morgen Padel mit Trainer, tagsüber Surfen oder Pool, abends Massage – und eine Villa in Canggu.',
    plan:['Check-in und erstes Spiel','Padel, Surfen und Spa','Abreise'], tip:'April–Oktober.' },
  // ── Ästhetik & Stil ─────────────────────────────────────────────
  'hair':{ title:'Haartransplantation in Istanbul', where:'Istanbul',
    short:'Akkreditierte Klinik, Beratung anhand von Fotos vor der Reise, Hotel und Begleitung.',
    about:'Die Türkei ist das Weltzentrum der Haartransplantation – und gerade deshalb gibt es hier viele „Fließband-Kliniken“, in denen Techniker operieren. Wir arbeiten nur mit Kliniken, in denen ein Arzt die Entnahme und die Kanalöffnung durchführt und die Zahl der Grafts dokumentiert wird. Beratung anhand von Fotos, Eingriff mit FUE oder DHI, PRP, Medikamente, 2–3 Nächte im Hotel und Transfers.',
    plan:['Beratung und Plan anhand von Fotos','Empfang, Laborwerte und Markierung','Eingriff','Verbandswechsel, Kontrolle und Abflug'],
    tip:'Oktober–April. Eine normale Reiseversicherung deckt geplante Eingriffe nicht ab.' },
  'dental':{ title:'Zahnmedizin in Bangkok: Implantate und Veneers', where:'Bangkok',
    short:'Internationale Kliniken, Behandlungsplan vor dem Abflug, Hotel in der Nähe. Preis pro Implantat.',
    about:'Bangkok ist eines der wichtigsten Zentren des Zahntourismus. Implantat mit Abutment und Krone (koreanische Systeme oder Straumann/Nobel), Veneers aus Keramik. Den Behandlungsplan erstellt die Klinik anhand Ihrer Röntgenbilder schon vor dem Abflug. Implantate erfordern zwei Reisen im Abstand von 3–6 Monaten, Veneers etwa eine Woche.',
    plan:['Röntgenbilder und Behandlungsplan vor der Reise','CT und Setzen der Implantate','Kronen nach 3–6 Monaten','Garantie und Nachkontrolle'],
    tip:'Wir achten darauf, dass gesunde Zähne nicht unnötig beschliffen werden.' },
  'lasik':{ title:'Laser-Augenkorrektur', where:'Bangkok',
    short:'Diagnostik, Eingriff und Nachkontrolle. Am Tag danach an den Strand – mit Sonnenbrille.',
    about:'Femto-LASIK oder SMILE in einer spezialisierten Augenklinik: vollständige Diagnostik, Eingriff an beiden Augen, Medikamente und Kontrollen am ersten und siebten Tag. Nicht für jeden geeignet – die Entscheidung trifft der Arzt nach der Untersuchung.',
    plan:['Diagnostik','Eingriff','Kontrolle und Erholung'], tip:'Pool und Meer erst nach 2–4 Wochen.' },
  'skin-seoul':{ title:'Männerkosmetik in Seoul', where:'Seoul',
    short:'Haut, Pigmentierung und Pflege: koreanische Protokolle für Männer.',
    about:'Fünf Tage in Kliniken in Seoul: dermatologische Beratung, gerätegestützte Behandlungen je nach Indikation, Pflege und Regeneration. Wir arbeiten mit registrierten Agenturen – Ausländern werden in Korea oft höhere Preise genannt, das kontrollieren wir.',
    plan:['Beratung und Plan','Behandlungen','Kontrolle und Empfehlungen'], tip:'Oktober–April.' },
  'style':{ title:'Stil und Auftritt in Dubai', where:'Dubai',
    short:'Stylist, Barber und eine Garderobe, die zu Ihrem Lebensrhythmus passt.',
    about:'Zwei Tage mit einem Stylisten: Analyse Ihrer Garderobe, ein Shoppingtag in den besten Kaufhäusern Dubais, Barber und Schneider. Die Kleidung kaufen Sie selbst – eine Provision auf Einkäufe nehmen wir nicht. Touristen können sich die Mehrwertsteuer von 5 % erstatten lassen.',
    plan:['Stil-Briefing und Barber','Shopping und Anproben'], tip:'November–März; das Dubai Shopping Festival findet von Dezember bis Januar statt.' },
  // ── Ernährung & Supplements ─────────────────────────────────────
  'nutritionist':{ title:'Ernährungsberatung nach Laborwerten', where:'Online',
    short:'Auswertung der Laborwerte, Ernährungsplan und vier Wochen Begleitung.',
    about:'Fragebogen, Laborüberweisung, Auswertung der Ergebnisse mit einem Ernährungsmediziner, ein Ernährungsplan für Ihre Ziele und zwei Kontrolltermine. Diagnosen stellt nur ein Arzt – deshalb arbeiten wir mit zugelassenen Fachleuten.',
    plan:['Fragebogen und Laborwerte','Auswertung und Ernährungsplan','Zwei Kontrolltermine'] },
  'erkak-stack':{ title:'ERKAK-Protokoll 90 Tage', where:'Weltweiter Versand',
    short:'D3+K2, Zink, Magnesium und Omega-3 mit Analysezertifikat der Charge. Kontrollwerte nach 90 Tagen.',
    about:'Ein Set aus vier ERKAK-Produkten für den vollen Zyklus bis zur Kontrollmessung: Vitamin D3 mit K2, Zink mit Selen, Magnesium und Omega-3. Für jede Dose liegt das Analysezertifikat der Charge vor. Nahrungsergänzungsmittel, kein Arzneimittel.',
    plan:['Ausgangswerte im Labor','90 Tage Protokoll','Kontrollwerte im Labor'] },
  'chef-prep':{ title:'Privatkoch und Ernährung nach Plan', where:'Phuket',
    short:'Mahlzeiten passend zu Ihren Zielen und Ihrem Training, frisch vom Privatkoch. Preis für zwei Personen, Lebensmittel inklusive.',
    about:'Sieben Tage mit einem Privatkoch in der Villa: Menü nach Kalorien und Makronährstoffen, Einkauf, Frühstück und Abendessen, Küchenreinigung. Alternativ: tägliche Lieferung fertiger Mahlzeiten. Alle Allergien bitte vor Beginn schriftlich mitteilen.',
    plan:['Briefing und Menü','Sieben Tage Ernährung nach Plan','Rezepte zum Mitnehmen'] },
  'shilajit-tour':{ title:'Zum Shilajit in die Tschimgan-Berge', where:'Usbekistan',
    short:'Woher das Shilajit von ERKAK kommt: Berge, Sammler und Labor.',
    about:'Drei Tage im westlichen Tian Shan: mit einem Guide zu den Fundorten des Shilajit (Mumijo), Begegnung mit den Sammlern, Besuch im Labor, in dem der Rohstoff gereinigt und geprüft wird, und ein Abend mit Plov in den Bergen.',
    plan:['Taschkent und die Tschimgan-Berge','Fundorte und Sammler','Labor und Rückkehr'], tip:'Mai–Oktober.' },
  // ── Vater & Sohn ────────────────────────────────────────────────
  'father-son-thai':{ title:'Vater und Sohn: Angeln und Muay Thai', where:'Phuket',
    short:'Morgens der Ring, tagsüber das Meer. Für Söhne ab 10 Jahren. Preis für zwei Personen.',
    about:'Fünf Tage, die Ihr Sohn nicht vergessen wird: fünf Muay-Thai-Trainings zu zweit mit Trainer, zwei Angeltage auf einem privaten Boot, Hotel und Transfers. Kindergruppen in den Camps gibt es ab 6–8 Jahren, an Bord Schwimmwesten für Kinder.',
    plan:['Anreise und erstes Training','Training und Angeln','Angeln und Abschlusstraining'], tip:'November–April: ruhige See.' },
  'family-krabi':{ title:'Familienabenteuer in Krabi', where:'Krabi',
    short:'Felsen, Kajaks, Inseln und Elefanten in einem ethischen Schutzgebiet. Preis pro Person.',
    about:'Eine Woche für die ganze Familie: mit dem Kajak durch Mangrovenlabyrinthe, Inseln mit dem privaten Boot, ein ethisches Elefantenschutzgebiet ohne Reiten, die Strände von Railay und ein Resort mit Kinderclub.',
    plan:['Resort und Strände','Kajaks, Inseln und Schutzgebiet','Erholung'], tip:'November–April; die Maya Bay ist im August und September gesperrt.' },
  'teen-camp':{ title:'Sportcamp für Jugendliche', where:'Phuket',
    short:'Sport und Englisch, während die Eltern in der Nähe Urlaub machen.',
    about:'Zwei Wochen für Jugendliche von 12 bis 17 Jahren: Muay Thai, Schwimmen, Surfen, täglich Englischunterricht und Betreuer. Fertige internationale Camps mit Unterkunft gibt es auf Phuket nur wenige – wir stellen das Programm auf Anfrage zusammen, mit überprüftem Personal und schriftlicher Einwilligung der Eltern.',
    plan:['Sport und Englisch','Turnier, Ausflüge und Abschluss'], tip:'Dezember–Januar und in den Frühjahrsferien.' },
  'father-son-nepal':{ title:'Vater und Sohn in den Bergen Nepals', where:'Nepal',
    short:'Trekking zum Poon Hill oder zum Annapurna-Basislager – für Söhne ab 14 Jahren.',
    about:'Zehn Tage zu zweit im Himalaya: Trekking zum Poon Hill (3210 m) – die sanfte Variante für Jugendliche – oder zum Annapurna-Basislager (4130 m) für Trainierte. Guide, Träger, Lodges und Genehmigungen sind inklusive. Preis pro Person.',
    plan:['Kathmandu und Pokhara','Trekking','Rückkehr und Kathmandu'], tip:'März–Mai und Oktober–November.' },
  // ── Firmen & Freunde ────────────────────────────────────────────
  'corp-retreat':{ title:'Retreat für Führungsteams', where:'Phuket',
    short:'Morgens Strategiesitzung, tagsüber Sport und Meer. Preis pro Teilnehmer.',
    about:'Vier Tage für das Managementteam: morgens Strategiesitzungen mit Facilitator, tagsüber Yacht, Angeln oder Muay Thai, abends gemeinsame Dinner. 5★-Hotel mit Tagungsräumen, Unterlagen und Rechnung für das Unternehmen.',
    plan:['Anreise und Abendessen','Strategiesitzungen und Aktivitäten','Ergebnisse und Abreise'], tip:'November–April.' },
  'founders':{ title:'Retreat für Gründer', where:'Bali',
    short:'Eine kleine Gruppe von Unternehmern: Strategie, Gesundheit und Stille.',
    about:'Fünf Tage in einer kleinen Gruppe von Gründern: Strategiesitzungen, gegenseitige Fallbesprechungen, Training, Schlaf und Stille. Villa, Facilitator und ein Programm, nach dem man mit einem Plan zurückkehrt.',
    plan:['Kennenlernen und Ziele','Sitzungen und Übungen','Pläne und Abschluss'], tip:'April–Oktober; das Visum bei Ankunft berechtigt nicht zum Arbeiten.' },
  'regatta':{ title:'Firmenregatta', where:'Phuket',
    short:'Teams auf baugleichen Yachten, Schiedsrichter, Pokale und Dinner. Preis pro Teilnehmer.',
    about:'Zwei Tage Segelregatta für Ihr Team: baugleiche Yachten mit Skippern, Wettfahrtleitung und Ergebnislisten, Pokale und ein Dinner mit Siegerehrung. In der ersten Dezemberwoche findet auf Phuket die King’s Cup Regatta statt – Hotels für diese Zeit buchen wir früh.',
    plan:['Einweisung und Trainingsrennen','Regatta und Siegerehrung'], tip:'November–April.' },
  'bachelor':{ title:'Premium-Junggesellenabschied', where:'Phuket oder Dubai',
    short:'Yacht, Angeln, Muay Thai und Dinner vom Koch. Ohne Klischees. Preis pro Teilnehmer.',
    about:'Drei Tage, von denen man noch auf der Hochzeit erzählt: Villa oder 5★-Hotel, ein Tag auf der Yacht mit Angeln, Muay-Thai-Training für die ganze Gruppe und ein Dinner vom Koch. Die Regeln sind einfach: In Thailand sind E-Zigaretten verboten, in den VAE gilt null Toleranz bei Drogen.',
    plan:['Check-in und Abendessen','Yacht und Angeln','Muay Thai und letzter Abend'] }
};

export const destinations = {
  phuket:{ name:'Phuket', title:'Phuket für Männer: Angeln, Muay Thai, Golf und Ozean',
    intro:'Phuket ist die Hauptbasis von ERKAK und für aktive Männerreisen die erste Wahl in Thailand. Trophäenangeln vor den Racha-Inseln, Muay-Thai-Camps an der Soi Ta-iad, fünf Golfplätze, Tauchen, Yachten und Regeneration – alles innerhalb einer Autostunde.',
    season:'November bis April ist Trockenzeit: ruhige See, die höchsten Preise von Dezember bis Februar. Mai bis Oktober ist Monsunzeit: Weite Ausfahrten aufs Meer fallen oft aus, dafür sind Camps und Golfplätze günstiger.',
    access:'Direktflüge aus Europa, dem Golf und Asien; Umstieg in Dubai, Doha, Istanbul oder Bangkok. Staatsangehörige Deutschlands, Österreichs und der Schweiz reisen 30 Tage visumfrei ein; für andere Pässe prüfen wir die Regeln und helfen beim Visum.' },
  bangkok:{ name:'Bangkok', title:'Bangkok für Männer: Check-ups, Muay Thai und Süßwasser-Giganten',
    intro:'Bangkok ist eines der weltweiten Zentren des Medizintourismus und die Hauptstadt des Muay Thai. Hier macht man einen Executive Check-up an einem Tag, kümmert sich um Zähne und Augen, trainiert in den Gyms der Legenden und angelt Mekong-Riesenwelse eine Stunde von der Stadt entfernt.',
    season:'Beste Zeit: November bis Februar. Von März bis Mai ist es sehr heiß, von Juni bis Oktober regnet es – medizinische Programme und Süßwasserangeln gibt es aber das ganze Jahr.',
    access:'Der Flughafen Suvarnabhumi ist ein großes Drehkreuz mit Direktflügen aus Europa, dem Golf und Asien; Umstieg etwa in Dubai, Doha oder Istanbul. Zu den Krankenhäusern sind es 40–60 Minuten.' },
  samui:{ name:'Koh Samui und Koh Tao', title:'Koh Samui: Detox, Muay Thai in der Villa und Freediving auf Koh Tao',
    intro:'Koh Samui ist die Insel der klassischen Wellness-Retreats, der Villen mit Blick auf den Golf von Thailand und des ruhigen Rhythmus. Gleich nebenan liegt Koh Tao, eines der Zentren für Freediving und Tauchen in Asien.',
    season:'Januar bis September ist die beste Zeit. Oktober bis Dezember ist Regenzeit im Golf von Thailand.',
    access:'Der Flughafen Koh Samui wird aus Bangkok und Singapur angeflogen; nach Koh Tao sind es 1,5–2 Stunden mit der Fähre.' },
  'chiang-mai':{ name:'Chiang Mai', title:'Chiang Mai: Berge, Stille, Massage und Motorradabenteuer',
    intro:'Nordthailand, das sind kühle Berge, Meditationszentren, Massage der alten Schule, Bergtrails zum Laufen und der legendäre Mae-Hong-Son-Loop für Motorradfahrer.',
    season:'November bis Januar: kühl und klar. Von Februar bis April liegt im Norden Rauch von Feldbränden in der Luft – diese Monate empfehlen wir nicht. Juni bis Oktober: Regenzeit.',
    access:'Direktflüge ab Bangkok (etwa eine Stunde) und von asiatischen Drehkreuzen.' },
  krabi:{ name:'Krabi und Khao Lak', title:'Krabi und Khao Lak: Kletterfelsen, Similans, Dschungel und Inseln',
    intro:'Die Kalkfelsen von Railay, Tauchsafaris zu den Similan-Inseln ab Khao Lak, der Cheow-Lan-See im Dschungel von Khao Sok und ruhige Inseln für Familien – die schönste Natur der Andamanenküste.',
    season:'November–April. Der Similan-Nationalpark ist etwa vom 15. Oktober bis 15. Mai geöffnet.',
    access:'Flughäfen Krabi und Phuket; nach Khao Lak etwa eine Stunde vom Flughafen Phuket.' },
  gulf:{ name:'Hua Hin und Pattaya', title:'Hua Hin und Pattaya: Kiten, Golf und Wakeboarden nahe Bangkok',
    intro:'Die Küste am Golf von Thailand, zwei bis drei Stunden von Bangkok: die Kitespots von Pranburi, die klassischen Golfplätze von Hua Hin, Wakeparks und Angeln vor den Inseln von Pattaya.',
    season:'November bis April: trocken und windig, die beste Zeit für Kiten und Golf.',
    access:'Transfer ab Bangkok 2–3 Stunden; bei Pattaya liegt der Flughafen U-Tapao.' },
  bali:{ name:'Bali', title:'Bali: Surfen, Retreats ohne Alkohol, Spa und Gründer-Retreats',
    intro:'Bali ist die Insel des Surfens, der Spas und der Retreats: Surfcamps an der Westküste, Atemarbeit und Spa in Ubud, Retreats ohne Alkohol und für Männer, Padel und eine starke Gründer-Community.',
    season:'April bis Oktober ist Trockenzeit. Im März ist der Tag der Stille (Nyepi): Die Insel ist 24 Stunden lang geschlossen.',
    access:'Flughafen Denpasar; Visum bei Ankunft und Touristenabgabe.' },
  dubai:{ name:'Dubai', title:'Dubai: Biohacking, Padel, Kraft 40+ und Stil',
    intro:'Dubai ist die Stadt der lizenzierten Regenerationskliniken, des Padel und des Service auf höchstem Niveau: Biohacking unter ärztlicher Aufsicht, Kraftprogramme für Männer ab 40, Padel-Camps und Stil.',
    season:'November–März. Im Sommer nur drinnen. Die Termine des Ramadan berücksichtigen wir.',
    access:'Direktflüge aus den meisten Metropolen der Welt; Staatsangehörige Deutschlands, Österreichs und der Schweiz reisen ohne Visum ein.' },
  caucasus:{ name:'Kaukasus', title:'Kaukasus: Elbrus, Höhentraining und Skifahren',
    intro:'Der höchste Punkt Europas, das olympische Trainingszentrum Zaghkadsor und Freeride in Gudauri – der Kaukasus für alle, die die Höhe lieben.',
    season:'Juni bis September: Besteigungen und Trainingslager; Dezember bis März: Skifahren.',
    access:'Mineralnyje Wody und Naltschik für den Elbrus, Jerewan für Zaghkadsor, Tiflis für Gudauri.' },
  'central-asia':{ name:'Zentralasien', title:'Zentralasien: Boxen in Almaty und die Berge Usbekistans',
    intro:'Die Heimat von ERKAK: die kasachische Boxschule in Almaty, die Berge des westlichen Tian Shan und die Fundorte des Shilajit bei Tschimgan.',
    season:'Mai bis Oktober in den Bergen; Boxen im Frühling und Herbst.',
    access:'Direktflüge nach Almaty und Taschkent aus Dubai, Istanbul und einigen europäischen Städten.' },
  russia:{ name:'Altai und Kamtschatka', title:'Altai und Kamtschatka: Männer-Retreats, Wanderritte und Vulkane',
    intro:'Die Wildnis Russlands: Männer-Retreats und Wanderritte im Altai, die Vulkane und das Tal der Geysire auf Kamtschatka, dazu eine echte Banja.',
    season:'Juli–September; Banja: Oktober–März.',
    access:'Barnaul oder Gorno-Altaisk; Petropawlowsk-Kamtschatski. Für ausländische Gäste: Visa- und Mastercard-Karten funktionieren in Russland nicht.' },
  'east-africa':{ name:'Ostafrika', title:'Ostafrika: Kilimandscharo, Safari und Laufen in Iten',
    intro:'Das Dach Afrikas, die Große Migration und die Stadt der Laufweltmeister – die drei großen Männerabenteuer des Kontinents.',
    season:'Januar–März und Juni–Oktober; die Migration in der Masai Mara von Juli bis Oktober.',
    access:'Flughäfen Kilimandscharo und Nairobi; elektronische Einreisegenehmigung (eTA) für Kenia und E-Visum für Tansania.' },
  europe:{ name:'Europa', title:'Europa: Golf in Schottland, Tennis, Radcamps und Fasten',
    intro:'Die europäischen Klassiker: St Andrews, Tennisakademie und Radtrainingslager auf Mallorca, Fastenkliniken in Deutschland und Österreich.',
    season:'Frühling und Herbst; Schottland: Mai–September.',
    access:'Im Schengen-Raum kein Visum für EU- und Schweizer Bürger; für Großbritannien je nach Pass die elektronische Einreisegenehmigung ETA oder ein Visum.' },
  'east-asia':{ name:'Japan und Korea', title:'Japan und Korea: Onsen, Check-ups und Hautpflege',
    intro:'Japanische Ryokans mit heißen Quellen, Check-ups in den führenden Krankenhäusern Seouls und koreanische Hautpflegeprotokolle.',
    season:'Frühling und Herbst; Onsen von November bis März.',
    access:'Einreiseregeln für Japan und Korea hängen vom Pass ab – wir prüfen sie für Sie.' },
  nepal:{ name:'Nepal' }, india:{ name:'Indien' }, jordan:{ name:'Jordanien' }, maldives:{ name:'Malediven' }, istanbul:{ name:'Istanbul' }, online:{ name:'Online' }
};
