// ERKAK · Deutsch · Bereich „Angeln in Thailand“: Landingpage, Touren, Spots, Kalender, Quiz.
export default {
  metaTitle:'Angeln auf Phuket & Andamanensee: Touren und Concierge | ERKAK',
  metaDesc:'Trophäenangeln auf Phuket, in Khao Lak und Bangkok: Segelfisch, Marlin, GT, Thun, Mekong-Riesenwels. Private Boote, lizenzierter Guide, Concierge. Ab 4.900 THB.',
  chip:'Saison eröffnet · Andamanensee',
  title:'Trophäenangeln in Thailand. *Legal. Privat. Alles aus einer Hand.*',
  lede:'Segelfisch, Marlin, GT und Thunfisch in der Andamanensee. Private Boote, ein lizenzierter Guide und ein Concierge, der alles regelt.',
  proof:[['0','Angeltouren in Nationalparks'],['≤ 6','Angler pro Gruppe'],['30 %','Anzahlung'],['24/7','Concierge erreichbar']],
  subnav:[['Touren','tours'],['Für wen','who'],['Concierge','concierge'],['Karte','map'],['Saison','season'],['Fragen','faq']],
  pains:{ kicker:'Warum Angelausflüge enttäuschen', title:'Vier Wege, einen Tag auf dem Meer zu verlieren. *Wir haben jeden ausgeschlossen.*', items:[
    ['Ausflug mit 40 Personen','Ein alter Kahn, Gedränge, eine Schnur am Stock – und zwanzig Minuten Angeln zwischen Imbiss und Schnorcheln.','Private Boote und Kleingruppen mit höchstens sechs Anglern. Die Zeit gehört dem Angeln.'],
    ['Bußgeld für Angeln im Nationalpark','Angeln an den Similan-Inseln und bei Phi Phi wird bis heute verkauft, obwohl es gesetzlich verboten ist: bis zu 500.000 THB Bußgeld und strafrechtliche Folgen.','Nur erlaubte Spots: Schelf, FADs, Racha-Inseln. Lizenzierter Veranstalter und lizenzierter thailändischer Guide an Bord.'],
    ['Der Kapitän versteht nicht, was Sie wollen','Gesten, Übersetzungs-App und eine Ausfahrt dorthin, „wo man immer hinfährt“ – statt zu Ihrem Fisch.','Ein Concierge für alles, erreichbar vor, während und nach der Ausfahrt. Das Briefing mit dem Kapitän bereiten wir vorab vor.'],
    ['Leere Ausfahrt außerhalb der Saison','Ihnen wird Segelfisch in einem Monat verkauft, in dem keiner da ist – bei Wind, der kein Boot über die Riffe hinauslässt.','Datum und Format wählen wir nach Beißkalender, Wetterprognose und Mondphase. Wir sagen offen, wenn Ihr Fisch gerade keine Saison hat.'],
    ['Das Gerät hält der Trophäe nicht stand','Müde Schnur, rostige Haken und eine Rolle, die beim ersten 20-kg-Fisch aufgibt.','Shimano Stella und Daiwa Saltiga, PE-Schnüre 6–10, frische Haken bei jeder Pro-Ausfahrt.'],
    ['Unsichere Bezahlung','Vorkasse „direkt aufs Konto des Kapitäns“ – ohne Vertrag und ohne Beleg.','Internationale Karten, Banküberweisung oder Firmenrechnung, USDT, Bargeld (THB/USD) vor Ort. 30 % Anzahlung, schriftlicher Vertrag.'] ] },
  who:{ kicker:'Für wen', title:'Sagen Sie uns, wer Sie sind – *wir zeigen Ihr Format*' },
  segments:[
    { id:'family', label:'Familie und Einsteiger', title:'Das erste richtige Angelerlebnis – ohne Seekrankheit, Gedränge und Abzocke',
      quote:'„Wir möchten mit den Kindern angeln, fürchten aber, auf einem alten Kahn mit vierzig Touristen und einer Schnur am Stock zu landen.“',
      points:['Privates Boot nur für Ihre Familie, 5 Stunden auf dem Wasser','Ruhiges Wasser bei Racha Yai, Schwimmwesten für Kinder','Der Kapitän richtet das Gerät ein und hilft beim Drill','Der Fang wird an Bord zubereitet – Sashimi und Grill'], picks:['family-half','first-strike','bangkok-monsters'] },
    { id:'angler', label:'Erfahrener Angler', title:'Popping und Jigging auf GT und Thun an den richtigen Spots – nicht dort, wo alle sind',
      quote:'„Ausflugsboote können kein Popping. Ich brauche einen Kapitän, der Bänke, Strömungen und Mondphasen kennt.“',
      points:['Schnelles Speedboat: mehr Zeit am Spot, weniger auf der Anfahrt','Gerät auf Stella- und Saltiga-Niveau, PE 6–10, Stinger','Spots auf dem Schelf und an FADs – außerhalb der Nationalparks, ohne Bußgeldrisiko','Plan nach Gezeiten, Mond und Wind für Ihren Termin'], picks:['pro-gt','bigame-day','khaosok-jungle'] },
    { id:'trophy', label:'Trophäenjäger', title:'Segelfisch, Marlin, Hundezahn-Thun – eine Expedition für ein Ziel',
      quote:'„Ich fliege um die halbe Welt für einen bestimmten Fisch. Ich brauche keinen Ausflug, ich brauche eine Chance.“',
      points:['Sportfischerboot mit Cockpit und Kampfstuhl','Übernachtung auf dem Schelf: Morgen- und Abendbeißzeit direkt am Spot','Zeitfenster nach Saison und Prognose, kostenlose Verschiebung','Catch & Release nach IGFA-Standard, Vermessung und Zertifikat'], picks:['overnight-shelf','expedition-khaolak','stingray'] },
    { id:'corp', label:'Unternehmen', title:'Turnier mit 3–5 Booten, Preise, Dinner und Video – mit einem einzigen Vertrag',
      quote:'„Ich will zwölf Geschäftspartner so ausführen, dass sie noch ein Jahr später davon erzählen. Und ohne mich um irgendetwas kümmern zu müssen.“',
      points:['Flotte aus 3–5 baugleichen Booten und ein Turnierrichter','Pokale, Kategorien, Moderator, Dinner in der Villa','Eventvideo innerhalb von 48 Stunden','Dokumente, Firmenrechnung, Vertrag'], picks:['tournament','bigame-day','signature-week'] },
    { id:'vip', label:'VIP', title:'Eine Person regelt alles: Villa, Yacht, Koch, Transfers',
      quote:'„Ich will eine Woche Spitzenangeln in Asien – ohne einen einzigen Anruf und ohne Wartezeiten.“',
      points:['Persönlicher Concierge rund um die Uhr, vor und während der Reise','Die besten Boote zu Spitzenterminen – eine Saison im Voraus reserviert','Privatkoch, Foto und Drohne, Privatsphäre','Helikopter, Wasserflugzeug, Familienprogramm – auf Anfrage'], picks:['signature-week','bigame-day','overnight-shelf'] }
  ],
  toursBlock:{ kicker:'Touren und Preise', title:'Vom ersten Biss bis zur *Marlin-Expedition*', lede:'Im Preis: Boot, Gerät, Transfer, Verpflegung, Versicherung und lizenzierter Guide. Keine Aufpreise am Pier.',
    filters:[['all','Alle'],['sea','Meer'],['fresh','Süßwasser'],['group','Gruppen'],['vip','VIP']] },
  concierge:{ kicker:'Concierge-Service', title:'Sie angeln. *Alles andere ist unsere Aufgabe.*', lede:'Ein fester Ansprechpartner betreut die ganze Reise – von der Terminwahl bis zur Trophäe.',
    items:[['boat','Boot und Kapitän für Ihr Ziel','Wir vergleichen die Flotte nach Tempo, Gerät und Bewertungen. Spitzentermine reservieren wir frühzeitig.'],['rod','Premium-Gerät','Stella, Saltiga, frische Schnüre. Oder wir bereiten Ihr eigenes Gerät vor.'],['car','Business-Class-Transfers','Abholung am Flughafen, Wagen zum Pier, Fahrer für alle Tage.'],['home','Villa am Meer','Nahe Chalong oder in Khao Lak – damit Sie länger schlafen können.'],['chef','Koch und Menü aus dem Fang','Sashimi an Bord, Abendessen aus Ihrem Fang in der Villa.'],['cam','Foto, Drohne, Film','Kameramann an Bord und Clip innerhalb von 48 Stunden.'],['shield','Versicherung und Dokumente','Geprüfte Boote, Vertrag, Firmenrechnung.'],['star','Programm für die Familie','Spa, Inseln und Natur, während Sie auf dem Meer sind.']],
    sigKicker:'Signature Week · 7 Tage', sigTitle:'Eine Woche Spitzenangeln in Thailand – *ohne einen einzigen Anruf*', sigPoints:['Big Game auf dem Sportfischerboot und eine Nacht auf dem Schelf','Dschungel von Khao Sok und die Rekordseen bei Bangkok','Villa, Koch, Fahrer, Foto und Film','Persönlicher Concierge rund um die Uhr und die besten Boote zur Hochsaison'],
    fee:'Concierge zu jeder Tour – ab 15.000 THB pro Tag. Clubkarte für Überwinterer: fünf Ausfahrten pro Saison mit 15 % Rabatt und Vorrang bei den Terminen.', sigCta:'Wochenprogramm ansehen' },
  mapPage:{ link:'Angelkarte für ganz Thailand →', crumb:'Karte', metaTitle:'Wo man in Thailand angeln darf: Karte der Spots und Verbotszonen | ERKAK', metaDesc:'Angelkarte Thailand: Andamanensee, Golf von Thailand, Bangkok und Khao Sok. Wo Angeln erlaubt ist, welche Nationalparks Bußgelder bedeuten und welche Tour wohin führt.',
    title:'Wo man *in Thailand* angeln darf', lede:'Vier Gebiete, in denen wir angeln, und die Zonen, in denen Angeln gesetzlich verboten ist. Tippen Sie auf ein Gebiet oder einen Spot.',
    regions:{ andaman:['Andamanensee', 'Phuket und Khao Lak: Segelfisch, Marlin, GT und Thunfisch. Saison: November–April.'], gulf:['Golf von Thailand', 'Pattaya und Samui: Barrakuda, Zackenbarsch und Makrele. Auch im Monsun befischbar.'], bangkok:['Bangkok', 'Süßwasser: Mekong-Wels, Karpfen und Rochen über 100 kg. Ganzjährig.'], khaosok:['Khao Sok', 'Cheow-Lan-See im Dschungel: Schlangenkopf, Hampala und Mahseer.'] },
    tourCta:'Tour hierhin: {tour}', rulesTitle:'Regeln, *die Sie schützen*', allTours:'Alle Touren und Preise',
    rules:['In Meeresnationalparks ist Angeln verboten: Similan, Surin, Phi Phi, Ang Thong, Mu Ko Lanta. Bußgelder bis 500.000 THB.', 'Wir fahren nur mit lizenziertem Anbieter hinaus: Das Boot hat eine Genehmigung des Marine Department, ein thailändischer Guide ist an Bord.', 'Im Süßwasser angeln wir in Angelparks und mit lokalen Guides. Große Fische setzen wir zurück.', 'Andamanensee: November–April. Im Monsun (Mai–Oktober) angeln wir im Golf von Thailand und im Süßwasser.'] },
  map:{ kicker:'Wo wir angeln – und wo nie', title:'Die ehrliche Karte *der Andamanensee*', lede:'In Meeresnationalparks ist Angeln gesetzlich verboten. Wir angeln auf dem Schelf, an FADs und bei den Racha-Inseln; Nationalparks laufen wir nur zum Ankern und Schnorcheln an. Wählen Sie einen Punkt auf der Karte.' },
  spots:{
    'racha-yai':{ name:'Racha Yai', run:'30–45 Minuten ab Chalong', fish:'Barrakuda, Makrele, Schnapper, Zackenbarsch', how:'Schleppangeln, Grundangeln, leichtes Jigging', note:'Liegt außerhalb der Nationalparks. Der wichtigste Spot für Familien und Gruppen.' },
    'racha-noi':{ name:'Racha Noi', run:'etwa eine Stunde ab Chalong', fish:'GT, Gelbflossen-Thun, Wahoo, Amberjack, Zackenbarsch', how:'Popping, Vertical Jigging, Schleppangeln', note:'Tiefer und weiter draußen, ein Unterwasserberg im Süden. Der Spot für den Pro Day.' },
    'shelf':{ name:'Schelf und FADs', run:'1,5–2,5 Stunden', fish:'Segelfisch, Marlin, Wahoo, Goldmakrele, Thun', how:'Schleppangeln, Popping an FADs', note:'Schelfkante und Fischsammler (FADs). Hierher fahren wir für den Segelfisch.' },
    'khaolak-fad':{ name:'FADs vor Khao Lak', run:'ab 6 km vor Tap Lamu', fish:'Goldmakrele, Wahoo, GT, Makrele, Segelfisch', how:'Popping, Jigging auf 60–80 m, Fliegenfischen', note:'Wir angeln strikt bis zur Grenze des Similan-Nationalparks.' },
    'phangnga':{ name:'Bucht von Phang Nga', run:'ab Bang Rong', fish:'Barrakuda, Stachelmakrele, Zackenbarsch, Schnapper', how:'Spinnfischen, Grundangeln', note:'Geschütztes Wasser – der Plan B in der Monsunzeit, außerhalb der Nationalparkgrenzen.' },
    'similan':{ name:'Similan-Inseln', run:'65–70 km ab Tap Lamu', fish:'—', how:'Nur Ankern und Schnorcheln', note:'Nationalpark: Angeln ganzjährig verboten, auch bei Koh Bon und Koh Tachai. Vom 16. Mai bis 15. Oktober geschlossen.' },
    'surin':{ name:'Surin und Richelieu Rock', run:'—', fish:'—', how:'—', note:'Nationalpark: Angeln verboten. Von Mitte Mai bis Mitte Oktober geschlossen.' },
    'phiphi':{ name:'Phi Phi', run:'—', fish:'—', how:'—', note:'Nationalpark Noppharat Thara – Phi Phi: Angeln verboten, auch bei Bamboo Island und den „4 Inseln“.' },
    'shark':{ name:'Shark Point', run:'—', fish:'—', how:'—', note:'Meeresschutzgebiet seit 1992: Angeln und Ankern verboten.' },
    'lanta':{ name:'Koh Rok · Hin Daeng', run:'—', fish:'—', how:'—', note:'Nationalpark Mu Ko Lanta. Für uns gilt hier ein Angelverbot.' },
    'khaosok':{ name:'Khao Sok · Cheow Lan', run:'2,5 Stunden über Land', fish:'Schlangenkopf, Hampala, Mahseer', how:'Spinnfischen, Fliegenfischen vom Longtail-Boot', note:'Angeln ist nur von lokalen Longtail-Booten aus erlaubt.' },
    'pattaya':{ name:'Inseln vor Pattaya: Ko Larn, Ko Sak', run:'30–60 Min. ab Pattaya', fish:'Barrakuda, Zackenbarsch, Schnapper, Makrele', how:'Schleppangeln, Grundangeln, Jiggen', note:'Wir angeln in erlaubten Gebieten, außerhalb der Marinezonen von Sattahip.' },
    'samui-south':{ name:'Süden von Samui: Ko Tan, Ko Madsum', run:'30–45 Min. ab Süd-Samui', fish:'Barrakuda, Makrele, Trevally, Zackenbarsch', how:'Schleppangeln, Jiggen, Grundangeln', note:'Außerhalb des Meeresnationalparks Ang Thong.' },
    'angthong':{ name:'Ang Thong', run:'—', fish:'—', how:'—', note:'Meeresnationalpark Mu Ko Ang Thong: Angeln verboten. Wir legen dort nur zum Ankern und Schnorcheln an.' },
    'bungsamran':{ name:'Bungsamran, Bangkok', run:'40–60 Min. ab Bangkok-Zentrum', fish:'Mekong-Riesenwels, Siam-Karpfen, Arapaima', how:'Grundangeln, Feeder', note:'Kostenpflichtiger Angelpark, alle Fische werden zurückgesetzt.' },
    'maeklong':{ name:'Mae-Klong-Fluss', run:'ca. 1,5 Std. ab Bangkok', fish:'Riesen-Süßwasserrochen', how:'Grundangeln vom Boot, schweres Gerät', note:'Nur Catch & Release, mit lizenziertem Guide.' }
  },
  season:{ sailfish:['Segelfisch','Schleppangeln'], marlin:['Schwarzer Marlin','Big Game'], gt:['GT (Riesenmakrele)','Popping'], yellowfin:['Gelbflossen-Thun','Popping, Jigging'], wahoo:['Wahoo und Goldmakrele','Schleppangeln'], mackerel:['Königsmakrele','Schleppangeln'], reef:['Zackenbarsch, Schnapper, Barrakuda','Riff'], fresh:['Süßwasser','Seen und Flüsse'] },
  sea:['Ruhige See','Andamanensee'], levels:['selten oder nie','gelegentlich','gut','Hochsaison'],
  cal:{ kicker:'Beißkalender', title:'Die richtige Zeit *für Ihren Fisch*', lede:'Andamanensee: ruhige Saison von November bis April, Monsun von Mai bis Oktober. Der Rahmen markiert den aktuellen Monat.',
    notes:[['Mai–Oktober: Monsun','Wellen von 2–3 Metern, weite Ausfahrten fallen oft aus. Möglich bleiben die geschützte Bucht von Phang Nga, Süßwasser und Schönwetterfenster – die Prognose verfolgen wir für Sie.'],['Die Segelfisch-Saison schwankt von Jahr zu Jahr','Kapitäne sehen Höhepunkte sowohl im Januar–März als auch im Juni–November. Nennen Sie uns Ihre Reisedaten – wir sagen Ihnen anhand aktueller Berichte, was gerade beißt.']] },
  guar:{ kicker:'Garantien', title:'Das Risiko *tragen wir*', items:[['100 %','Erstattung bei wetterbedingter Absage','Oder kostenlose Verschiebung. Entscheidend sind Kapitän und Prognose.'],['7 Tage','Kostenlose Stornierung','Danach Verschiebung ohne Aufpreis innerhalb der Saison.'],['0 THB','Aufpreise am Pier','Alles, was inklusive ist, steht in der Bestätigung.'],['48 h','Fotos und Video des Tages','Oder 20 % Rabatt auf die nächste Ausfahrt.']] },
  quiz:{ kicker:'Auswahl in 60 Sekunden', title:'Wir planen Ihre *ideale Ausfahrt*', lede:'Fünf Fragen – und der Concierge schickt Ihnen einen Vorschlag mit Boot, Spot, Prognose und Preis.',
    q1:'Wer reist?', h1:'Wählen Sie eine Option', q2:'Wie viel Angelerfahrung haben Sie?', h2:'Danach richten wir Gerät und Format aus', q3:'Was ist Ihnen am wichtigsten?', h3:'Das Ziel bestimmt Boot und Spot', q4:'Wo werden Sie sein?', h4:'Noch nicht entschieden? Wir beraten Sie', q5:'Budget fürs Angeln', h5:'Damit wir nichts Unpassendes vorschlagen', q6:'Wohin dürfen wir Plan und Preis senden?', result:'Passend für Sie',
    who:[['solo','Ich allein','oder mit einem Freund'],['couple','Paar','zu zweit'],['family','Familie mit Kindern','Kinder ab 5 Jahren'],['friends','Gruppe 4–8','Freunde, Männertrip'],['corp','Firmenevent 8+','Team, Geschäftspartner'],['vip','VIP-Reise','Concierge für alles']],
    exp:[['zero','Noch nie geangelt','möchte es ausprobieren'],['casual','Angle gelegentlich','zu Hause und im Urlaub'],['pro','Erfahrener Spinnfischer','Popping, Jigging'],['trophy','Trophäenjäger','Big Game, Expeditionen']],
    goal:[['fun','Erholung und Fang fürs Abendessen','ganz entspannt'],['gt','Trophäe: GT und Thun','Popping, Jigging'],['billfish','Segelfisch oder Marlin','Big Game'],['fresh','Süßwasser-Giganten','Wels, Karpfen, Rochen'],['event','Event fürs Team','Turnier und Preise'],['all','Alles auf einmal','eine Woche mit Concierge']],
    where:[['phuket','Phuket','Chalong, Rawai'],['khaolak','Khao Lak oder Krabi','Norden und Osten'],['bkk','Bangkok oder Pattaya','Süßwasser und Golf von Thailand'],['any','Noch offen','beraten Sie mich']],
    budget:[['b1','Bis 10.000 THB pro Person','Gruppenausfahrt'],['b2','20.000–40.000 THB','privates Boot für einen Tag'],['b3','50.000–200.000 THB','Sportfischerboot, Übernachtung'],['b4','Budget ist zweitrangig','das Ergebnis zählt']] },
  faqTitle:'Antworten, *bevor Sie fragen*',
  faq:[
    ['Ist das legal? Ich habe von Festnahmen wegen Angelns gehört.','Ja – und das ist unser wichtigster Grundsatz. Die Touren führt ein lizenzierter Veranstalter durch, an Bord ist ein lizenzierter thailändischer Guide, die Boote haben Genehmigungen des thailändischen Marine Department. Wir angeln nicht in Meeresnationalparks (Similan-Inseln, Surin, Phi Phi, Koh Rok, Hin Daeng) und Schutzgebieten – dort ist Angeln gesetzlich verboten.'],
    ['Wie kann ich bezahlen?','Zur Buchung leisten Sie 30 % Anzahlung. Wir akzeptieren internationale Karten, Banküberweisung (auch gegen Firmenrechnung), USDT sowie Bargeld in THB oder USD vor Ort. Der Rest ist am Tag der Ausfahrt fällig. Rechnung und Bestätigung erhalten Sie schriftlich auf Englisch.'],
    ['Und wenn ein Sturm aufzieht?','Über die Ausfahrt entscheidet der Kapitän anhand der Prognose des thailändischen Wetterdienstes. Fällt die Ausfahrt wetterbedingt aus, verschieben wir kostenlos oder erstatten die Anzahlung vollständig. In der Monsunzeit schlagen wir vorab geschützte Spots oder Süßwasser vor.'],
    ['Ich werde leicht seekrank. Ist das trotzdem etwas für mich?','Wählen Sie November bis April, eine private Halbtagesausfahrt und ein Boot mit breitem Rumpf. Wir planen die Route mit kurzen Anfahrten. Für besonders Empfindliche gibt es Süßwasserseen – dort schaukelt gar nichts.'],
    ['Brauche ich Erfahrung und eigenes Gerät?','Nein. Kapitän und Maat richten alles ein und zeigen es Ihnen. Für den Pro Day und Expeditionen stellen wir Gerät auf dem Niveau von Shimano Stella und Daiwa Saltiga. Eigenes Gerät können Sie gern mitbringen – wir sagen Ihnen, was in Ihrer Saison sinnvoll ist.'],
    ['Darf ich den Fang behalten?','Speisefische ja: Der Koch bereitet Sashimi und Gegrilltes direkt an Bord zu. Segelfische, Marline und große GTs lassen wir nach Catch-&-Release-Standard frei: Wir vermessen und fotografieren sie und stellen ein Zertifikat aus.'],
    ['Geht das auch mit Kindern?','Ja, ab 5 Jahren bei „Familientag“ und „Erster Biss“. Schwimmwesten für Kinder, leichte Ruten, Schatten und Toilette an Bord. Auf dem Sportfischerboot ab 10 Jahren.'],
    ['Brauche ich ein Visum?','Seit dem 15. September 2026 reisen Staatsangehörige Deutschlands, Österreichs und der Schweiz – wie die vieler anderer Länder – für 30 Tage visumfrei nach Thailand ein. Maßgeblich ist Ihr Pass: Wir prüfen die Regeln vor der Buchung und helfen bei längeren Aufenthalten mit dem DTV-Visum. Details finden Sie in unserem Visa-Ratgeber.']
  ],
  legalNote:'Wir angeln nicht in Meeresnationalparks und Schutzgebieten: Similan-Inseln, Surin, Phi Phi, Koh Rok, Hin Daeng, Shark Point. Das ist thailändisches Recht – und es schützt Sie.',
  tours:{
    'first-strike':{ title:'Erster Biss', where:'Phuket · Racha Yai', kind:'Gruppenausfahrt',
      short:'Kleingruppe mit bis zu sechs Anglern auf einem komfortablen Boot. Schleppangeln und Grundangeln bei den Racha-Inseln.',
      pitch:'Der einfachste Weg, das Meeresangeln in der Andamanensee auszuprobieren. Nicht 15–40 Personen wie bei Massenausflügen, sondern höchstens sechs Angler auf einem Boot mit Toilette und Schatten.',
      species:['Barrakuda','Makrele','Schnapper','Zackenbarsch'],
      day:[['07:30','Transfer vom Hotel auf Phuket'],['08:30','Abfahrt ab Chalong und Einweisung'],['09:15','Schleppangeln auf dem Weg nach Racha Yai'],['10:30','Grundangeln und Jigging an den Riffen'],['12:30','Mittagessen an Bord: Fang vom Grill, Obst'],['14:00','Nachmittagsrunde, auf Wunsch Schnorcheln'],['16:00','Rückfahrt und Transfer zum Hotel']],
      incl:['Transfer von Hotels auf Phuket','Gerät und Köder','Mittagessen, Wasser, Obst','Passagierversicherung','Lizenzierter Guide an Bord','Fotos vom Fang in den Chat'],
      excl:['Alkohol','Privates Boot – siehe „Familientag“'],
      upsell:[['Privates Boot','Das ganze Boot nur für Sie – „Familientag“'],['Drohnenvideo','+4.500 THB pro Ausfahrt'],['Kinderset','Kostenlos: Schwimmweste und leichte Rute']] },
    'family-half':{ title:'Familientag', where:'Phuket · Racha Yai', kind:'Privates Boot',
      short:'Ein Boot nur für Ihre Familie. Fünf Stunden in ruhigem Wasser, der Kapitän hilft Kindern und Einsteigern.',
      pitch:'Das Format für alle, die angeln möchten, statt eine Mutprobe zu bestehen. Wir starten morgens, solange das Meer ruhig ist, angeln bei Racha Yai, essen den Fang zu Mittag und sind vor der größten Hitze zurück.',
      species:['Barrakuda','Goldmakrele','Schnapper','Stachelmakrele'],
      day:[['08:00','Transfer vom Hotel'],['08:45','Abfahrt und Sicherheitseinweisung'],['09:15','Schleppangeln: die ersten Bisse'],['10:30','Angeln am Riff, Hilfe für die Kinder'],['12:00','Sashimi und Grill aus dem Fang'],['13:30','Rückkehr nach Chalong']],
      incl:['Privates Boot mit Kapitän und Maat','Transfer hin und zurück','Gerät für Erwachsene und Kinder','Mittagessen aus dem Fang und Getränke','Schwimmwesten für Kinder','Versicherung und lizenzierter Guide'],
      excl:['Alkohol','Fotograf – auf Anfrage'],
      upsell:[['Fotograf an Bord','+6.000 THB, über 100 Aufnahmen'],['Ganzer Tag','+12.000 THB, mit Strandstopp'],['Torte und Deko','Für den Geburtstag an Bord']] },
    'pro-gt':{ title:'Pro Day: GT und Jigging', where:'Phuket · Racha Noi · Schelf', kind:'Speedboat · bis 4 Angler',
      short:'Popping auf Giant Trevally und Vertical Jigging auf den Bänken von Racha Noi. Für alle, die es können und eine Trophäe wollen.',
      pitch:'Ein schnelles Speedboat, ein auf Popping spezialisierter Kapitän und Gerät, das einem GT von über 30 kg standhält. Die Spots wählen wir nach Gezeiten und Mondphase an Ihrem Termin – außerhalb der Nationalparkgrenzen.',
      species:['GT (Giant Trevally)','Gelbflossen-Thun','Hundezahn-Thun','Amberjack','Zackenbarsch'],
      day:[['06:00','Transfer und Kaffee an Bord'],['06:45','Abfahrt mit 30 Knoten'],['07:30','Morgen-Popping an den Riffen von Racha Noi'],['10:00','Vertical Jigging auf 60–120 m'],['12:30','Mittagessen und Spotwechsel je nach Strömung'],['14:00','Popping am Nachmittag mit der Flut'],['16:30','Rückkehr und Auswertung des Tages']],
      incl:['Speedboat mit spezialisiertem Kapitän','Gerät Shimano Stella / Daiwa Saltiga, PE 6–10','Popper, Stickbaits, Jigs 150–400 g','Mittagessen, Wasser, Energydrinks','Lizenzierter Guide und Versicherung','Fotos und Videos von Actioncams'],
      excl:['Verlorene Köder über drei hinaus – zum Selbstkostenpreis'],
      upsell:[['Kameramann mit Drohne','+9.000 THB, Clip innerhalb von 48 Stunden'],['Zweiter Tag','−15 % bei Buchung von zwei Tagen'],['Eigenes Gerät','3.000 THB Rabatt']] },
    'bigame-day':{ title:'Big Game auf dem Sportfischerboot', where:'Phuket · Schelf und FADs', kind:'Sportfischerboot, 44–50 Fuß',
      short:'Schleppangeln auf Segelfisch und Marlin vom Cockpit eines echten Sportfischerboots. Kampfstuhl, Ausleger, Koch an Bord.',
      pitch:'Das wichtigste Format für die Trophäe. Ein Sportfischerboot mit 44–50 Fuß, Klimaanlage, Kampfstuhl und einer Crew, die weiß, wo sich der Segelfisch in diesem Monat auf dem Schelf aufhält.',
      species:['Segelfisch','Schwarzer Marlin','Wahoo','Goldmakrele','Thun'],
      day:[['06:30','Transfer im Business-Class-Wagen'],['07:00','Abfahrt und Frühstück vom Koch'],['08:00','Schleppangeln über Schelf und FADs'],['12:30','Mittagessen: Sashimi aus dem Fang und ein warmes Gericht'],['13:30','Zweite Schlepp-Serie am Nachmittag'],['17:00','Rückkehr und Champagner auf den ersten Segelfisch']],
      incl:['Sportfischerboot mit Crew','Koch und Vollpension an Bord','Big-Game-Gerät und Kampfstuhl','Business-Class-Transfer','Lizenzierter Guide und Versicherung','Fotos und ein kurzes Video des Tages'],
      excl:['Premium-Alkohol – laut Karte','Nationalparkgebühren beim Ankern im Park'],
      upsell:[['Übernachtung auf dem Schelf','Verlängerung zur „Nacht auf dem Schelf“'],['Drohnenaufnahmen','+9.000 THB'],['Trophäen-Replik','Lebensgroße Nachbildung Ihres Fischs nach Fotos und Maßen']] },
    'overnight-shelf':{ title:'Nacht auf dem Schelf', where:'Andamanensee · 2 Tage / 1 Nacht', kind:'Sportfischerboot mit Übernachtung',
      short:'Zwei Morgen- und eine Abendbeißzeit direkt am Spot. Kalmarangeln bei Nacht, Abendessen unter Sternen, Sonnenaufgang auf dem Schelf.',
      pitch:'Das produktivste Format: Statt täglich drei Stunden auf der Anfahrt zu verbringen, erleben Sie die beste Beißzeit – bei Sonnenaufgang und Sonnenuntergang – direkt am Spot.',
      species:['Segelfisch','Marlin','Gelbflossen-Thun','Wahoo','Kalmar'],
      day:[['Tag 1 · 07:00','Abfahrt und Schleppangeln über den Schelf'],['Tag 1 · 18:00','Abendessen vom Koch und Kalmarangeln bei Nacht'],['Tag 2 · 05:30','Beißzeit bei Sonnenaufgang – die beste Chance auf Segelfisch'],['Tag 2 · 12:00','Mittagessen und letzte Serie'],['Tag 2 · 17:00','Rückkehr nach Chalong']],
      incl:['Sportfischerboot mit Kabinen und Dusche','Koch und fünf Mahlzeiten','Komplettes Gerät und Köder','Transfers','Lizenzierter Guide und Versicherung','Fotos und Video des Tages'],
      excl:['Premium-Alkohol','Treibstoff für Fahrten über 60 Meilen hinaus'],
      upsell:[['3 Tage / 2 Nächte','+85.000 THB'],['Kameramann mit Drohne','Film über die Reise'],['Villa nach der Ausfahrt','Reserviert der Concierge']] },
    'expedition-khaolak':{ title:'Expedition Khao Lak', where:'Khao Lak · FADs und Schelf · 4 Tage', kind:'Liveaboard · pro Angler',
      short:'Vier Tage an Bord: Popping und Jigging in den FAD-Feldern zwischen Khao Lak und den Similan-Inseln – strikt außerhalb der Parkgrenzen.',
      pitch:'Eine Expedition für alle, die möglichst viele Würfe pro Tag wollen. Die FAD-Felder beginnen 6 km vor Tap Lamu und reichen bis zu den Similan-Inseln. Wir angeln auf dem Schelf und übernachten vor Anker; im Park erholen wir uns nur – Angeln ist dort verboten.',
      species:['GT','Gelbflossen-Thun','Goldmakrele','Wahoo','Königsmakrele'],
      day:[['Tag 1','Transfer ab Phuket, Abfahrt ab Tap Lamu, erste FADs'],['Tag 2','Popping bei Sonnenaufgang, tagsüber Jigging auf 60–80 m'],['Tag 3','Weiter entfernte FADs und Schleppangeln auf Segelfisch'],['Tag 4','Morgensession, Rückkehr und Transfer']],
      incl:['Liveaboard mit Kabinen','Vollpension','Premium-Gerät','Transfer Phuket – Tap Lamu','Lizenzierter Guide und Versicherung','Fotos und Video der Expedition'],
      excl:['Nationalparkgebühr fürs Ankern (500 THB pro Tag)','Alkohol','Trinkgeld für die Crew'],
      upsell:[['Privatcharter','Das ganze Boot für Ihre Gruppe'],['Verlängerung auf 6 Tage','Auf Anfrage'],['Mergui (Myanmar)','Expedition auf Anfrage, wenn die Grenze offen ist']] },
    'gulf-private':{ title:'Golf von Thailand: Pattaya und Samui', where:'Pattaya · Koh Khram · Samui', kind:'Privates Speedboat',
      short:'Für alle, die am Golf leben oder Urlaub machen. Kurze Anfahrt zu den Inseln, Barrakuda, Cobia, Königsmakrele.',
      pitch:'In Pattaya ist die beste Saison von Oktober bis März, auf Samui von Januar bis Mai. Wir fahren zu den Inseln Koh Khram, Koh Phai und Samae San oder zu den Riffen im Norden von Samui – außerhalb des Nationalparks Ang Thong, in dem Angeln verboten ist.',
      species:['Barrakuda','Cobia','Königsmakrele','Zackenbarsch','Queenfish'],
      day:[['07:00','Transfer vom Hotel oder Condo'],['07:45','Abfahrt mit dem Speedboat'],['08:30','Schleppangeln auf dem Weg zu den Inseln'],['10:30','Jigging und Lebendköder an den Riffen'],['12:30','Mittagessen an Bord und Baden'],['14:30','Rückfahrt']],
      incl:['Privates Speedboat mit Kapitän','Transfer','Gerät und Köder','Mittagessen und Getränke','Lizenzierter Guide und Versicherung','Fotos vom Fang'],
      excl:['Alkohol','Kalmarangeln bei Nacht – auf Anfrage'],
      upsell:[['Kalmar bei Nacht','Abendausfahrt mit Dinner'],['See mit Arapaima','Zweiter Tag – Süßwasser'],['Yacht statt Speedboat','Für Gruppen bis 12 Gäste']] },
    'bangkok-monsters':{ title:'Monsterfische von Bangkok', where:'Bangkok · New Bungsamran', kind:'Süßwasser · Tagestour',
      short:'Mekong-Riesenwels und Siam-Riesenkarpfen von 30–100 kg an Thailands bekanntestem Angelsee. Transfer ab Hotel in Bangkok.',
      pitch:'Ideal für einen Stopp in Bangkok und für die Regenzeit, wenn das Meer stürmisch ist. Ein See mit Fischen bis 100 kg, ein klimatisierter Pavillon und ein Guide, der Gerät und Futter vorbereitet.',
      species:['Mekong-Riesenwels','Siam-Riesenkarpfen','Arapaima'],
      day:[['06:00','Transfer vom Hotel in Bangkok (etwa eine Stunde)'],['07:30','Pavillon, Gerät, Anfüttern'],['08:00','Angeln: Der Guide ist den ganzen Tag für Sie da'],['13:00','Mittagessen im Restaurant am See'],['19:30','Fotos mit den Trophäen und Rückfahrt']],
      incl:['Transfer von Hotels in Bangkok','Ticket für die Session','Gerät und Futter','Guide am See','Klimatisierter Pavillon','Trophäenfotos'],
      excl:['Verpflegung am See','Nachtsession – auf Anfrage'],
      upsell:[['Nachtsession','Große Welse bei Nacht'],['Riesenrochen','Zweiter Tag am Mae Klong'],['Hotel am Fluss','Reserviert der Concierge']] },
    'stingray':{ title:'Riesenrochen', where:'Fluss Mae Klong · Samut Songkhram', kind:'Süßwasser · Tagestour',
      short:'Jagd auf Süßwasser-Stechrochen von über 100 kg – vom Boot aus auf dem Mae Klong. Catch & Release.',
      pitch:'Eine der größten Süßwasserarten der Welt. 2015 wurde am Mae Klong ein Rochen von etwa vier Metern Länge gefangen und wieder freigelassen. Das ist Angeln mit Geduld – und eine Chance, an die Sie sich Ihr Leben lang erinnern.',
      species:['Riesen-Süßwasserstechrochen','Wels'],
      day:[['05:30','Transfer ab Bangkok (etwa 1,5 Stunden)'],['07:30','Boot auf dem Fluss und schweres Gerät'],['08:00','Angeln mit Lebendköder und Warten auf den Biss'],['13:00','Mittagessen am Fluss'],['17:30','Rückfahrt nach Bangkok']],
      incl:['Transfer','Boot und lokaler Guide','Schweres Gerät 80–130 lb','Köder','Mittagessen','Fotos und Vermessung der Trophäe'],
      excl:['Bissgarantie – es ist ein Wildfisch'],
      upsell:[['Zweiter Tag','Doppelte Chance'],['Monsterfische von Bangkok','Kombination über zwei Tage'],['Videoaufnahmen','Kameramann an Bord']] },
    'khaosok-jungle':{ title:'Dschungelangeln in Khao Sok', where:'Cheow-Lan-See · 2 Tage', kind:'Floßhaus · pro Angler',
      short:'Schlangenkopf und Hampala zwischen Karstfelsen. Eine Nacht im Floßhaus auf dem See und Beißzeit bei Sonnenaufgang.',
      pitch:'Das landschaftlich schönste Angeln Thailands. Wir angeln von lokalen Longtail-Booten aus – andere Boote sind auf dem See nicht zugelassen – mit Spinn- und Fliegenrute und wohnen in einem Floßhaus mitten im Nationalpark.',
      species:['Riesen-Schlangenkopf','Hampala','Mahseer','Wels'],
      day:[['Tag 1 · 07:00','Transfer ab Phuket oder Khao Lak (etwa 2,5 Stunden)'],['Tag 1 · 11:00','Longtail-Boot und erste Würfe auf Schlangenkopf'],['Tag 1 · 17:00','Abendbeißzeit und Dinner im Floßhaus'],['Tag 2 · 06:00','Angeln bei Sonnenaufgang'],['Tag 2 · 12:00','Mittagessen und Rücktransfer']],
      incl:['Transfers','Floßhaus mit Verpflegung','Longtail-Boot mit lokalem Guide','Nationalparkgebühren','Leichtes Gerät','Fotos'],
      excl:['Fliegengerät – am besten das eigene','Alkohol'],
      upsell:[['Dritter Tag','Entlegene Buchten'],['Dschungelsafari','Für die Familie'],['Privates Floßhaus','Das ganze Haus für Sie']] },
    'tournament':{ title:'Firmenturnier', where:'Phuket · 3–5 Boote · 2 Tage', kind:'Firmengruppe · 8–30 Gäste',
      short:'Turnier auf baugleichen Booten mit Schiedsrichter, Kategorien und Pokalen. Galadinner in der Villa und Film nach 48 Stunden.',
      pitch:'Ein Event, nach dem sich das Team daran erinnert, wie es um den Pokal gekämpft hat – und nicht, wie es auf den Bus gewartet hat. Flotte, Jury, Preise, Dinner, Filmaufnahmen und Dokumente übernehmen wir.',
      species:['Segelfisch','Thun','Barrakuda','Stachelmakrele'],
      day:[['Tag 1 · Morgen','Briefing und Einteilung auf die Boote'],['Tag 1 · Tag','Erste Turnierrunde'],['Tag 1 · Abend','Dinner in der Villa und Zwischenstand'],['Tag 2 · Tag','Finalrunde'],['Tag 2 · Abend','Siegerehrung, Pokale und Film-Teaser']],
      incl:['3–5 Boote mit Crew','Schiedsrichter, Regeln und Protokolle','Pokale und Kategorien','Galadinner mit Moderator','Fotos, Drohne und Clip innerhalb von 48 Stunden','Vertrag und Firmenrechnung'],
      excl:['Unterkunft – wir finden die passende','Flüge'],
      upsell:[['Branding','T-Shirts, Flaggen und Pokale mit Logo'],['Villa für die Gruppe','Für alle Reisetage'],['Partnerprogramm','Spa, Yacht, Shopping']] },
    'signature-week':{ title:'Signature Week', where:'Phuket · Khao Lak · Bangkok', kind:'Concierge · 7 Tage',
      short:'Eine Woche Spitzenangeln in Thailand, komplett organisiert: Villa, Sportfischerboot, Süßwasser-Giganten, Koch, Filmaufnahmen und persönlicher Concierge.',
      pitch:'Für alle, die ihre Zeit schätzen. Wir stellen das Programm nach Ihren Zielen zusammen: drei Tage auf dem Meer, eine Nacht auf dem Schelf, ein Tag im Dschungel und ein Rekordsee. Sie wohnen in der Villa, der Concierge regelt alles andere.',
      species:['Segelfisch','Marlin','GT','Mekong-Riesenwels','Schlangenkopf'],
      day:[['Tag 1','Empfang am Flughafen, Villa, Dinner vom Koch'],['Tage 2–3','Big Game auf dem Sportfischerboot'],['Tag 4','Nacht auf dem Schelf'],['Tag 5','Dschungel von Khao Sok'],['Tag 6','Erholung, Spa, Familie – nach Wunsch'],['Tag 7','Monsterfische von Bangkok oder Abflug']],
      incl:['Persönlicher Concierge rund um die Uhr','Villa mit Pool','Alle Ausfahrten und Boote','Privatkoch','Fotos, Drohne und Reisefilm','Alle Transfers und VIP-Empfang'],
      excl:['Flüge','Individuelle Wünsche außerhalb des Programms – nach Kostenvoranschlag'],
      upsell:[['Wasserflugzeug','Flüge zwischen den Spots'],['Familienprogramm','Für alle, die nicht angeln'],['Trophäen-Replik','Für Ihr Büro']] }
  }
};
