// ERKAK · oʻzbekcha · yoʻnalishlar, dasturlar, joylar. Faktlar va narxlar — 2026-yil sentabrdagi bozor tadqiqotiga koʻra.
export const directions = {
  fishing:{ name:'Baliq ovi va trofeylar', short:'Yelkanbaliq, marlin, GT va chuchuk suv gigantlari. Qonuniy, litsenziyali gid bilan.',
    who:'Ekskursiya emas, haqiqiy baliq ovini istagan oilalar, tajribali baliqchilar, trofey ovchilari va doʻstlar davrasi uchun.',
    intro:'Andaman dengizida trofey baliq ovi va Bangkokning chuchuk suv gigantlari — ERKAKning ilk ochilgan yoʻnalishi. Xususiy qayiqlar, Stella darajasidagi anjomlar, litsenziyali gid va shaffof xarita: biz hech qachon dengiz milliy bogʻlarida baliq tutmaymiz.',
    incl:['Qayiq va kapitan','Anjomlar va xoʻrak','Transfer','Bortda ovqatlanish','Sugʻurta va litsenziyali gid'] },
  muaythai:{ name:'Muay tay va yakkakurashlar', short:'Puket va Bangkokdagi lagerlar, BJJ, boks, MMA. Birinchi mashgʻulotdan birinchi janggacha.',
    who:'Yugurish yoʻlakchasi orqali emas, jang orqali formaga kirmoqchi boʻlganlar uchun.',
    intro:'Puket va Bangkok — muay tayning jahon poytaxtlari: minglab zallar, yashash joyi bor lagerlar va deyarli har oqshom janglar. Lagerni darajangiz va maqsadingizga qarab tanlaymiz, zalga yaqin joylashtiramiz va birinchi mashgʻulotdan natijalar tahliligacha yoningizda boʻlamiz.',
    incl:['Tekshirilgan lagerda mashgʻulotlar','Zalga yaqin turar joy','Aeroportdan transfer','Boshlangʻich ekipirovka','Oʻzbek va rus tillarida konsyerj'],
    note:'Tailandga kirish qoidalari pasportga bogʻliq: 2026-yil 15-sentabrdan 60 ta davlat fuqarolari 30 kungacha vizasiz kiradi, Oʻzbekiston fuqarolariga esa viza (e-Visa) kerak — hujjatlarda yordam beramiz. Uzoq mashgʻulotlar uchun DTV vizasini olishga ham koʻmaklashamiz.' },
  camps:{ name:'Sport yigʻinlari', short:'Hyrox, yogʻ yoqish, treyl, triatlon, marafon, velosport yigʻinlari — murabbiy va reja bilan.',
    who:'1–3 haftada natija va uyda yetishmaydigan intizomni istaganlar uchun.',
    intro:'Yigʻin — formani yaxshilashning eng tez yoʻli: murabbiy, rejim, ovqatlanish va mashq qilgingiz keladigan iqlim. Puketdagi Hyrox lageridan Keniyaning Iten shahridagi baland togʻ yigʻinlarigacha.',
    incl:['Ixtisoslashgan murabbiy dasturi','Boshida va oxirida oʻlchovlar','Yuklamaga mos ovqatlanish','Turar joy','Tiklanish: massaj, sauna'] },
  longevity:{ name:'Tibbiy koʻrik va uzoq umr', short:'Executive check-up, erkaklar salomatligi, yurak, uyqu, DNK — akkreditatsiyadan oʻtgan klinikalarda.',
    who:'Taxmin qilib yurmasdan, oʻz koʻrsatkichlarini aniq bilishni istagan 35+ yoshdagi erkaklar uchun.',
    intro:'Bangkok — tibbiy turizmning asosiy markazlaridan biri: JCI akkreditatsiyasiga ega shifoxonalar, paketlarning ochiq narxlari va bir kunda tekshiruv. Klinika va paketni tanlaymiz, oʻzbek va rus tillarida hamrohlik qilamiz, xulosalarni tarjima qilamiz. ERKAK — konsyerj, tibbiyot muassasasi emas: qarorlarni shifokor qabul qiladi.',
    incl:['Klinika va paketni tanlash','Qabulga yozish, oʻzbek va rus tillarida hamrohlik','Xulosalar tarjimasi','Transferlar va mehmonxona','Natijalar boʻyicha harakat rejasi'],
    note:'Paket narxlarini shifoxonalarning oʻzi e’lon qiladi; aksiya narxlari ba’zan faqat rezidentlar uchun amal qiladi — biz chet ellik bemor uchun yozma tasdiq olamiz.' },
  detox:{ name:'Detoks va yangilanish', short:'Detoks-retritlar, vazn dasturlari, alkogolsiz retritlar, shifokor nazoratida ochlik, ayurveda.',
    who:'Charchagan, ortiqcha vazn yigʻgan va hammasini qaytadan boshlamoqchi boʻlganlar uchun.',
    intro:'Yangilanish — bu «toksinlarni chiqarish» emas, yangi rejim. Samui va Balidagi retritlar, Puketdagi vazn kamaytirish dasturlari, Yevropada shifokor nazoratidagi ochlik va Keralada ayurveda. Boshlashdan oldin — salomatlik soʻrovnomasi: ba’zi formatlar hammaga ham toʻgʻri kelmaydi.',
    incl:['Retrit dasturi','Protokol boʻyicha turar joy va ovqatlanish','Mutaxassislar maslahati','Transferlar','Keyingi 30 kun davomida koʻmak'] },
  recovery:{ name:'Tiklanish', short:'Sauna va muz, tay massaji, fizioterapiya, onsenlar, rus hammomi, Oʻlik dengiz.',
    who:'Beli ogʻriyotgan, charchoqdan qutula olmayotgan va uyqusi buzilganlar uchun.',
    intro:'Tiklanish — mashgʻulotning yarmi va ogʻir yildan keyin kuch-quvvatni qaytarishning eng yaxshi yoʻli. Puketda kontrast terapiya, Chiang Mayda eski maktab massaji, Yaponiya onsenlari, rus hammomi va Oʻlik dengiz.',
    incl:['Muolajalar kursi','Tekshirilgan studiya va spa','Sizning ritmingizga mos jadval','Transferlar','Oʻzbek va rus tillarida konsyerj'] },
  mind:{ name:'Ong va xotirjamlik', short:'Sokin retritlar, nafas va sovuq, erkaklar davralari, monastir, kouching, psixolog.',
    who:'Hamma narsasi bor, faqat xayolida sokinlik yetishmaydiganlar uchun.',
    intro:'Sokinlik va fikr tiniqligi — eng taqchil resurs. Shimoliy Tailanddagi meditatsiya markazlari, Balida nafas amaliyotlari, Oltoyda erkaklar retritlari, onlayn kouching va psixolog. An’ana bepul boʻlgan joyda biz faqat logistikani sotamiz.',
    incl:['Yetakchi yoki ustoz','Sokin muhitda yashash','Ovqatlanish','Transferlar','Keyin integratsiya sessiyasi'] },
  adventure:{ name:'Sarguzashtlar', short:'Elbrus, Kilimanjaro, Everest, Kamchatka, moto-turlar, safari, Reyli qoyalari.',
    who:'Nevaralariga hikoya qilib beradigan ishni qilmoqchi boʻlganlar uchun.',
    intro:'Choʻqqilar, treklar va marshrutlar — ulardan keyin oʻz vazifalaringiz koʻlamiga boshqacha qaraysiz. Mahalliy litsenziyali operatorlar bilan ishlaymiz, zaxira kunlar va balandlikni qoplaydigan sugʻurtani rejaga kiritamiz — va xavflar haqida ochiq gapiramiz.',
    incl:['Gidlar va ruxsatnomalar','Roʻyxat boʻyicha jihozlar','Marshrut boʻyicha turar joy','Faol dam olish sugʻurtasi','Foto va video'] },
  ocean:{ name:'Okean', short:'Dayving, fridayving, serf, kayt, yaxta kurslari va yaxtada dam olish haftalari.',
    who:'Suvga talpinadigan va shunchaki tomosha qilish emas, oʻzi qila olishni istaganlar uchun.',
    intro:'Racha orollari yonidagi ilk shoʻngʻishdan Similan orollaridagi dayv-safari va Balidagi serfgacha. Sertifikatlangan instruktorlar, xalqaro sertifikatlar hamda shamol va toʻlqinga qarab tanlangan mavsumlar.',
    incl:['Instruktor va sertifikatlash','Jihozlar','Qayiq yoki spot','Yaqin atrofda turar joy','Suv ostida suratga olish'] },
  golf:{ name:'Golf va padel', short:'Puket va Shotlandiyada golf haftalari, Dubayda padel, tennis akademiyalari.',
    who:'Oʻyinni, yaxshi davrani va goʻzal maydonlarni sevadiganlar uchun.',
    intro:'Bir haftada Puketning beshta maydoni, Hua Hinda noldan golf, Sent-Endryusning links maydonlari va bu sport eng tez oʻsayotgan Dubayda padel. Taym-slotlar, pro-murabbiy va inventar bilan transferlar — bizning zimmamizda.',
    incl:['Taym-slotlar va kortlar','Murabbiy yoki pro','Inventar bilan transferlar','Turar joy','Guruh ichida turnir'] },
  aesthetics:{ name:'Erkaklar estetikasi', short:'Soch koʻchirib oʻtkazish, stomatologiya, koʻrish korreksiyasi, teri parvarishi, uslub.',
    who:'Oʻzining eng yaxshi yoshidagidek koʻrinishni istaganlar uchun.',
    intro:'Istanbul, Bangkok va Seul — estetik tibbiyotning jahon markazlari: bu yerda a’lo klinikalar ham, «konveyerlar» ham koʻp. Akkreditatsiyadan oʻtgan klinikalarni tanlaymiz, muolajani aynan kim bajarishini tekshiramiz va oʻzbek hamda rus tillarida hamrohlik qilamiz.',
    incl:['Akkreditatsiyadan oʻtgan klinikani tanlash','Safardan oldin konsultatsiya','Oʻzbek va rus tillarida hamrohlik','Mehmonxona va transferlar','Keyingi nazorat'],
    note:'ERKAK tibbiyot muassasasi emas: koʻrsatmalar va qarorlar — shifokor zimmasida. Oddiy sayohat sugʻurtasi rejali operatsiyalarni qoplamaydi.' },
  nutrition:{ name:'Ovqatlanish va ERKAK qoʻshimchalari', short:'Tahlillar asosida nutritsiolog, ERKAK qoʻshimchalar protokoli, shaxsiy oshpaz va reja boʻyicha ovqatlanish.',
    who:'Ovqat va qoʻshimchalar tahlil koʻrsatkichlariga ijobiy ta’sir qilishini istaganlar uchun.',
    intro:'Ovqatlanish — har qanday dasturning asosi. Litsenziyali mutaxassis bilan tahlillarni koʻrib chiqish, har bir partiyasi tahlil sertifikatiga ega ERKAK qoʻshimchalar protokoli, safar davomida shaxsiy oshpaz va Oʻzbekiston togʻlariga — mumiyo manbalariga sayohat.',
    incl:['Tahlillarni koʻrib chiqish','Shaxsiy reja','Partiya sertifikatiga ega qoʻshimchalar','Messenjerda koʻmak','90 kundan keyin nazorat nuqtasi'] },
  family:{ name:'Ota va oʻgʻil', short:'Ota va oʻgʻil uchun umumiy xotiraga aylanadigan sayohatlar.',
    who:'Oʻgʻliga buyum emas, birga oʻtkaziladigan vaqtni sovgʻa qilmoqchi boʻlgan otalar uchun.',
    intro:'Puketda ring va okean, Himolay, Krabi qoyalari va orollari. Bola yoshiga mos dasturlar, tekshirilgan instruktorlar va birinchi oʻrinda — xavfsizlik.',
    incl:['Bola yoshiga mos dastur','Instruktorlar va gidlar','Turar joy','Transferlar','Safar haqida foto va film'] },
  business:{ name:'Kompaniyalar va doʻstlar uchun', short:'Top-jamoalar uchun retritlar, regatalar, asoschilar retritlari, kuyov va doʻstlari uchun premium safarlar.',
    who:'Umumiy tajriba kerak boʻlgan jamoalar va doʻstlar davrasi uchun.',
    intro:'Birgalikdagi tajriba har qanday timbildingdan koʻra kuchliroq yaqinlashtiradi. Puket va Balida strategik retritlar, korporativ regatalar va siyqasi chiqmagan erkaklar safarlari — kompaniya uchun hujjatlar va hisob-faktura bilan.',
    incl:['Vazifaga moslangan dastur','Tadbir joylari va turar joy','Boshlovchi va fasilitator','Kompaniya uchun hujjatlar va hisob-faktura','Tadbir haqida film'] }
};

export const programs = {
  // ── Muay tay va yakkakurashlar ──────────────────────────────────
  'mt-phuket-week':{ title:'Puketda muay tay haftasi', where:'Puket, Soi Ta-Iad',
    short:'Dunyodagi asosiy muay tay koʻchasidagi lagerda kuniga ikki mashgʻulot. Zaldan besh daqiqalik masofada hovuzli turar joy.',
    about:'Chalongdagi Soi Ta-Iad — Tiger Muay Thai, Phuket Top Team va AKA ketma-ket joylashgan koʻcha. Lagerni darajangizga qarab tanlaymiz: yangi boshlovchilar uchun guruh darslari, boks bilan shugʻullanib kelganlar uchun sparringlar yoki maqsad forma boʻlsa — kuch bloki. Zal yonidagi hovuzli mehmonxonada yashaysiz, transfer va birinchi mashgʻulotda oʻzbek va rus tillarida hamrohlik qilamiz.',
    plan:['Transfer, joylashish, murabbiy bilan tanishuv va kirish mashgʻuloti','Ertalab texnika darsi, kechqurun — lapa va boks qoplarida ish, xohishga koʻra sparring','Hafta oʻrtasida massaj va tiklanish','Yakuniy mashgʻulot, video-tahlil va uy uchun reja'],
    tip:'Lagerlar yil boʻyi ishlaydi; yomgʻirlar mavsumida (may–oktabr) turar joy arzonroq. Bir hafta 30 kunlik vizasiz muddatga bemalol sigʻadi, Oʻzbekiston fuqarolariga esa viza (e-Visa) kerak — hujjatlarda yordam beramiz.' },
  'mt-month':{ title:'Toʻrt haftalik transformatsiya: muay tay va ovqatlanish', where:'Puket',
    short:'Eng ommabop format — «ketib, boshqa odam boʻlib qaytish»: kuniga ikki mashgʻulot, nutritsiolog va har hafta oʻlchovlar.',
    about:'Muay tay lagerida aniq maqsad bilan toʻrt hafta: ortiqcha kilogrammlardan xalos boʻlish, chidamlilik va texnikani oshirish. Nutritsiolog ratsionni yuklamaga qarab hisoblaydi, ovqat tayyor holda yetkaziladi, haftada bir marta tana tarkibi oʻlchanadi. Dastur 28 kun davom etadi: bu 2026-yil 15-sentabrdan amal qilayotgan 30 kunlik vizasiz muddatga zaxira bilan sigʻadi, Oʻzbekiston fuqarolari uchun esa vizani rasmiylashtirishda yordam beramiz.',
    plan:['Issiq va yuklamaga moslashish, asosiy texnika, boshlangʻich oʻlchovlar','Kuniga ikki mashgʻulot, kuch bloki, ovqatlanish nazorati','Xohishga koʻra sparringlar, yakuniy oʻlchovlar va video-tahlil','Uyda davom ettirish uchun 90 kunlik mashgʻulot va ovqatlanish rejasi'],
    tip:'Tailandga vizasiz kirish muddati — 30 kun va u faqat ayrim davlatlar fuqarolariga taalluqli. Oʻzbekiston fuqarolariga viza (e-Visa) kerak — rasmiylashtirishda yordam beramiz.' },
  'mt-bangkok':{ title:'Bangkok: afsonalar bilan bir hafta va stadionda oqshom', where:'Bangkok',
    short:'Chempionlar zallarida mashgʻulotlar va Rajadamnern stadionida ring yonidagi eng yaxshi oʻrinlar.',
    about:'Bangkok — muay tay tarixi: chempionlar mashq qilgan zallar va deyarli har oqshom janglar boʻladigan Rajadamnern stadioni. Besh kun davomida ikki-uchta klassik zalda mashq qilasiz, har kuni shaxsiy mashgʻulot olasiz va janglar oqshomini ring yonidagi oʻrinlardan tomosha qilasiz. Chiptalarni faqat rasmiy kassalardan olamiz — chayqovchilar ustamasisiz.',
    plan:['Klassik zalda ertalabki va kechki sessiyalar','Sobiq chempion bilan shaxsiy mashgʻulot','Stadionda ring yonidagi oʻrinlardan janglar oqshomi','Yakuniy sessiya va Bangkokda erkin vaqt'],
    tip:'Eng yaxshi oylar — noyabr–fevral: martdan maygacha Bangkokda juda issiq boʻladi.' },
  'mt-private':{ title:'Shaxsiy muay tay murabbiyi', where:'Puket yoki Samui',
    short:'Jangchi-murabbiy bilan yakkama-yakka oʻnta mashgʻulot. Oilaviy ta’tilga moslashadigan erkin jadval.',
    about:'Oila bilan dam olayotgan va lager jadvaliga moslashishni istamaydiganlar uchun format. Murabbiy villaga keladi yoki sizni qulay vaqtda zalda kutadi. Murabbiyni til, daraja va maqsadga qarab tanlaymiz: texnika, forma yoki sparringlarga tayyorgarlik.',
    plan:['Daraja va maqsadni baholash','Texnika, kombinatsiyalar, lapada ishlash','Sparring elementlari va mustaqil mashgʻulotlar rejasi'],
    tip:'Mashhur sobiq chempionlar bilan mashgʻulotlar qimmatroq — byudjetingizga mosini topamiz.' },
  'mt-fight':{ title:'Birinchi jangga tayyorgarlik', where:'Puket',
    short:'Lagerda olti–sakkiz hafta, sparringlar va burchagingizda professional jamoa bilan ringga chiqish.',
    about:'Oʻzini chindan sinab koʻrmoqchi boʻlganlar uchun. Chet elliklarni debyutga tayyorlash tajribasiga ega lager, 10–20 ta shaxsiy mashgʻulot, sparringlar, vazn nazorati va tibbiy ruxsatnoma. Jangni zal tashkil qiladi — Puket stadionlarida yoki ichki turnirlarda. Jang kafolatlanmaydi: qachon tayyor ekaningizni murabbiy hal qiladi.',
    plan:['Baza, chidamlilik, murabbiy bahosi','Sparringlar, shaxsiy mashgʻulotlar, taktika','Jang oldidan yakuniy tayyorgarlik, vazn nazorati, tibbiy ruxsatnoma va jang','Tiklanish va jang tahlili'],
    tip:'Dastur 30 kundan uzun — viza kerak boʻladi; hujjatlarda, jumladan DTV boʻyicha yordam beramiz.' },
  'bjj-camp':{ title:'Braziliya jiu-jitsusi lageri', where:'Puket',
    short:'Yangi boshlovchilar va koʻk kamarlar uchun BJJ: ertalab — texnika, kechqurun — sparringlar, ikki shaxsiy mashgʻulot.',
    about:'Puket — Osiyodagi eng yaxshi BJJ maskanlaridan biri: bitta koʻchada qora kamarli murabbiylar ishlaydigan bir nechta zal bor. Ertalab — texnika tahlili, kechqurun — oʻz vazningizdagi sheriklar bilan sparringlar, hafta oʻrtasida — ikki shaxsiy mashgʻulot. Kimono (gi) ijaraga beriladi, lekin oʻzingiznikini olib kelgan ma’qul.',
    plan:['Zal bilan tanishuv va darajani baholash','Ertalab texnika, kechqurun sparringlar','Shaxsiy mashgʻulotlar: pozitsiyalaringiz tahlili','Yakuniy sparring va rivojlanish rejasi'] },
  'boxing-camp':{ title:'Olmaotada boks lageri', where:'Olmaota',
    short:'Qozogʻiston boks maktabi: olimpiya zaxirasi murabbiylari bilan lapa, qop va sparringlar.',
    about:'Qozogʻiston boksi — dunyodagi eng kuchli maktablardan biri, Olmaota esa uning poytaxti. Bu yerda tayyor xalqaro lagerlar deyarli yoʻq, shuning uchun dasturni oʻzimiz tuzamiz: sport maktabidan shaxsiy murabbiy, kuniga ikki sessiya, darajaga mos sparringlar, zal yonidagi mehmonxona va dam olish kuni Olatov togʻlari.',
    plan:['Uchrashuv, darajani baholash, birinchi sessiya','Kuniga ikki sessiya — texnika va juftlikda ishlash','Yakuniy sparring va togʻlarda sayr'],
    tip:'Eng yaxshi vaqt — aprel–iyun va sentabr–oktabr: qishda shaharda smog boʻladi.' },
  'mma-camp':{ title:'Professionallar yonida MMA lageri', where:'Puket',
    short:'Zarba texnikasi, kurash va parter: yirik liga jangchilari tayyorlanadigan zalda ikki hafta.',
    about:'Puketda aralash yakkakurashlar deganda professional liga jangchilari mashq qiladigan zallar tushuniladi. Siz toʻliq siklni oʻtaysiz: muay tay, kurash, BJJ, toʻr yonida ishlash va toʻrtta shaxsiy mashgʻulot. Professionallar bilan bir guruhga faqat daraja baholangach, murabbiy taklifiga koʻra qoʻshilasiz — bu haqda oldindan ochiq aytamiz.',
    plan:['Baholash va uch yoʻnalish boʻyicha asosiy darslar','Toʻliq sikl va shaxsiy mashgʻulotlar','Intensiv, sparringlar, tahlil'] },
  'mt-samui-lux':{ title:'Samui orolida muay tay va villa', where:'Samui',
    short:'Villada shaxsiy murabbiy, oshpaz va har kungi massaj. Jang — faqat xohlasangiz.',
    about:'Xususiy kurort formatidagi muay tay: hovuzli, dengiz manzarali villa, murabbiy kuniga ikki marta keladi, oshpaz yuklamaga mos taom tayyorlaydi, massaj — har oqshom. Oila bilan borayotgan boʻlsangiz yoki lager muhitidan koʻra sokinlikni qadrlasangiz, aynan siz uchun.',
    plan:['Joylashish va murabbiy bilan tanishuv','Kuniga ikki mashgʻulot, massaj, oshpaz taomlari','Yakuniy mashgʻulot va dam olish'],
    tip:'Samuida eng yaxshi oylar — yanvar–avgust; oktabr–dekabr — yomgʻirlar mavsumi.' },
  // ── Sport yigʻinlari ────────────────────────────────────────────
  'hyrox-camp':{ title:'Puketda Hyrox lageri', where:'Puket',
    short:'Eng tez ommalashayotgan fitnes-startga tayyorgarlik: yugurish, sakkizta stansiya va poyganing toʻliq simulyatsiyasi.',
    about:'Hyrox — 8 km yugurish va sakkizta funksional stansiyadan iborat poyga; unga qiziqish boshqa har qanday fitnes-startga qaraganda tezroq oʻsmoqda. Soi Ta-Iaddagi funksional trening zalida bir haftalik blok tuzamiz: stansiyalar texnikasi, temp, jaziramada ishlash va oxirida poyganing toʻliq simulyatsiyasi. Osiyoda tayyor Hyrox lagerlari deyarli yoʻq.',
    plan:['Testlar, stansiyalar texnikasi, tempda yugurish','Intervallar, aralash kombinatsiyalar, tiklanish','Vaqt oʻlchovi bilan poyganing toʻliq simulyatsiyasi','Tahlil va startingizga tayyorgarlik rejasi'],
    tip:'Eng yaxshi vaqt — havo salqinroq boʻladigan noyabr–mart.' },
  'fatloss-camp':{ title:'Puketda yogʻ yoqish lageri', where:'Puket',
    short:'Ikki hafta kardio, kuch mashqlari va muay tay — kaloriya hisobidagi ovqatlanish va oʻlchovlar bilan. Keyingi 90 kun uchun reja.',
    about:'Puketdagi fitnes-lagerlar — ritmga oson kiriladigan iqlimda kuniga 2–3 mashgʻulot. Biz koʻpchilikka yetishmaydigan narsani qoʻshamiz: ovqatlanish hisob-kitobi, ovqatni yetkazib berish, boshida va oxirida tana tarkibini oʻlchash hamda qaytgach natija yoʻqolmasligi uchun 90 kunlik reja. «Minus 10 kg» kabi va’dalar yoʻq — faqat tushunarli tizim.',
    plan:['Oʻlchovlar, konsultatsiya, boshlangʻich mashgʻulot','Aylanma, kuch, muay tay va kardio mashgʻulotlari, reja boʻyicha ratsion','Yakuniy oʻlchovlar va 90 kunlik reja'] },
  'trail-camp':{ title:'Chiang May togʻlarida treyl lageri', where:'Chiang May',
    short:'Doi Suthep va Doi Inthanon soʻqmoqlari, pastga tushish texnikasi va balandlikdagi salqin tonglar.',
    about:'Shimoliy Tailand — Doi Inthanonda 2 565 metrgacha koʻtariladigan togʻlar va shahardan toʻgʻri Doi Suthepga chiqib ketadigan soʻqmoqlar tarmogʻi. Gid bilan beshta yugurish, mamlakatning eng baland nuqtasida bir kun va har bir uzun mashgʻulotdan keyin massaj. Togʻ startiga tayyorlanish yoki yugurish zavqini qaytarish uchun ayni muddao.',
    plan:['Yengil yugurish va soʻqmoqlar bilan tanishuv','Tepalikka intervallar, pastga tushish texnikasi, uzun yugurish','Doi Inthanon — Tailandning eng baland nuqtasi','Tiklanish'],
    tip:'Faqat noyabr–yanvar: fevraldan aprelgacha shimolda dalalar yoqilishi sababli tutun mavsumi boʻladi.' },
  'tri-camp':{ title:'Puketda triatlon yigʻinlari', where:'Puket, Laguna',
    short:'50 metrli hovuz, ochiq suv, sohil boʻylab velosiped va yugurish bloklari — sprintdan 70.3 masofasigacha.',
    about:'Puketdagi Laguna hududi — Tailanddagi triatlon markazi: 50 metrli hovuz, ochiq suvda suzish uchun sokin laguna va sohil boʻylab marshrutlar. Murabbiy yuklamani masofangizga qarab belgilaydi, velosiped — ijaraga olinadi yoki oʻzingizniki, mexanik bilan. Noyabr oxirida bu yerda Laguna Phuket Triathlon oʻtkaziladi.',
    plan:['Hovuzda va velostanokda testlar','Suzish–velo–yugurish bloklari, ochiq suv','Nazorat brik mashgʻuloti va tahlil'],
    tip:'Noyabr–mart; maydan oktabrgacha gʻarbiy sohilda boʻron boʻlib turadi.' },
  'marathon-camp':{ title:'Itenda baland togʻ yigʻinlari', where:'Iten, Keniya',
    short:'Jahon chempionlari shahrida 2 400 m balandlikda mashgʻulotlar — mahalliy yuguruvchilar bilan birga.',
    about:'Itenni chempionlar uyi deyishadi: sayyoradagi eng kuchli stayerlar shu yerda yashaydi va mashq qiladi. 2 400 metr balandlikda ikki hafta, mashgʻulot markazida toʻliq pansion, keniyalik atletlar bilan guruhda yugurish, stadion va massaj. Balandlik chidamlilikni oshirishga yordam beradi, muhit esa uyda sotib olib boʻlmaydigan motivatsiya beradi.',
    plan:['Akklimatizatsiya va yengil yugurishlar','Guruhdagi mashgʻulotlar, stadion, uzun yugurishlar','Nazorat mashgʻuloti va uyga qaytish'],
    tip:'Eng qulay davrlar — yanvar–mart va iyun–oktabr; Keniyaning elektron vizasi kerak.' },
  'cycling-camp':{ title:'Mayorka yoki Jironada velosport yigʻinlari', where:'Mayorka yoki Jirona',
    short:'Togʻ koʻtarilishlari, guruh boʻlib chiqishlar, mexanik va kuzatuv mashinasi.',
    about:'Mayorka va Jirona — professional jamoalar bahorda mashq qilish uchun boradigan joylar. Gid guruhni eng yaxshi marshrutlar boʻylab olib boradi, kuzatuv mashinasi suv va ehtiyot qismlarni tashiydi, mexanik velosipedni tayyorlaydi. Yarim pansionli mehmonxona va uzun kunlardan keyin massaj.',
    plan:['Velosipedni moslash va yengil chiqish','80–140 km marshrutlar, koʻtarilishlar, guruhda haydash','Erkin chiqish va dam olish'],
    tip:'Fevral–may va sentabr–oktabr. Shengen vizasi kerak.' },
  'strength-40':{ title:'Dubayda 40+ kuch lageri', where:'Dubay',
    short:'Kuch, harakatchanlik, tahlillar va sport shifokoridan protokol — qirqdan oshgan erkaklar uchun besh kun.',
    about:'Qirqdan keyin «yigirma yoshdagidek» mashq qilish — jarohatga olib boradigan toʻgʻri yoʻl. Sertifikatlangan murabbiy va sport shifokori bilan besh kun: tana tarkibini baholash (DEXA), tahlillar, harakatchanlik, kuniga ikki mashgʻulot va fizioterapiya. Natijada — bir yilga moʻljallangan mashgʻulot va tiklanish protokoli.',
    plan:['DEXA, tahlillar, shifokor konsultatsiyasi','Kuniga ikki mashgʻulot, harakatchanlik, fizioterapiya','Yakuniy konsultatsiya va bir yillik protokol'],
    tip:'Noyabr–mart — Dubayda mashq qilish qulay boʻlgan payt.' },
  'altitude-camp':{ title:'Kavkazda baland togʻ yigʻinlari', where:'Tsaxkadzor yoki Kislovodsk',
    short:'Chidamlilik uchun oʻrta balandlikdagi togʻlar: olimpiya markazlarida yugurish, velo va hovuz.',
    about:'Armanistondagi Tsaxkadzor (taxminan 1 850 m) — terma jamoalar mashq qiladigan olimpiya bazasi: stadion, hovuz va soʻqmoqlar. Kislovodsk pastroqda (900–1 400 m) joylashgan va yumshoq moslashish uchun qulay. Murabbiy, yarim pansion, massaj va startingizga moslangan yuklama rejasi.',
    plan:['Balandlikka moslashish','Asosiy blok — yugurish, velo, suzish','Nazorat mashgʻuloti'], tip:'Iyun–sentabr.' },
  'ski-camp':{ title:'Murabbiy bilan togʻ changʻisi lageri', where:'Gudauri yoki Shimbulak',
    short:'Gid bilan karving yoki frirayd. Ski-pass, jihozlar ijarasi va kuniga ikki soat murabbiy bilan.',
    about:'Shaxsiy murabbiy bilan togʻlarda bir hafta: har kuni ikki soatlik mashgʻulot, texnikani video-tahlil qilish, qolgan vaqt — erkin uchish. Gruziyadagi Gudauri frirayd va quyoshli kunlari bilan mashhur, Shimbulak — Olmaotadan 30 daqiqalik masofadagi trassalari bilan. Ski-pass, jihozlar ijarasi va yarim pansionli mehmonxona narxga kiritilgan.',
    plan:['Darajani baholash, jihozlarni moslash','Murabbiy bilan ikki soat, uchish, video-tahlil','Erkin uchish'],
    tip:'Dekabr–mart. Gruziyaga safar uchun sugʻurta kerak boʻlishi mumkin.' },
  // ── Tibbiy koʻrik va uzoq umr ───────────────────────────────────
  'checkup-bkk':{ title:'Bangkokda Executive check-up', where:'Bangkok',
    short:'Xalqaro shifoxonada bir kunda toʻliq tekshiruv. Xulosa tarjimasi oʻzbek yoki rus tilida, mehmonxona va transferlar.',
    about:'Bangkok shifoxonalari — dunyodagi tibbiy turizmning asosiy markazlaridan biri; yetakchilari JCI akkreditatsiyasiga ega va paket narxlarini e’lon qiladi. 40+ yoshdagi erkaklar paketi odatda tahlillar va onkomarkerlar (jumladan PSA), EKG, yuklama testi, qorin boʻshligʻi UZI, rentgen va oʻsha kuni shifokor qabulini oʻz ichiga oladi. Shifoxona va paketni tanlaymiz, qabulga yozamiz, kutib olamiz, xulosani tarjima qilamiz va harakat rejasini tuzamiz.',
    plan:['Arafasida: tayyorgarlik boʻyicha yoʻriqnoma va mehmonxonaga transfer','Tekshiruv kuni: 4–8 soat, nahorga, koordinator yoningizda','Natijalarni shifokor bilan koʻrib chiqish','Xulosa tarjimasi va harakat rejasi'],
    tip:'Shifoxonalarning aksiya narxlari ba’zan faqat rezidentlar uchun amal qiladi — biz chet ellik bemor uchun yozma tasdiq olamiz.' },
  'mens-health':{ title:'Erkaklar salomatligi: urolog, gormonlar, prostata', where:'Bangkok',
    short:'Urolog-androlog, gormonal profil, PSA va UZI — noqulayliksiz, xotirjam suhbat.',
    about:'Erkaklar yillab paysalga soladigan tekshiruv. Urolog-androlog qabuli, gormonal panel (umumiy va erkin testosteron, SHBG, LH/FSH, prolaktin, estradiol, TSH), PSA, buyrak va prostata UZI, urofloumetriya. Barcha tayinlovlarni faqat shifokor koʻrikdan keyin qiladi; biz tashkil qilamiz, hamrohlik qilamiz va tarjima qilamiz.',
    plan:['Nahorga tahlil topshirish','Koʻrik, UZI, urofloumetriya','Natijalarni koʻrib chiqish va shifokor tavsiyalari'],
    tip:'Gormonal preparatlar — faqat shifokor tayinlovi bilan; biz dori vositalarini sotmaymiz va joʻnatmaymiz.' },
  'longevity-week':{ title:'Uzoq umr haftasi: check-up va protokol', where:'Bangkok va Puket',
    short:'Check-up, biologik yosh, VO2max hamda bir yillik uyqu, ovqatlanish va mashgʻulot rejasi.',
    about:'Organizmingiz qanday qarib borayotganini va bu borada nima qilish kerakligini tushunish uchun yetti kun. Bangkok shifoxonasida kengaytirilgan check-up, biologik yosh testi, VO2max kardiopulmonal testi, tana tarkibi, shifokor va nutritsiolog konsultatsiyalari. Haftaning ikkinchi yarmi — Puket kurortida: yangi rejimni mutaxassislar kuzatuvida boshlaysiz. Biologik yosh — tashxis emas, moʻljal: «yosharish»ni va’da qilmaymiz.',
    plan:['Bangkokda check-up, VO2max va tahlillar','Natijalarni shifokor bilan koʻrib chiqish','Puketdagi kurort: uyqu, mashgʻulotlar, ovqatlanish','Bir yillik protokol va nazorat nuqtalari'] },
  'heart-check':{ title:'Kardio check-up va sportga ruxsat', where:'Bangkok',
    short:'EKG, yuklama testi, exokardiografiya va kalsiy indeksi — yuguradigan va jang qiladiganlar uchun.',
    about:'Marafon, jang yoki choʻqqiga chiqishdan oldin yurak yuklama ostida qanday ishlashini bilgan ma’qul. Ixtisoslashgan kardiomarkazdagi dastur: EKG, stress-test yoki stress-exo, exokardiografiya, KT yordamida kalsiy indeksini baholash, lipid profili va kardiolog xulosasi. Agar biror narsa aniqlansa, keyingi muolajalar alohida va faqat sizning roziligingiz bilan kelishiladi.',
    plan:['Tahlillar va EKG','Yuklama testi va exokardiografiya','Kalsiy indeksi uchun KT','Kardiolog xulosasi va ruxsatnoma'] },
  'sleep-lab':{ title:'Uyqu laboratoriyasi', where:'Bangkok',
    short:'Tunab qolib polisomnografiya: apnoe, xurrak, uyqu sifati va tiklanish rejasi.',
    about:'Agar charchab uygʻonsangiz, xurrak otsangiz yoki turmush oʻrtogʻingiz nafasingiz toʻxtab qolishini sezsa — bu uyquni tekshirish uchun asos. Uyqu laboratoriyasida polisomnografiya bilan bir kecha, somnolog konsultatsiyasi va reja. Apnoe gumon qilinsa, shifokor CPAP apparatini moslash uchun ikkinchi kechani taklif qilishi mumkin.',
    plan:['Kechqurun: laboratoriyaga joylashish va datchiklar','Tun: kuzatuv ostida uyqu yozuvi','Ertalab: somnolog konsultatsiyasi va reja'] },
  'dna-plan':{ title:'DNK-test va shaxsiy reja', where:'Onlayn, toʻplam pochta orqali',
    short:'Ovqatlanish, sport va xavflar genetikasi — shifokor-genetik bilan rus tilida tahlil.',
    about:'Soʻlak namunasi uchun toʻplam uyingizga yetkaziladi, natija — 4–10 haftada. Shifokor-genetik bilan tahlil: modda almashinuvi xususiyatlari, yuklamaga javob, irsiy xavflar va ulardan qaysilarini haqiqatan hisobga olish kerakligi. DNK-test — tashxis emas, biz ilm qayerda tugab, marketing qayerda boshlanishini ochiq aytamiz.',
    plan:['Toʻplamni buyurtma qilish va yetkazib berish','Laboratoriya tahlili: 4–10 hafta','Shifokor-genetik bilan tahlil va reja'],
    tip:'Genetik ma’lumotlar — shaxsga doir ma’lumotlarning maxsus toifasi; faqat yozma roziligingiz bilan ishlaymiz.' },
  'biohack-week':{ title:'Dubayda biohaking haftasi', where:'Dubay',
    short:'Barokamera, krioterapiya, tahlillar asosida infuziyalar va HRV nazorati — shifokorlar kuzatuvida.',
    about:'Dubayning litsenziyali klinikalarida besh kun: shifokor koʻrigi va tahlillar, har kuni giperbarik oksigenatsiya va krioterapiya seanslari, infuziyalar faqat shifokor tayinlovi bilan, tiklanish va yakuniy reja. Moʻjiza va’da qilmaymiz: koʻplab muolajalarning ilmiy asosi zaif, shuning uchun qarorlarni shifokor qabul qiladi, siz esa haqqoniy manzarani olasiz.',
    plan:['Shifokor, tahlillar, qarshi koʻrsatmalarni tekshirish','Barokamera, krioterapiya, tiklanish','Yakuniy konsultatsiya va reja'],
    tip:'Noyabr–mart. BAAga koʻplab dori vositalarini olib kirish uchun ruxsat talab qilinadi.' },
  'seoul-checkup':{ title:'Seulda check-up', where:'Seul',
    short:'Koreya tibbiyoti: ikki kunda MRT va endoskopiya bilan kengaytirilgan check-up.',
    about:'Seulning yetakchi shifoxonalari dunyodagi eng batafsil check-uplardan birini oʻtkazadi: tahlillar, sedatsiya ostida endoskopiya, KT va MRT, kardiodiagnostika va natijalar boʻyicha konsultatsiya — ikki kunda. Koreyada roʻyxatdan oʻtgan tibbiy turizm agentlari orqali ishlaymiz.',
    plan:['Tahlillar, vizualizatsiya, endoskopiya','Shifoxona yoki mehmonxonada tunash','Kardiodiagnostika va natijalar boʻyicha konsultatsiya'],
    tip:'Eng yaxshi vaqt — bahor va kuz.' },
  // ── Detoks va yangilanish ───────────────────────────────────────
  'detox-samui':{ title:'Samui orolida detoks-retrit', where:'Samui',
    short:'Toza ovqatlanish, yoga, massaj, sauna va nutritsiolog — dengiz boʻyida bir haftalik yangilanish.',
    about:'Samui — klassik velnes-retritlar oroli. Sokinlikda bir hafta: sharbatlar yoki yengillashtirilgan ovqatlanish, har kuni massaj, yoga va sauna, nutritsiolog konsultatsiyasi. «Detoks»ga halol yondashamiz: bu rejimni yangilash, «toksinlarni chiqarish» emas. Formatni sokin butik-retritdan tortib flagman kurortlargacha tanlaymiz.',
    plan:['Konsultatsiya va dastur','Dastur boʻyicha ovqatlanish, massaj, yoga, sauna','Dasturdan chiqish va ovqatlanish rejasi'],
    tip:'Yanvar–sentabr; oktabr–dekabrda Samuida yomgʻir yogʻadi. Ochlik hammaga ham toʻgʻri kelmaydi — oldindan tekshiramiz.' },
  'weight-reset':{ title:'Vaznni joyidan qoʻzgʻatish: 21 kun', where:'Puket',
    short:'Shifokor, nutritsiolog, murabbiy va tushunarli reja. Oldin va keyin oʻlchovlar, 90 kunlik koʻmak.',
    about:'Vaznni oʻlik nuqtadan siljitish uchun uch hafta. 40+ yoshdagi erkaklar uchun dastlabki koʻrik va EKG, kuniga 2–3 mashgʻulot, yetkazib beriladigan ratsion va har hafta tana tarkibini oʻlchash. Keyin — 90 kun onlayn hamrohlik. Vazn kamaytiruvchi preparatlar faqat shifokor bilan muhokama qilinadi va dasturga kirmaydi.',
    plan:['Koʻrik, EKG, oʻlchovlar va reja','Mashgʻulotlar, ratsion va haftalik oʻlchovlar','Yakuniy oʻlchovlar va 90 kunlik reja'],
    tip:'21 kun 30 kunlik vizasiz muddatga sigʻadi; Oʻzbekiston fuqarolariga esa viza (e-Visa) kerak — rasmiylashtirishda yordam beramiz.' },
  'sober-retreat':{ title:'Hushyorlik retriti: alkogolsiz 14 kun', where:'Bali',
    short:'Erkaklar guruhi, sport, psixolog bilan ishlash va yangi odatlar — nasihatbozliksiz.',
    about:'Bu klinika ham, «davolash» ham emas — alkogolsiz hayotni ichkaridan koʻrish uchun ikki hafta: guruh, sport, guruhiy va individual sessiyalar, ovqatlanish va uyqu. Boshlashdan oldin — soʻrovnoma: agar qaramlik kuchli boʻlsa, tibbiy detoks qiladigan klinikaga yoʻnaltiramiz, chunki keskin toʻxtatish xavfli boʻlishi mumkin.',
    plan:['Safardan oldin soʻrovnoma va qoʻngʻiroq','Rejim, sport va guruh','Yangi odatlar va uy uchun reja','Qaytgach onlayn koʻmak'] },
  'digital-detox':{ title:'Khao Sok changalzorlarida raqamli detoks', where:'Khao Sok, suzuvchi uy',
    short:'Aloqa yoʻq — koʻl, qoyalar, sokinlik va tong sahardagi baliq ovi bor.',
    about:'Ohaktosh qoyalar orasidagi Cheow Lan koʻli — Tailandning eng goʻzal joylaridan biri. Suzuvchi uyda toʻrt kun: kayaklar, gʻorlar, changalzorda sayr va longteyl qayigʻidan ertalabki baliq ovi. Telefon butun muddat seyfda turadi: ba’zi uylarda 4G allaqachon ushlaydi, shuning uchun rejimni oʻzimiz belgilaymiz.',
    plan:['Transfer, longteyl, joylashish','Kayaklar, gʻorlar, changalzor va baliq ovi','Koʻlda tong va qaytish'], tip:'Dekabr–aprel.' },
  'fasting':{ title:'Shifokorlar nazoratida ochlik kursi', where:'Germaniya yoki Avstriya',
    short:'Klassik ochlik klinikalari: shifokor nazorati, muolajalar va toʻgʻri chiqish.',
    about:'Yevropa ochlik klinikalari oʻn yillardan beri Buxinger va Mayr usullari asosida ishlaydi: koʻrik va tahlillar, har kuni shifokor nazorati, muolajalar va ovqatlanishga bosqichma-bosqich qaytish. Biz klinikani bron qilamiz, viza va transferlarda yordam beramiz. Ayrim holatlarda ochlik mumkin emas — klinika buni boshlashdan oldin tekshiradi.',
    plan:['Safardan oldin klinika soʻrovnomasi','Koʻrik, tahlillar, tayyorgarlik','Shifokor kuzatuvidagi dastur','Ochlikdan chiqish va tavsiyalar'],
    tip:'2–4 oy oldin bron qilish kerak; Shengen vizasi zarur.' },
  'ayurveda':{ title:'Ayurveda: Keralada panchakarma', where:'Kerala, Hindiston',
    short:'Ayurveda markazida an’anaviy tozalash dasturi — 14 kun.',
    about:'Kerala — ayurveda vatani. Akkreditatsiyadan oʻtgan markazda ikki hafta: ayurveda shifokori koʻrigi, tayyorgarlik, panchakarmaning asosiy muolajalari, ovqatlanish va yoga. Akkreditatsiyaga ega markazlarni tanlaymiz va tarkibi tekshirilmagan dori-darmonlarni uyga olib ketishni maslahat bermaymiz.',
    plan:['Koʻrik va tayyorgarlik bosqichi','Asosiy muolajalar','Tiklanish va tavsiyalar'],
    tip:'An’anaga koʻra eng yaxshi vaqt — musson (iyun–sentabr) yoki quruq mavsum (noyabr–mart).' },
  'burnout':{ title:'Toliqishdan chiqish retriti', where:'Chiang May',
    short:'Uyqu, togʻlar, psixolog, tana amaliyotlari va ishga qaytish rejasi.',
    about:'Toʻyib uxlash, nafasni rostlash va nimani oʻzgartirish kerakligini tushunish uchun oʻn kun. Holat skriningi, har kuni individual sessiyalar, tana amaliyotlari, meditatsiya, togʻlarda sayr va ishga qaytish rejasi. Toliqish (burnout) — tashxis emas, lekin depressiya belgilari boʻlsa, tegishli mutaxassislarni jalb qilamiz.',
    plan:['Skrining, uyqu va rejim','Sessiyalar, amaliyotlar va togʻlar','Ishga qaytish rejasi'],
    tip:'Oktabr–yanvar: fevraldan aprelgacha Chiang Mayda havo tutunli boʻladi.' },
  // ── Tiklanish ───────────────────────────────────────────────────
  'sauna-ice':{ title:'Sauna va muzli vanna: kurs', where:'Puket',
    short:'Kontrast protokollar, nafas mashqlari va HRV oʻlchovlari. Parvozdan keyin qilish mumkin boʻlgan eng yaxshi narsa.',
    about:'Kontrast terapiya studiyasida beshta sessiya: sauna, muzli vanna, nafas amaliyotlari va soatingizda yurak urishi oʻzgaruvchanligini (HRV) kuzatish. Mashgʻulotlar va parvozdan keyin tiklanishga yordam beradi. Kursdan oldin — qisqa soʻrov: yurak va qon bosimi bilan muammo boʻlsa, sovuq hammaga ham toʻgʻri kelmaydi.',
    plan:['Yoʻriqnoma va yumshoq protokol','Sovuqda koʻproq vaqt, nafas amaliyotlari','Yakuniy HRV oʻlchovlari'] },
  'thai-massage':{ title:'Chiang Mayda tay massaji va choʻzilish', where:'Chiang May',
    short:'Eski maktab ustalaridan har kuni ikki soatlik massaj va bel uchun choʻzilish mashqlari.',
    about:'Chiang May — an’anaviy tay massaji poytaxti. Eski maktab ustalari qoʻlida besh kun, har kuni ikki soatdan: bel va chanoq-son boʻgʻimlari bilan ishlash, choʻzilish. Oʻzingiz oʻrganmoqchi boʻlsangiz — an’anaviy tibbiyot shifoxonasi qoshidagi maktabga kursga yozdiramiz.',
    plan:['Baholash va yumshoq massaj','Chuqur ishlov va choʻzilish','Yakuniy seans va uy uchun mashqlar'], tip:'Noyabr–fevral.' },
  'sports-recovery':{ title:'Sport tiklanishi', where:'Puket',
    short:'Fizioterapevt, sport massaji, harakatchanlik va sovuq — jang qilgani kelib, haddan oshirib yuborganlar uchun.',
    about:'Lager, marafon yoki jarohatdan keyin bir haftalik tiklanish: fizioterapevt bilan toʻrtta sessiya, beshta sport massaji, kontrast muolajalar va harakatchanlik mashgʻulotlari. Zarur boʻlsa, turar joyni ham qoʻshish mumkin.',
    plan:['Fizioterapevt koʻrigi','Massaj, harakatchanlik, sovuq','Yakuniy baho va mashqlar'] },
  'spa-week':{ title:'Balida erkaklar spa-haftasi', where:'Bali',
    short:'Hovuzli villa, har kungi muolajalar, egiluvchan boʻlmaganlar uchun yoga va sokinlik.',
    about:'Bali massaji, Ubudning sholi terrasalari orasidagi villa, hech qachon yoga qilmaganlar uchun yoga va muolajalardan boshqa hech qanday jadval yoʻq. Ogʻir yildan keyin yoki ikki loyiha oraligʻida ayni muddao.',
    plan:['Joylashish va birinchi massaj','Muolajalar, yoga va sayr','Joʻnab ketish'], tip:'Aprel–oktabr — quruq mavsum.' },
  'onsen':{ title:'Yaponiya onsenlari va ryokanlari', where:'Hakone va Kioto',
    short:'Issiq buloqlar, kayseki kechki ovqati va hayotingizdagi eng yaxshi uyqu. Narx — bir kishi uchun.',
    about:'Hakonedagi xususiy onsenli va togʻ manzarali ryokanda ikki tun, Kiotoda yana ikki tun, oraliqda poyezd va gid bilan bir kun. Yaponcha hammom va kayseki kechki ovqati marosimi har qanday spadan yaxshiroq yangilaydi. Narx ikki kishilik xonada bir kishi uchun koʻrsatilgan.',
    plan:['Hakone: ryokan va onsen','Kiotoga koʻchish','Gid bilan ibodatxonalar va ryokan'],
    tip:'Noyabr, mart oxiri–aprel; yanvar–fevralda narxlar eng qulay. Tatuirovkasi borlarni umumiy hammomlarga koʻpincha kiritishmaydi.' },
  'banya':{ title:'Bugʻ ustasi bilan rus hammomi', where:'Moskva viloyati yoki Oltoy',
    short:'Haqiqiy bugʻlanish, sovuq hovuzcha, giyohli choy va massaj — ikki kun.',
    about:'Usta qoʻlida bugʻlanish — oddiy hammom emas: venik supurgilar, harorat, ritm va sovuq hovuzcha sizga moslab tanlanadi. Bugʻ ustasi bilan ikki seans, massaj, shahar tashqarisidagi majmuada bir tun va transferlar.',
    plan:['Kelish, birinchi seans va kechki ovqat','Ikkinchi seans, massaj va joʻnash'], tip:'Oktabr–mart.' },
  'dead-sea':{ title:'Oʻlik dengiz: bel va boʻgʻimlar', where:'Iordaniya',
    short:'Quruqlikning eng past nuqtasida loy muolajalari, mineral suv va fizioterapiya.',
    about:'Dengiz sathidan taxminan 430 metr pastda: zich suv, mineral loy va oʻziga xos havo. Spa-mehmonxonada yetti tun, shifokor koʻrigi, oltita muolaja va uchta fizioterapiya seansi. Ta’siri eng yaxshi teri kasalliklarida oʻrganilgan; boʻgʻimlar uchun ilmiy asos oʻrtacha va biz buni ochiq aytamiz.',
    plan:['Shifokor koʻrigi va dastur','Muolajalar va fizioterapiya','Xulosa va tavsiyalar'], tip:'Oktabr–aprel.' },
  // ── Ong va xotirjamlik ──────────────────────────────────────────
  'silent-retreat':{ title:'Sokin retrit: 10 kunlik meditatsiya', where:'Chiang May',
    short:'Meditatsiya, sukut va oddiy taom. Yoʻl va hamrohlikni oʻz zimmamizga olamiz.',
    about:'Klassik oʻn kunlik meditatsiya kurslari (masalan, Goenka an’anasidagi vipassana) bepul, xayriyalar hisobiga oʻtkaziladi — va shunday qolishi kerak. Shuning uchun kursning oʻzini sotmaymiz: markazni tanlash va yozilishda yordam beramiz, transfer, kursdan oldin va keyin mehmonxona hamda chiqishda kutib olishni tashkil qilamiz. Yumshoqroq formatni istaganlar uchun — ustoz bilan xususiy retrit ($1 500 dan).',
    plan:['Markaz tanlash va yozilish','Transfer va start oldidan tun','Oʻn kunlik kurs','Kutib olish, dam olish va keyingi suhbat'],
    tip:'Intensiv meditatsiya hammaga ham toʻgʻri kelmaydi — ruhiy salomatligingiz xususiyatlari haqida oldindan xabar bering.' },
  'breathwork':{ title:'Balida nafas va sovuq', where:'Bali',
    short:'Nafas amaliyotlari, muzdek suv va stress bilan ishlash — besh kun.',
    about:'Sertifikatlangan instruktor bilan besh kunlik nafas va kontrast sovuq amaliyotlari, yoga, sauna va sokin villa. Xavfsizlik qoidasi: nafasni ushlab turish amaliyotlari hech qachon suvda yoki suv yonida bajarilmaydi. Boshlashdan oldin — salomatlik soʻrovnomasi.',
    plan:['Asoslar va xavfsizlik','Amaliyotlar, muz va sauna','Integratsiya va uy uchun reja'] },
  'mens-retreat':{ title:'Oltoyda erkaklar retriti', where:'Oltoy',
    short:'Erkaklar guruhi, togʻlar, gulxan, hammom va boshlovchi bilan samimiy suhbatlar.',
    about:'Kichik erkaklar guruhi bilan Oltoy togʻlarida besh kun: piyoda yurishlar, rafting, hammom, tajribali boshlovchi bilan gulxan atrofidagi kechki davralar. Odatda ichda saqlanadigan narsalarni ovoz chiqarib muhokama qilmoqchi boʻlganlar uchun format — oʻzingiz kabi erkaklar davrasida.',
    plan:['Guruh yigʻilishi va baza','Yurishlar, rafting, hammom va davralar','Yakun'],
    tip:'Iyun–sentabr. Kana ensefalitiga qarshi emlash kerak; ba’zi hududlar — chegara zonasi.' },
  'coaching':{ title:'Samaradorlik kouchingi', where:'Onlayn',
    short:'Maqsadlar, energiya va fokus: biznes egalari bilan ishlagan kouch bilan oltita sessiya.',
    about:'ICF sertifikatiga ega kouch bilan 60 daqiqalik oltita video-sessiya: diagnostika, chorak uchun maqsadlar, energiya rejimi, vakolatlarni topshirish, fokus. Sessiyalar orasida — messenjerda aloqa. Kouching psixoterapiya emas: ruhiy holat ustida ishlash kerak boʻlsa, psixologni jalb qilamiz.',
    plan:['Diagnostika va maqsadlar','Reja boʻyicha ishlash','Natijalar va keyingi chorak rejasi'] },
  'monk-week':{ title:'Buddaviy monastirda bir hafta', where:'Shimoliy Tailand',
    short:'Erta turish, meditatsiya, mehnat va sokinlik. Yoʻl va tayyorgarlik — bizning zimmamizda.',
    about:'Monastirda yashash — turistik mahsulot emas va biz uni sotmaymiz: sizni qabul qilish-qilmaslikni monastir boshligʻi hal qiladi, xayriyani oʻzingiz topshirasiz. Sizni safarga tayyorlaymiz, qoidalarni tushuntiramiz (sakkiz ahd, tushdan keyin ovqat yoʻq, telefonsiz), Chiang Maydan mashina, oldin va keyin mehmonxona hamda oq kiyimni tashkil qilamiz.',
    plan:['Tayyorgarlik: qoidalar va odob','Transfer va Chiang Mayda bir tun','Monastirda besh kun','Qaytish va dam olish'], tip:'Noyabr–yanvar.' },
  'psychologist':{ title:'Erkaklar uchun psixolog', where:'Onlayn',
    short:'Inqiroz, ajrim, xavotir, gʻazab — erkaklarni tushunadigan psixolog bilan sakkizta sessiya.',
    about:'Psixologni soʻrovingiz va muloqot uslubingizga qarab tanlaymiz: onlayn, rus tilida 50 daqiqalik sakkizta sessiya. Psixolog shifokor emas: davolash zarur boʻlsa, psixoterapevtga yoʻnaltiramiz. Oʻtkir holatlar uchun inqiroz protokoli mavjud.',
    plan:['Soʻrovnoma asosida mutaxassis tanlash','Haftada bir sessiya','Xulosa va tavsiyalar'] },
  'meditation-21':{ title:'Band odamlar uchun meditatsiya: 21 kun', where:'Onlayn',
    short:'Ustoz bilan kuniga oʻn daqiqa va rivojlanishni kuzatish.',
    about:'Yigirma bitta qisqa amaliyot, uchta jonli guruh sessiyasi va ustoz bilan chat. Togʻlarga ketmasdan, fikrni boshqa narsaga oʻtkazishni oʻrganish va yaxshiroq uxlashni istaganlar uchun.',
    plan:['Kirish sessiyasi','Har kuni 10 daqiqalik amaliyot','Yakuniy sessiya'] },
  // ── Sarguzashtlar ───────────────────────────────────────────────
  'elbrus':{ title:'Elbrusga chiqish', where:'Kavkaz',
    short:'Yevropaning eng baland nuqtasi — 5 642 m — akklimatizatsiya, gidlar va zaxira kun bilan.',
    about:'Klassik janubiy marshrut boʻyicha koʻtarilish: gidlar bilan sakkiz kun, 4 000 metrdan yuqoriga akklimatizatsiya chiqishlari, boshpanalar, xohishga koʻra ratrakda yuqoriga chiqarib qoʻyish va choʻqqini zabt etish. Marshrut texnik jihatdan murakkab emas, lekin choʻqqidagi ob-havo xavfli — shuning uchun qarorlarni gid qabul qiladi, zaxira kun esa majburiy.',
    plan:['Kelish va Chegetda akklimatizatsiya','4 000 m dan yuqoriga chiqishlar va boshpana','Choʻqqini zabt etish va zaxira kun','Pastga tushish va uyga qaytish'],
    tip:'Iyun–sentabr. Chet elliklar uchun: xorijiy kartalar Rossiyada ishlamaydi, jumladan Oʻzbekiston banklarining Visa/Mastercard kartalari ham; gʻarb sugʻurtalari koʻpincha bu safarni qoplamaydi.' },
  'kilimanjaro':{ title:'Machame marshruti boʻyicha Kilimanjaro', where:'Tanzaniya',
    short:'Afrika tomi — 5 895 m. Gidlar, hammollar, lagerlar va xohishga koʻra safari.',
    about:'Machame — Kilimanjaroga olib boradigan eng manzarali, akklimatizatsiya uchun qulay marshrut: beshta iqlim zonasi orqali koʻtarilish va Uhuru choʻqqisiga tungi hal qiluvchi yurish. Park yigʻimlari, gidlar, hammollar, chodirlar, ovqatlanish va Moshida ikki tun narxga kiritilgan. Koʻtarilishdan keyin safari — gʻalabani nishonlashning eng yaxshi usuli.',
    plan:['Moshi va brifing','Lagerlar orqali Machame marshruti','Uhuruni zabt etish va pastga tushish','Sertifikat va dam olish'],
    tip:'Yanvar–mart va iyun–oktabr; aprel–may va noyabrda yomgʻirlar boʻladi. Park yigʻimlari vaqti-vaqti bilan oʻzgaradi — bron qilishda aniqlashtiramiz.' },
  'ebc':{ title:'Everest tayanch lageriga trekking', where:'Nepal',
    short:'Lukla, Namche-Bazar, 5 364 m. Lojlar, litsenziyali gid va hammollar.',
    about:'Khumbu vodiysida klassik trekking: Luklaga parvoz, Namche-Bazar, Tengboche monastiri va 5 364 m balandlikdagi Everest tayanch lageri. Nepal qoidalariga koʻra litsenziyali gid majburiy, hammol — ikki kishiga bitta. Qizgʻin mavsumda Luklaga reyslar Ramechhapdan uchadi — zaxira kunlarni rejaga kiritamiz.',
    plan:['Katmandu va Luklaga parvoz','Akklimatizatsiya bilan Namche va Tengboche orqali koʻtarilish','Tayanch lager va Kala-Patthar','Pastga tushish va Katmandu'],
    tip:'Mart–may va oktabr–noyabr. Vertolyotda evakuatsiyani qoplaydigan sugʻurta kerak.' },
  'kamchatka':{ title:'Kamchatka: vulqonlar va baliq ovi', where:'Kamchatka',
    short:'Geyzerlar vodiysiga vertolyot, vulqonga chiqish, daryoda losos ovi.',
    about:'Dunyoning chekkasida oʻn kun: Avachinskiy yoki Goreliy vulqoniga chiqish, Geyzerlar vodiysi va Uzon kalderasiga qoʻnib oʻtadigan vertolyot kuni, Bistraya daryosida rafting va baliq ovi. Vertolyot parvozlari ob-havoga bogʻliq — dasturdagi ikki kun moslashuvchan.',
    plan:['Yetib kelish va termal buloqlar','Vulqonga chiqish','Geyzerlar vodiysiga vertolyot (ob-havoga qarab)','Rafting va baliq ovi'], tip:'Iyul–sentabr.' },
  'moto-north':{ title:'Shimoliy Tailand boʻylab moto-tur', where:'Mae Hong Son halqasi',
    short:'1 864 ta burilish, togʻlar, tuman va togʻ lojlarida tunash.',
    about:'Afsonaviy Mae Hong Son halqasi: gid va yordamchi mashina bilan enduro yoki turistik mototsiklda yetti kun, togʻ dovonlari, qishloqlar va vodiylar uzra tumanlar. A toifali haydovchilik guvohnomasi va «A» belgili xalqaro guvohnoma kerak — ularsiz sugʻurta amal qilmaydi.',
    plan:['Chiang May va mototsikl tanlash','Pai va Mae Hong Son orqali halqa','Chiang Mayga qaytish'],
    tip:'Noyabr–fevral; mart–aprelda tutun, iyun–oktabrda yomgʻirlar.' },
  'safari':{ title:'Keniya va Tanzaniyada safari', where:'Masai-Mara va Serengeti',
    short:'Buyuk migratsiya, lojlar va eng yaxshi gidlar — sakkiz kun.',
    about:'Tomi ochiladigan jipda Masai-Mara va Serengeti boʻylab sakkiz kun: gnu antilopalari migratsiyasi, Mara daryosidan kechib oʻtishlar, «katta beshlik». Toʻliq pansionli lojlar, park yigʻimlari va mamlakatlar oʻrtasidagi koʻchish narxga kiritilgan. Kechuvlarni hech kim kafolatlamaydi — ammo gidlar qayerda kutish kerakligini biladi.',
    plan:['Masai-Mara','Tanzaniyaga oʻtish','Serengeti va Ngorongoro krateri','Uchib ketish'],
    tip:'Iyul–oktabr — Marada migratsiya; yanvar–fevral — janubiy Serengetida bolalash mavsumi.' },
  'railay-climb':{ title:'Reylida qoyaga tirmashish', where:'Krabi',
    short:'Dengiz uzra ohaktosh qoyalar. Noldan pastki himoya (lead) bilan ilk marshrutgacha.',
    about:'Reyli — Osiyoda qoyaga tirmashish uchun eng yaxshi hududlardan biri: ohaktosh devorlar toʻgʻridan-toʻgʻri plyaj ustida. Instruktor bilan uch kunlik kurs — yuqori himoyadan (top-rope) pastki himoya (lead) bilan ilk marshrutgacha, shuningdek faqat qayiqda borish mumkin boʻlgan Reylida uch tun.',
    plan:['Texnika va yuqori himoya','Pastki himoya va pastga tushish','Pastki himoya bilan ilk marshrut'], tip:'Noyabr–aprel.' },
  'altai-horse':{ title:'Oltoy boʻylab otda sayohat', where:'Oltoy',
    short:'Dovonlar, togʻ koʻllari va chodirlarda tunash — egarda yetti kun.',
    about:'Togʻli Oltoy boʻylab egarda bir hafta: dovonlar, muzlik koʻllari, chodirlarda va turbazalarda tunash, toʻliq pansion va tajribali yoʻlboshchilar. Ot minish tajribasi shart emas — otlar chavandozga moslab tanlanadi. Beluxa tomon marshrutlar uchun chegara zonasiga ruxsatnoma kerak, uni oldindan rasmiylashtiramiz.',
    plan:['Baza va yoʻriqnoma','Dovonlar va koʻllar orqali marshrut','Qaytish'], tip:'Iyun oxiri — sentabr boshi.' },
  'uzbek-mountains':{ title:'Oʻzbekiston togʻlari: Chimyon va Pskom', where:'Oʻzbekiston',
    short:'ERKAK vatani: trekking, togʻ daryolari va gulxan yonida palov.',
    about:'Toshkentdan ikki soatlik masofadagi Gʻarbiy Tyan-Shanda olti kun: Katta Chimyon (3 309 m), Beldersoy va Pskom daralari, chodirlarda va mehmon uylarida tunash. ERKAK mumiyosi aynan shu togʻlardan olinadi. Qirgʻiziston chegarasi yaqinidagi marshrutlar uchun ruxsatnoma kerak — rasmiylashtiramiz.',
    plan:['Toshkent va togʻlarga yoʻl','Chimyon va Pskom boʻylab trekking','Qaytish'], tip:'Iyun–sentabr.' },
  // ── Okean ───────────────────────────────────────────────────────
  'padi-ow':{ title:'Noldan dayving: PADI Open Water', where:'Puket',
    short:'Toʻrt kunda xalqaro sertifikat. Ilk shoʻngʻishlar — Racha orollari yonida.',
    about:'PADI Open Water kursi: nazariya, hovuz va qayiqdan ochiq suvga toʻrtta shoʻngʻish. Sertifikat butun dunyoda amal qiladi va 18 metrgacha shoʻngʻish imkonini beradi. Dayv-markaz yonidagi mehmonxonada uch tun narxga kiritilgan. Kursdan oldin — tibbiy soʻrovnoma; oxirgi shoʻngʻishdan keyin 18 soat davomida samolyotda uchish mumkin emas.',
    plan:['Nazariya va hovuz','Hovuz va ilk shoʻngʻishlar','Racha orollari yonida shoʻngʻishlar va sertifikat'], tip:'Noyabr–aprel; maydan oktabrgacha toʻlqinlar tufayli bekor qilishlar boʻladi.' },
  'similan-dive':{ title:'Similan orollariga dayv-safari', where:'Khao Lak',
    short:'Tailanddagi eng yaxshi dayving: Ko Bon, Ko Tachai, Rishelye — bortda toʻrt kun.',
    about:'Similan orollari — milliy bogʻ va mamlakatning asosiy dayving hududi: fevral–aprelda manta skatlari va kit akulalari, Ko Bon va Ko Tachai riflari, Rishelye qoyasi. Layvbordda toʻrt kun, 14 ga yaqin shoʻngʻish, kayuta va ovqatlanish. Bogʻda baliq ovlash taqiqlangan — bu baliqchilar emas, dayverlar uchun dastur.',
    plan:['Tap Lamudan chiqish va ilk shoʻngʻishlar','Ko Bon, Ko Tachai, Rishelye','Soʻnggi shoʻngʻishlar va qaytish'],
    tip:'Bogʻ taxminan 15-oktabrdan 15-maygacha ochiq. Advanced sertifikati va 20+ shoʻngʻish tajribasini tavsiya qilamiz.' },
  'freediving':{ title:'Ko Taoda noldan fridayving', where:'Ko Tao',
    short:'Nafas, nafasni ushlab turish va bir nafasda ilk 10–20 metr.',
    about:'Ko Tao — Osiyodagi fridayving markazlaridan biri. Boshlangʻich daraja kursi (AIDA, SSI yoki Molchanovs): nazariya, hovuzda nafasni ushlab turish, dengizda tros boʻylab mashq va sertifikat. Asosiy qoida — doimo sherik va instruktor bilan.',
    plan:['Nazariya va hovuz','Dengiz: tros boʻylab shoʻngʻishlar','Yakuniy shoʻngʻishlar va sertifikat'], tip:'Mart–sentabr; noyabr — Siam qoʻltigʻidagi eng noqulay oy.' },
  'surf-camp':{ title:'Balida serf-lager', where:'Bali',
    short:'Instruktor, taxta va video-tahlil — ilk kunlardayoq taxtada turasiz.',
    about:'Serf-lagerda bir hafta: 5–10 ta dars, taxta, spotlarga transfer, video-tahlil va yoga. Mavsumga qarab sohil almashadi: apreldan oktabrgacha gʻarbda va Bukitda sharoit yaxshi, noyabrdan martgacha — sharqda. Yangi boshlovchilar yil boʻyi serf qilishi mumkin.',
    plan:['Xavfsizlik va koʻpikli toʻlqinlarda ilk urinishlar','Darslar va video-tahlil','Yoningizda instruktor bilan mustaqil serf'],
    tip:'Martda Balida Sukunat kuni (Nyepi) — orol bir sutkaga yopiladi.' },
  'kite':{ title:'Noldan kaytserfing', where:'Hua Hin va Pranburi',
    short:'IKO sertifikati va noyabrdan aprelgacha barqaror shamol.',
    about:'IKO kursi: instruktor bilan 9–12 soat, ratsiyali dubulgʻa, barcha jihozlar va sertifikat. Hua Hin va Pranburi — shimoli-sharqiy musson mavsumida qoʻltiqdagi eng yaxshi kayt-spotlar. Shamolga buyurtma berib boʻlmaydi — ikki zaxira kunni rejaga kiritamiz.',
    plan:['Qirgʻoqda kaytni boshqarish','Bodidreg va ilk startlar','Taxtada yurish va sertifikat'], tip:'Noyabr–aprel; yozda kaytserfing Puketda boʻladi.' },
  'sailing':{ title:'Yaxta shkiperi kursi', where:'Puket',
    short:'Andaman dengizida amaliyot va xalqaro sertifikat.',
    about:'Instruktor bilan yaxtada bir hafta (bortda beshtagacha oʻquvchi): navigatsiya, qirgʻoqqa bogʻlanish, tungi oʻtishlar va yelkanlar bilan ishlash. Yakunda — maktab tanloviga koʻra xalqaro shkiper sertifikati. Yaxtani mustaqil ijaraga olish uchun radiooperator litsenziyasi ham kerak boʻladi — uni qanday olishni aytib beramiz.',
    plan:['Nazariya va manevrlarni mashq qilish','Orollar oraligʻida oʻtishlar va tungi oʻtish','Imtihon va sertifikat'], tip:'Noyabr–aprel.' },
  'yacht-week':{ title:'Doʻstlar bilan yaxtada bir hafta', where:'Andaman dengizi',
    short:'Katamaran, shkiper, oshpaz va Phang Nga orollari. Narx — sakkiz mehmon boʻlganda bir kishi uchun.',
    about:'Shkiper va oshpaz bilan 45–50 futlik yelkanli katamaranda bir hafta: Phang Nga qoʻltigʻi, Krabi va Phi-Phi orollari, bogʻlardan tashqarida bortdan baliq ovi, snorkeling va palubada kechki ovqatlar. Narx sakkiz mehmonga hisoblangan; yoqilgʻi va oziq-ovqat — haqiqiy sarfga koʻra.',
    plan:['Bortga chiqish va Phang Nga qoʻltigʻi','Krabi va Phi-Phi orollari','Qaytish'], tip:'Noyabr–aprel; Maya Bay koʻrfazi 1-avgustdan 30-sentabrgacha yopiq.' },
  'wakeboard':{ title:'Pattayyada veyk-lager', where:'Pattayya',
    short:'Murabbiy bilan kabelli veyk-park: ilk startlardan tryuklargacha.',
    about:'Kabelli veyk-parkda besh kun: murabbiy, jihozlar va video-tahlil. Oʻrganish uchun kabel katerdan osonroq — birinchi kunning oʻzidayoq taxtada turasiz.',
    plan:['Startlar va asosiy turish holati','Burilishlar, sakrashlar va video-tahlil','Ilk tryuklar'], tip:'Noyabr–fevral.' },
  'maldives-surf':{ title:'Maldiv orollarida serf-charter', where:'Maldiv orollari',
    short:'Qayiq, eng yaxshi rif toʻlqinlari va shom paytidagi baliq ovi.',
    about:'Gid bilan serf-qayiqda bir hafta: kurortlardan yetib boʻlmaydigan rif ustidagi toʻlqinlar, toʻliq pansion va shom paytida baliq ovi. Format ishonchli daraja uchun — riflar sayoz.',
    plan:['Maleda bortga chiqish','Atoll riflarida serf','Qaytish'], tip:'Mart–oktabr; eng katta toʻlqinlar — iyun–avgust.' },
  // ── Golf va padel ───────────────────────────────────────────────
  'golf-phuket':{ title:'Puketda golf haftasi', where:'Puket',
    short:'Orolning beshta eng yaxshi maydoni, keddi, mehmonxona va inventar bilan transferlar.',
    about:'Puketning eng yaxshi maydonlarida beshta raund — Blue Canyon, Red Mountain, Laguna va boshqalar, — har bir maydonda keddi (Puketda ular majburiy), 4★ mehmonxona va sumkalar bilan transferlar. Dekabrdan martgacha boʻlgan eng gavjum taym-slotlarni oldindan bron qilamiz.',
    plan:['Yetib kelish va mehmonxona','Turli maydonlarda beshta raund','Dam olish yoki baliq ovi kuni'], tip:'Noyabr–aprel; maydan oktabrgacha grin-fi 20–40% arzonroq.' },
  'golf-school':{ title:'Noldan golf', where:'Hua Hin',
    short:'PGA-pro bilan har kungi darslar va hafta oxiriga kelib maydonga chiqish.',
    about:'Hua Hin — Tailandning klassik golf kurorti. Sertifikatlangan pro bilan besh kunlik mashgʻulotlar: turish holati, sving, qisqa oʻyin, qoidalar va odob, oxirida esa — ilk toʻqqiz lunkangiz.',
    plan:['Turish holati, sving, driving-reynj','Qisqa oʻyin va patting','Maydonda ilk lunkalar'], tip:'Noyabr–aprel.' },
  'padel-camp':{ title:'Dubayda padel-lager', where:'Dubay',
    short:'Eng tez oʻsayotgan sport turi: texnika, taktika va guruh ichida turnir.',
    about:'Soʻnggi yillarda BAAda padelga qiziqish bir necha barobar oshdi va Dubay uning poytaxtlaridan biriga aylandi. Murabbiy bilan besh kun: 10–15 soat texnika va taktika, oʻz darajangizdagi sheriklar bilan oʻyinlar va oxirida turnir.',
    plan:['Darajani baholash','Texnika, taktika va oʻyinlar','Turnir'], tip:'Noyabr–mart; yozda — faqat yopiq kortlar. Ramazon sanalarini hisobga olamiz.' },
  'tennis-camp':{ title:'Mayorkada tennis lageri', where:'Mayorka',
    short:'Akademiya murabbiylari, video-tahlil va oʻyin setlari.',
    about:'Mayorkadagi tennis akademiyasining kattalar dasturida bir hafta: 15–20 soat tennis, jismoniy tayyorgarlik, zarbalarning video-tahlili va akademiya qoshida yashash.',
    plan:['Baholash va video-tahlil','Mashgʻulotlar va oʻyin setlari','Yakuniy oʻyinlar'], tip:'Mart–iyun va sentabr–noyabr. Shengen vizasi kerak.' },
  'golf-scotland':{ title:'Shotlandiyada golf: Sent-Endryus', where:'Sent-Endryus',
    short:'Golf vatani: Old Course va klassik links maydonlari.',
    about:'Golf vatanida bir hafta: har kungi qur’a orqali Old Courseda oʻynashga urinish (yoki qimmatroq kafolatlangan paket), Kingsbarns, Carnoustie va boshqa links maydonlari, mehmonxona va haydovchi. Old Course uchun gandikap kerak: erkaklarda — 24 dan yuqori boʻlmasligi lozim.',
    plan:['Sent-Endryusga yetib kelish','Links maydonlarida raundlar va Old Course qur’asi','Joʻnab ketish'], tip:'May–sentabr. Buyuk Britaniyaga kirish uchun pasportga qarab viza yoki ETA kerak — tekshirib beramiz.' },
  'padel-bali':{ title:'Balida padel va velnes', where:'Bali',
    short:'Ertalab padel, kunduzi serf, kechqurun spa.',
    about:'Sport va dam olish toʻgʻri nisbatda boʻlgan hafta: tong sahardan murabbiy bilan padel, kunduzi serf yoki hovuz, kechqurun massaj va Changgudagi villa.',
    plan:['Joylashish va birinchi oʻyin','Padel, serf va spa','Joʻnab ketish'], tip:'Aprel–oktabr.' },
  // ── Erkaklar estetikasi ─────────────────────────────────────────
  'hair':{ title:'Istanbulda soch koʻchirib oʻtkazish', where:'Istanbul',
    short:'Akkreditatsiyadan oʻtgan klinika, safardan oldin foto orqali konsultatsiya, mehmonxona va hamrohlik.',
    about:'Turkiya — soch koʻchirib oʻtkazishning jahon markazi, aynan shuning uchun bu yerda operatsiyani texniklar bajaradigan «konveyer» klinikalar koʻp. Biz faqat graftlarni olish va kesiklarni shifokor bajaradigan, graftlar soni hujjat bilan tasdiqlanadigan klinikalar bilan ishlaymiz. Foto orqali konsultatsiya, FUE yoki DHI operatsiyasi, PRP, dori-darmonlar, mehmonxonada 2–3 tun va transferlar.',
    plan:['Foto boʻyicha konsultatsiya va reja','Kutib olish, tahlillar va belgilash','Operatsiya','Bogʻlov, nazorat va uchib ketish'],
    tip:'Oktabr–aprel. Oddiy sayohat sugʻurtasi rejali operatsiyalarni qoplamaydi.' },
  'dental':{ title:'Bangkokda stomatologiya: implantlar va vinirlar', where:'Bangkok',
    short:'Xalqaro klinikalar, uchishdan oldin davolash rejasi, yaqin atrofda mehmonxona. Narx — bitta implant uchun.',
    about:'Bangkok — stomatologik turizmning asosiy markazlaridan biri. Abatment va tojli implant (Koreya tizimlari yoki Straumann/Nobel), keramik vinirlar. Davolash rejasini uchishdan oldin rentgen suratlari asosida tuzamiz. Implantlar 3–6 oy oraliq bilan ikki safarni talab qiladi, vinirlar — bir haftaga yaqin.',
    plan:['Safardan oldin suratlar va davolash rejasi','KT va implantlarni oʻrnatish','3–6 oydan keyin tojlar','Kafolat va nazorat'],
    tip:'Sogʻlom tishlar keraksiz charxlanmasligini nazorat qilamiz.' },
  'lasik':{ title:'Koʻrishni lazer bilan tuzatish', where:'Bangkok',
    short:'Diagnostika, operatsiya va nazorat. Bir kundan keyin — quyoshdan himoya koʻzoynagida plyajga.',
    about:'Ixtisoslashgan koʻz klinikasida Femto-LASIK yoki SMILE: toʻliq diagnostika, ikkala koʻzda operatsiya, dori-darmonlar va birinchi hamda yettinchi kuni nazorat. Hammaga ham toʻgʻri kelmaydi — qarorni shifokor tekshiruvdan keyin qabul qiladi.',
    plan:['Diagnostika','Operatsiya','Nazorat va dam olish'], tip:'Hovuz va dengiz — faqat 2–4 haftadan keyin.' },
  'skin-seoul':{ title:'Seulda erkaklar kosmetologiyasi', where:'Seul',
    short:'Teri, pigmentatsiya va parvarish: erkaklar uchun Koreya protokollari.',
    about:'Seul klinikalarida besh kun: dermatolog konsultatsiyasi, koʻrsatmalarga koʻra apparat muolajalari, parvarish va tiklanish. Roʻyxatdan oʻtgan agentlar orqali ishlaymiz — Koreyada chet elliklarga koʻpincha yuqoriroq narx aytiladi, biz buni nazorat qilamiz.',
    plan:['Konsultatsiya va reja','Muolajalar','Nazorat va tavsiyalar'], tip:'Oktabr–aprel.' },
  'style':{ title:'Dubayda uslub va imij', where:'Dubay',
    short:'Stilist, barber va hayot ritmingizga mos garderob.',
    about:'Stilist bilan ikki kun: garderobni koʻrib chiqish, Dubayning eng yaxshi univermaglarida bir kunlik shoping, barber va tikuvchi. Kiyimni oʻzingiz sotib olasiz — xaridlardan foiz olmaymiz. Turistlarga 5% QQS qaytariladi.',
    plan:['Uslub brifi va barber','Shoping va kiyib koʻrish'], tip:'Noyabr–mart; Dubai Shopping Festival — dekabr–yanvar.' },
  // ── Ovqatlanish va qoʻshimchalar ────────────────────────────────
  'nutritionist':{ title:'Tahlillar asosida nutritsiolog', where:'Onlayn',
    short:'Tahlillarni koʻrib chiqish, ovqatlanish rejasi va toʻrt hafta hamrohlik.',
    about:'Soʻrovnoma, tahlillarga yoʻllanma, natijalarni shifokor-dietolog bilan koʻrib chiqish, maqsadlaringizga mos ovqatlanish rejasi va ikki nazorat uchrashuvi. Tashxisni faqat shifokor qoʻyadi — shuning uchun litsenziyali mutaxassislar bilan ishlaymiz.',
    plan:['Soʻrovnoma va tahlillar','Natijalar tahlili va ovqatlanish rejasi','Ikki nazorat uchrashuvi'] },
  'erkak-stack':{ title:'ERKAK protokoli: 90 kun', where:'Dunyo boʻylab yetkazib berish',
    short:'Partiya tahlil sertifikatiga ega D3+K2, rux, magniy va omega-3. 90 kundan keyin nazorat tahlili.',
    about:'Nazorat tahliligacha boʻlgan toʻliq siklga moʻljallangan toʻrt nomdagi ERKAK toʻplami: K2 bilan D3 vitamini, selen bilan rux, magniy va omega-3. Har bir bankada — partiya tahlili sertifikati. Dori vositasi hisoblanmaydi.',
    plan:['Boshlangʻich tahlillar','90 kunlik protokol','Nazorat tahlili'] },
  'chef-prep':{ title:'Shaxsiy oshpaz va reja boʻyicha ovqatlanish', where:'Puket',
    short:'Oshpaz maqsadlaringiz va mashgʻulotlaringizga moslab taom tayyorlaydi. Narx — ikki kishi uchun, mahsulotlar kiritilgan.',
    about:'Villada xususiy oshpaz bilan yetti kun: kaloriya va makronutriyentlarga mos menyu, mahsulot xaridi, nonushta va kechki ovqat, oshxonani yigʻishtirish. Muqobil variant — har kuni tayyor ratsionni yetkazib berish. Barcha allergiyalar haqida boshlashdan oldin yozma ravishda xabar berasiz.',
    plan:['Brif va menyu','Reja boʻyicha yetti kunlik ovqatlanish','Retseptlar oʻzingiz bilan'] },
  'shilajit-tour':{ title:'Chimyon togʻlariga — mumiyo izidan', where:'Oʻzbekiston',
    short:'ERKAK mumiyosi qayerdan keladi: togʻlar, yigʻuvchilar va laboratoriya.',
    about:'Gʻarbiy Tyan-Shanda uch kun: yoʻlboshchi bilan mumiyo yigʻiladigan joylarga safar, yigʻuvchilar bilan tanishuv, xomashyo tozalanadigan va tekshiriladigan laboratoriyaga tashrif hamda togʻlarda palovli oqshom.',
    plan:['Toshkent va Chimyon togʻlari','Yigʻish joylari va yigʻuvchilar','Laboratoriya va qaytish'], tip:'May–oktabr.' },
  // ── Ota va oʻgʻil ───────────────────────────────────────────────
  'father-son-thai':{ title:'Ota va oʻgʻil: baliq ovi va muay tay', where:'Puket',
    short:'Ertalab — ring, kunduzi — okean. 10 yoshdan boshlab oʻgʻillar uchun. Narx — ikki kishi uchun.',
    about:'Oʻgʻlingiz umrbod eslab qoladigan besh kun: murabbiy bilan ikkovlon beshta muay tay mashgʻuloti, xususiy qayiqda ikki kunlik baliq ovi, mehmonxona va transferlar. Lagerlardagi bolalar guruhlari — 6–8 yoshdan, qayiqda — bolalar qutqaruv jiletlari.',
    plan:['Yetib kelish va birinchi mashgʻulot','Mashgʻulotlar va baliq ovi','Baliq ovi va yakuniy mashgʻulot'], tip:'Noyabr–aprel — dengiz sokin.' },
  'family-krabi':{ title:'Krabida oilaviy sarguzasht', where:'Krabi',
    short:'Qoyalar, kayaklar, orollar va etik qoʻriqxonadagi fillar. Narx — bir kishi uchun.',
    about:'Butun oila uchun bir hafta: mangr labirintlarida kayaklar, xususiy qayiqda orollar, fillarga minilmaydigan etik qoʻriqxona, Reyli plyajlari va bolalar klubi bor kurort.',
    plan:['Kurort va plyajlar','Kayaklar, orollar va qoʻriqxona','Dam olish'], tip:'Noyabr–aprel; Maya Bay avgust–sentabrda yopiq.' },
  'teen-camp':{ title:'Oʻsmirlar uchun sport lageri', where:'Puket',
    short:'Ota-onalar yaqin atrofda dam olayotganda — sport va ingliz tili.',
    about:'12–17 yoshli oʻsmirlar uchun ikki hafta: muay tay, suzish, serf, har kuni ingliz tili va tarbiyachilar. Puketda yashash joyi bilan tayyor xalqaro lagerlar kam — dasturni soʻrov boʻyicha, xodimlarni tekshirib va ota-onalarning yozma roziligi bilan tuzamiz.',
    plan:['Sport va ingliz tili','Turnir, ekskursiyalar va yakun'], tip:'Dekabr–yanvar va bahorgi ta’til.' },
  'father-son-nepal':{ title:'Ota va oʻgʻil Nepal togʻlarida', where:'Nepal',
    short:'14 yoshdan boshlab oʻgʻillar uchun Poon Hill yoki Annapurna tayanch lageriga trekking.',
    about:'Himolayda ikkovlon oʻn kun: Poon Hillga (3 210 m) trekking — oʻsmirlar uchun yengil variant — yoki tayyorgarligi borlar uchun Annapurna tayanch lageriga (4 130 m). Gid, hammol, lojlar va ruxsatnomalar narxga kiritilgan. Narx — bir kishi uchun.',
    plan:['Katmandu va Pokhara','Trekking','Qaytish va Katmandu'], tip:'Mart–may va oktabr–noyabr.' },
  // ── Kompaniyalar va doʻstlar uchun ──────────────────────────────
  'corp-retreat':{ title:'Top-jamoa uchun retrit', where:'Puket',
    short:'Ertalab strategik sessiya, kunduzi sport va okean. Narx — bir ishtirokchi uchun.',
    about:'Boshqaruv jamoasi uchun toʻrt kun: fasilitator bilan ertalabki strategik sessiyalar, kunduzi — yaxta, baliq ovi yoki muay tay, kechqurun — kechki ziyofatlar. Muzokara xonalari bor 5★ mehmonxona, kompaniya uchun hujjatlar va hisob-faktura.',
    plan:['Kelish va kechki ovqat','Strategik sessiyalar va faoliyatlar','Yakunlar va joʻnash'], tip:'Noyabr–aprel.' },
  'founders':{ title:'Asoschilar uchun retrit', where:'Bali',
    short:'Biznes egalarining kichik guruhi: strategiya, salomatlik va sokinlik.',
    about:'Asoschilarning kichik guruhida besh kun: strategik sessiyalar, bir-birining keyslarini tahlil qilish, mashgʻulotlar, uyqu va sokinlik. Villa, fasilitator va dastur — undan keyin aniq reja bilan qaytasiz.',
    plan:['Tanishuv va maqsadlar','Sessiyalar va amaliyotlar','Rejalar va yakun'], tip:'Aprel–oktabr; kelganda beriladigan viza ishlash huquqini bermaydi.' },
  'regatta':{ title:'Korporativ regata', where:'Puket',
    short:'Bir xil yaxtalardagi jamoalar, hakamlar, kuboklar va kechki ziyofat. Narx — bir ishtirokchi uchun.',
    about:'Jamoa uchun ikki kunlik yelkanli poygalar: shkiperli bir xil yaxtalar, hakam va bayonnomalar, kuboklar va taqdirlash marosimi bilan kechki ziyofat. Dekabrning birinchi haftasida Puketda King’s Cup regatasi oʻtadi — bu paytda mehmonxonalarni oldindan bron qilamiz.',
    plan:['Yoʻriqnoma va mashq poygasi','Regata va marosim'], tip:'Noyabr–aprel.' },
  'bachelor':{ title:'Kuyov va doʻstlari uchun premium safar', where:'Puket yoki Dubay',
    short:'Yaxta, baliq ovi, muay tay va oshpazdan kechki ovqat. Siyqasi chiqqan narsalarsiz. Narx — bir ishtirokchi uchun.',
    about:'Toʻyda aytib bersa arziydigan uch kun: villa yoki 5★ mehmonxona, yaxtada baliq ovi bilan bir kun, butun davra bilan muay tay mashgʻuloti va oshpazdan kechki ovqat. Qoidalar oddiy: Tailandda veyplar taqiqlangan, BAAda esa giyohvand moddalarga mutlaqo toqat qilinmaydi.',
    plan:['Joylashish va kechki ovqat','Yaxta va baliq ovi','Muay tay va yakuniy oqshom'] }
};

export const destinations = {
  phuket:{ name:'Puket', title:'Erkaklar uchun Puket: baliq ovi, muay tay, golf va okean',
    intro:'Puket — ERKAKning asosiy bazasi va Tailanddagi faol erkaklar dam olishi uchun eng yaxshi orol. Racha orollari yonida trofey baliq ovi, Soi Ta-Iaddagi muay tay lagerlari, beshta golf maydoni, dayving, yaxtalar va tiklanish — barchasi bir soatlik yoʻl masofasida.',
    season:'Noyabr–aprel — quruq mavsum, sokin dengiz va dekabr–fevralda narxlar choʻqqisi. May–oktabr — musson: uzoq dengiz chiqishlari koʻpincha bekor qilinadi, lekin lagerlar va golf maydonlarida narxlar pastroq.',
    access:'Toshkentdan Bangkokka toʻgʻridan-toʻgʻri reyslar bor, Puketga esa Bangkok, Dubay, Doha, Istanbul yoki Olmaota orqali uchiladi. Oʻzbekiston fuqarolariga viza (e-Visa) kerak — rasmiylashtirishda yordam beramiz; Rossiya va Qozogʻiston fuqarolari 30 kungacha vizasiz kiradi.' },
  bangkok:{ name:'Bangkok', title:'Erkaklar uchun Bangkok: check-up, muay tay va gigant baliqlar',
    intro:'Bangkok — tibbiy turizmning jahon markazlaridan biri va muay tay poytaxti. Bu yerda bir kunda executive check-up qilinadi, tish va koʻz muolajalari oʻtkaziladi, afsonalar zallarida mashq qilinadi va shahardan bir soatlik masofada Mekong laqqa baliqlari tutiladi.',
    season:'Eng yaxshi vaqt — noyabr–fevral. Martdan maygacha juda issiq, iyundan oktabrgacha yomgʻirlar yogʻadi, ammo tibbiy dasturlar va chuchuk suvda baliq ovi yil boʻyi ishlaydi.',
    access:'Suvarnabhumi aeroporti — Toshkent, Dubay va Olmaotadan toʻgʻridan-toʻgʻri reyslar keladigan yirik xab. Shifoxonalargacha — 40–60 daqiqa.' },
  samui:{ name:'Samui va Ko Tao', title:'Samui oroli: detoks, villada muay tay va Ko Taoda fridayving',
    intro:'Samui — klassik velnes-retritlar, Siam qoʻltigʻiga qaragan villalar va sokin ritm oroli. Yaqinida — Osiyodagi fridayving va dayving markazlaridan biri Ko Tao.',
    season:'Yanvar–sentabr — eng yaxshi vaqt. Oktabr–dekabr — Siam qoʻltigʻida yomgʻirlar mavsumi.',
    access:'Samui aeroporti Bangkok va Singapurdan reyslarni qabul qiladi; Ko Taogacha — paromda 1,5–2 soat.' },
  'chiang-mai':{ name:'Chiang May', title:'Chiang May: togʻlar, sokinlik, massaj va moto-sarguzashtlar',
    intro:'Shimoliy Tailand — bu togʻlar salqini, meditatsiya markazlari, eski maktab massaji, treyl uchun togʻ soʻqmoqlari va afsonaviy Mae Hong Son moto-halqasi.',
    season:'Noyabr–yanvar — salqin va ochiq havo. Fevraldan aprelgacha shimolda dalalar yoqilishi sababli tutun boʻladi — bu oylarni tavsiya qilmaymiz. Iyun–oktabr — yomgʻirlar.',
    access:'Bangkokdan (taxminan bir soat) va Osiyo xablaridan toʻgʻridan-toʻgʻri reyslar.' },
  krabi:{ name:'Krabi va Khao Lak', title:'Krabi va Khao Lak: qoyalar, Similan, changalzor va orollar',
    intro:'Reylining ohaktosh qoyalari, Khao Lakdan Similan orollariga dayv-safari, Khao Sok changalzorlaridagi Cheow Lan koʻli va oilalar uchun sokin orollar — Andaman sohilining eng goʻzal tabiati.',
    season:'Noyabr–aprel. Similan milliy bogʻi taxminan 15-oktabrdan 15-maygacha ochiq.',
    access:'Krabi va Puket aeroportlari; Khao Lakkacha — Puket aeroportidan taxminan bir soat.' },
  gulf:{ name:'Hua Hin va Pattayya', title:'Hua Hin va Pattayya: Bangkok yonida kayt, golf va veyk',
    intro:'Bangkokdan ikki-uch soatlik masofadagi Siam qoʻltigʻi sohili: Pranburi kayt-spotlari, Hua Hinning klassik golf maydonlari, veyk-parklar va Pattayya orollari yonida baliq ovi.',
    season:'Noyabr–aprel — quruq va shamolli, kayt va golf uchun eng yaxshi mavsum.',
    access:'Bangkokdan transfer — 2–3 soat; Pattayya yaqinida U-Tapao aeroporti bor.' },
  bali:{ name:'Bali', title:'Bali: serf, alkogolsiz retritlar, spa va asoschilar retritlari',
    intro:'Bali — serf, spa va retritlar oroli: gʻarbiy sohilda serf-lagerlar, Ubudda nafas amaliyotlari va spa, alkogolsiz va erkaklar retritlari, padel va asoschilarning kuchli hamjamiyati.',
    season:'Aprel–oktabr — quruq mavsum. Martda Sukunat kuni (Nyepi): orol bir sutkaga yopiladi.',
    access:'Denpasar aeroporti; kelganda beriladigan viza va turistik yigʻim.' },
  dubai:{ name:'Dubay', title:'Dubay: biohaking, padel, 40+ kuch dasturlari va uslub',
    intro:'Dubay — litsenziyali tiklanish klinikalari, padel va yuqori darajadagi servis shahri: shifokorlar nazoratida biohaking, 40+ yoshdagi erkaklar uchun kuch dasturlari, padel-lagerlar va uslub.',
    season:'Noyabr–mart. Yozda — faqat yopiq joylarda. Ramazon sanalarini hisobga olamiz.',
    access:'Dunyoning aksariyat shaharlaridan toʻgʻridan-toʻgʻri reyslar. Kirish qoidalari pasportga bogʻliq (masalan, Rossiya fuqarolari vizasiz kiradi) — biz tekshirib beramiz.' },
  caucasus:{ name:'Kavkaz', title:'Kavkaz: Elbrus, baland togʻ yigʻinlari va togʻ changʻisi',
    intro:'Yevropaning eng baland nuqtasi, Tsaxkadzor olimpiya bazasi va Gudauri friraydi — balandlikni sevuvchilar uchun Kavkaz.',
    season:'Iyun–sentabr — choʻqqilarga chiqish va yigʻinlar; dekabr–mart — togʻ changʻisi.',
    access:'Elbrus uchun — Mineralniye Vodi va Nalchik; Tsaxkadzor uchun — Yerevan; Gudauri uchun — Tbilisi.' },
  'central-asia':{ name:'Markaziy Osiyo', title:'Markaziy Osiyo: Olmaotada boks va Oʻzbekiston togʻlari',
    intro:'ERKAK vatani: Olmaotadagi Qozogʻiston boks maktabi, Gʻarbiy Tyan-Shan togʻlari va Chimyondagi mumiyo yigʻiladigan joylar.',
    season:'May–oktabr — togʻlarda; boks — bahor va kuzda.',
    access:'Olmaota va Toshkentga Dubay, Istanbul va Moskvadan toʻgʻridan-toʻgʻri reyslar.' },
  russia:{ name:'Oltoy va Kamchatka', title:'Oltoy va Kamchatka: erkaklar retritlari, otliq sayr va vulqonlar',
    intro:'Rossiyaning yovvoyi tabiati: Oltoyda erkaklar retritlari va otda sayohatlar, Kamchatka vulqonlari va Geyzerlar vodiysi, haqiqiy rus hammomi.',
    season:'Iyul–sentabr; hammom — oktabr–mart.',
    access:'Barnaul yoki Gorno-Altaysk; Petropavlovsk-Kamchatskiy. Chet elliklar uchun: xorijiy kartalar Rossiyada ishlamaydi, jumladan Oʻzbekiston banklarining Visa/Mastercard kartalari ham.' },
  'east-africa':{ name:'Sharqiy Afrika', title:'Sharqiy Afrika: Kilimanjaro, safari va Itenda yugurish',
    intro:'Afrika tomi, Buyuk migratsiya va yugurish boʻyicha jahon chempionlari shahri — qit’adagi uchta asosiy erkaklar sarguzashti.',
    season:'Yanvar–mart va iyun–oktabr; Masai-Marada migratsiya — iyul–oktabr.',
    access:'Kilimanjaro va Nayrobi aeroportlari; Keniya va Tanzaniyaning elektron vizalari.' },
  europe:{ name:'Yevropa', title:'Yevropa: Shotlandiyada golf, tennis, velosport va ochlik kurslari',
    intro:'Yevropa klassikasi: Sent-Endryus, Mayorkadagi tennis akademiyasi va velosport yigʻinlari, Germaniya va Avstriyaning ochlik klinikalari.',
    season:'Bahor va kuz; Shotlandiya — may–sentabr.',
    access:'Shengen vizasi; Buyuk Britaniya uchun — pasportga qarab viza yoki ETA elektron ruxsatnomasi, biz tekshirib beramiz.' },
  'east-asia':{ name:'Yaponiya va Koreya', title:'Yaponiya va Koreya: onsenlar, check-up va kosmetologiya',
    intro:'Issiq buloqli yapon ryokanlari, Seulning yetakchi shifoxonalaridagi check-uplar va teri parvarishining Koreya protokollari.',
    season:'Bahor va kuz; onsenlar — noyabrdan martgacha.',
    access:'Yaponiya va Koreyaga kirish qoidalari pasportga bogʻliq — biz tekshirib beramiz.' },
  nepal:{ name:'Nepal' }, india:{ name:'Hindiston' }, jordan:{ name:'Iordaniya' }, maldives:{ name:'Maldiv orollari' }, istanbul:{ name:'Istanbul' }, online:{ name:'Onlayn' }
};
