// ERKAK · oʻzbekcha · «Tailandda baliq ovi» boʻlimi: lending, turlar, nuqtalar, kalendar, kviz.
export default {
  metaTitle:'Puketda baliq ovi: Andaman dengizida turlar va konsyerj | ERKAK',
  metaDesc:'Puket, Khao Lak va Bangkokda trofey baliq ovi: yelkanbaliq, marlin, GT. Xususiy qayiq, litsenziyali gid, oʻzbek va rus tillarida konsyerj. Narxi 4 900 THB dan.',
  chip:'Mavsum ochiq · Andaman dengizi',
  title:'Tailandda trofey baliq ovi. *Qonuniy, oʻz tilingizda, hammasi tayyor.*',
  lede:'Andaman dengizida yelkanbaliq, marlin, GT va tunets. Xususiy qayiqlar, litsenziyali gid va hamma narsani hal qiladigan konsyerj.',
  proof:[['0','milliy bogʻlarda baliq ovi'],['≤ 6','baliqchi bir guruhda'],['30%','oldindan toʻlov'],['24/7','konsyerj aloqada']],
  sonar:{ aria:'Exolot: taxminan 40 metr chuqurlikda baliq', depth:'Chuqurlik', water:'Suv', speed:'Tezlik', point:'Nuqta', tagTitle:'38 m chuqurlikda nishon — GT boʻlsa kerak', tagText:'Racha Noi · tong · suv koʻtarilmoqda. Popper qoʻyamiz.' },
  subnav:[['Turlar','tours'],['Kimlar uchun','who'],['Konsyerj','concierge'],['Xarita','map'],['Mavsum','season'],['Savollar','faq']],
  pains:{ kicker:'Nega baliq ovi koʻngilni qoldiradi', title:'Okeanda bir kunni boy berishning toʻrt yoʻli. *Har birini toʻsdik.*', items:[
    ['40 kishilik ekskursiya','Katta sayr kemasi, olomon, tayoqqa oʻralgan qarmoq ipi va tamaddi bilan snorkeling oraligʻida suv yonida atigi yigirma daqiqa.','Xususiy qayiqlar va oltita baliqchigacha boʻlgan mini-guruhlar. Vaqt — baliq oviga.'],
    ['Milliy bogʻda baliq ovi uchun jarima','Similan va Phi Phi orollarida baliq ovini hanuz sotishadi, garchi u qonun bilan taqiqlangan boʻlsa ham: 500 000 THB gacha jarima va jinoiy javobgarlik.','Faqat ruxsat etilgan nuqtalar: shelf, FAD, Racha orollari. Litsenziyali operator va bortda tailandlik gid.'],
    ['Kapitan nima istashingizni tushunmaydi','Imo-ishoralar, telefondagi tarjimon va sizning baligʻingiz oʻrniga «odatdagi joyga» chiqish.','Oʻzbek va rus tillarida gaplashadigan konsyerj chiqishdan oldin, chiqish paytida va undan keyin aloqada. Kapitan bilan brifingni oldindan tayyorlaymiz.'],
    ['Mavsumdan tashqari quruq qaytish','Sizga yelkanbaliq yoʻq oyda yelkanbaliq ovini, riflardan nariga chiqib boʻlmaydigan shamolli kunda esa dengiz safarini sotishadi.','Sana va formatni baliq ovi kalendari, prognoz va oy fazasiga qarab tanlaymiz. Baligʻingizning mavsumi boʻlmasa, ochiq aytamiz.'],
    ['Anjomlar trofeyga bardosh bermadi','Eskirgan ip, zanglagan ilgaklar va 20 kilogrammlik birinchi baliqdayoq taslim boʻladigan gʻaltak.','Shimano Stella va Daiwa Saltiga, PE 6–10 iplar, har bir Pro-chiqish uchun yangi ilgaklar.'],
    ['Uydan toʻlash noqulay','Mahalliy kartalar chet elda har doim ham oʻtmaydi, «kapitanning kartasiga» pul oʻtkazish esa xavotirli.','Oʻzbekiston banklarining xalqaro Visa/Mastercard kartalari, USDT, joyida naqd pul, kompaniya uchun hisob-faktura. 30% oldindan toʻlov, shartnoma oʻz tilingizda.'] ] },
  who:{ kicker:'Kimlar uchun', title:'Kim ekaningizni tanlang — *formatingizni koʻrsatamiz*' },
  segments:[
    { id:'family', label:'Oila va yangi boshlovchilar', title:'Birinchi haqiqiy baliq ovi — dengiz kasalligisiz, olomonsiz va aldovsiz',
      quote:'«Bolalar bilan baliq ovlamoqchimiz, lekin qirqta turist bilan eski kemaga chiqarib, qoʻlimizga tayoqqa oʻralgan ip tutqazishlaridan qoʻrqamiz».',
      points:['Faqat oilangiz uchun xususiy qayiq, 5 soatlik chiqish','Racha Yai oroli yonida sokin suv, bolalar uchun qutqaruv nimchalari','Kapitan anjomlarni sozlaydi va baliqni tortib olishga yordam beradi','Oʻlja bortda tayyorlanadi — sashimi va gril'], picks:['family-half','first-strike','bangkok-monsters'] },
    { id:'angler', label:'Tajribali baliqchi', title:'GT va tunets uchun popping va jig — «hamma boradigan joyda» emas, toʻgʻri nuqtalarda',
      quote:'«Turistik qayiqlar popping qila olmaydi. Menga suv osti tepaliklari, oqimlar va oy fazalarini biladigan kapitan kerak».',
      points:['Tezyurar spidbot: nuqtada koʻproq, yoʻlda kamroq vaqt','Stella va Saltiga darajasidagi anjomlar, PE 6–10, stingerlar','Shelf va FAD nuqtalari — milliy bogʻlardan tashqarida, jarima xavfisiz','Sanangiz uchun suv koʻtarilishi, oy va shamolga moslangan reja'], picks:['pro-gt','bigame-day','khaosok-jungle'] },
    { id:'trophy', label:'Trofey ovchisi', title:'Yelkanbaliq, marlin, it tishli tunets — bitta maqsad uchun ekspeditsiya',
      quote:'«Aniq bir baliq uchun dunyoning yarmini uchib oʻtaman. Menga sayr emas, imkoniyat kerak».',
      points:['Kokpit va baliq bilan kurashish kreslosi boʻlgan sportfisher','Shelfda tunash: ertalabki va kechki ov aynan nuqtaning oʻzida','Mavsum va prognozga qarab qulay oyna, jarimasiz koʻchirish','IGFA standarti boʻyicha catch & release, oʻlchash va sertifikat'], picks:['overnight-shelf','expedition-khaolak','stingray'] },
    { id:'corp', label:'Kompaniya', title:'3–5 qayiqda turnir, sovrinlar, kechki ziyofat va video — bitta shartnoma bilan',
      quote:'«Oʻn ikki hamkorni shunday olib borish kerakki, bir yil eslab yurishsin. Men esa hech narsani oʻylamasam».',
      points:['3–5 ta bir xil qayiqdan iborat flot va turnir hakami','Kuboklar, nominatsiyalar, boshlovchi, villada kechki ziyofat','Tadbir videoroligi 48 soat ichida','Hujjatlar, kompaniya uchun hisob-faktura, shartnoma'], picks:['tournament','bigame-day','signature-week'] },
    { id:'vip', label:'VIP', title:'Hammasini bitta odam hal qiladi: villa, yaxta, oshpaz, transferlar',
      quote:'«Osiyodagi eng yaxshi baliq ovi haftasini birorta qoʻngʻiroqsiz va kutishsiz oʻtkazmoqchiman».',
      points:['Safardan oldin va safar davomida 24/7 shaxsiy konsyerj','Eng gavjum sanalarda eng yaxshi qayiqlar — bir mavsum oldin bron','Shef-oshpaz, foto va dron, maxfiylik','Vertolyot, gidrosamolyot, oilaviy dastur — soʻrov boʻyicha'], picks:['signature-week','bigame-day','overnight-shelf'] }
  ],
  toursBlock:{ kicker:'Turlar va narxlar', title:'Birinchi ilinishdan *marlin ekspeditsiyasigacha*', lede:'Narxga qayiq, anjomlar, transfer, ovqat, sugʻurta va litsenziyali gid kiradi. Pirsda qoʻshimcha toʻlovlarsiz.',
    filters:[['all','Barchasi'],['sea','Dengiz'],['fresh','Chuchuk suv'],['group','Kompaniyalar'],['vip','VIP']] },
  ladder:{ kicker:'Besh daraja', title:'Kichikdan boshlang — *yoki darhol trofeydan*', lede:'Aksariyat mehmonlar «Ilk oʻlja» yoki «Oilaviy kun»dan boshlaydi, bir yildan soʻng esa yelkanbaliq uchun qaytib keladi.',
    steps:[['I · Bepul','Qoʻllanma va baliq ovi kalendari','0 THB','Qonuniy nuqtalar, mavsumlar va oʻzingiz bilan nima olish kerakligi — messenjerga yuboramiz.',8],
      ['II · Sinab koʻrish','Ilk oʻlja','4 900 THB','Oltita kishigacha boʻlgan mini-guruh. Bu siz uchunmi yoki yoʻqmi — bilib olasiz.',22],
      ['III · Xususiy','Oilaviy kun · Pro Day','24 000–38 000','Qayiq faqat sizniki: bolalar bilan sokin kundan GT uchun poppinggacha.',45],
      ['IV · Trofey','Big Game · Shelfda tun','89 000+','Sportfisher, shef-oshpaz, yelkanbaliq va marlin. Trofey uchun asosiy imkoniyat.',72],
      ['V · Signature','Turnir · Signature Week','390 000+','Konsyerj, villa, flot va film. Siz uchib kelguningizcha hammasi hal qilingan boʻladi.',100]] },
  concierge:{ kicker:'Konsyerj xizmati', title:'Siz baliq ovlaysiz. *Qolgani — bizning ishimiz.*', lede:'Oʻz tilingizda gaplashadigan bitta inson butun safar uchun javob beradi — sana tanlashdan trofeygacha.',
    items:[['boat','Maqsadga mos qayiq va kapitan','Flotni tezlik, anjomlar va sharhlar boʻyicha solishtiramiz. Gavjum sanalarni oldindan bron qilamiz.'],['rod','Premium darajadagi anjomlar','Stella, Saltiga, yangi iplar. Yoki oʻzingiznikini tayyorlab beramiz.'],['car','Biznes-klass transferlar','Aeroportda kutib olish, pirsgacha avtomobil, butun safar davomida haydovchi.'],['home','Dengiz boʻyidagi villa','Chalong yaqinida yoki Khao Lakda — koʻproq uxlash uchun.'],['chef','Shef-oshpaz va oʻljadan menyu','Bortda sashimi, villada trofeydan kechki ovqat.'],['cam','Foto, dron, film','Bortda operator va 48 soatda tayyor rolik.'],['shield','Sugʻurta va hujjatlar','Tekshirilgan qayiqlar, shartnoma, kompaniya uchun hisob-faktura.'],['star','Oila uchun dastur','Siz okeandaligingizda — spa, orollar va tabiat.']],
    sigKicker:'Signature Week · 7 kun', sigTitle:'Tailanddagi eng yaxshi baliq ovi haftasi — *birorta qoʻngʻiroqsiz*', sigPoints:['Sportfisherda Big Game va shelfda tun','Khao Sok tropik oʻrmonlari va Bangkokning rekordli koʻllari','Villa, shef-oshpaz, haydovchi, foto va film','24/7 shaxsiy konsyerj va mavsum choʻqqisida eng yaxshi qayiqlar'],
    fee:'Istalgan turga konsyerj — kuniga 15 000 THB dan. Qishni Tailandda oʻtkazadiganlar uchun klub kartasi: mavsumda besh marta chiqish 15% chegirma bilan va sanalarni tanlashda ustuvorlik.', sigCta:'Hafta dasturi' },
  map:{ kicker:'Qayerda ovlaymiz — va qayerda hech qachon', title:'Halol xarita: *Andaman dengizi*', lede:'Dengiz milliy bogʻlarida baliq ovlash qonun bilan taqiqlangan. Biz shelfda, FAD va Racha orollari atrofida ovlaymiz, bogʻlarga esa faqat toʻxtash va snorkeling uchun kiramiz. Xaritadagi nuqtani bosing.' },
  spots:{
    'racha-yai':{ name:'Racha Yai', run:'Chalongdan 30–45 daqiqa', fish:'Barrakuda, makrel, lutsian, gruper', how:'Trolling, tubdan ovlash, yengil jig', note:'Milliy bogʻ hududiga kirmaydi. Oilalar va guruhlar uchun asosiy nuqta.' },
    'racha-noi':{ name:'Racha Noi', run:'Chalongdan taxminan bir soat', fish:'GT, sariq qanotli tunets, vahu, amberjek, gruper', how:'Popping, vertikal jig, trolling', note:'Chuqurroq va uzoqroq, janub tomonda suv osti togʻi bor. Pro Day uchun nuqta.' },
    'shelf':{ name:'Shelf va FAD', run:'1,5–2,5 soat', fish:'Yelkanbaliq, marlin, vahu, korifena, tunets', how:'Trolling, FAD yonida popping', note:'Chuqurlik keskin ortadigan joy va baliq toʻplovchi qurilmalar. Yelkanbaliq uchun aynan shu yerga boriladi.' },
    'khaolak-fad':{ name:'Khao Lak FAD nuqtalari', run:'Tap Lamudan 6 km naridan boshlab', fish:'Korifena, vahu, GT, makrel, yelkanbaliq', how:'Popping, 60–80 metrda jig, fly-fishing', note:'Qat’iy ravishda Similan milliy bogʻi chegarasigacha ovlaymiz.' },
    'phangnga':{ name:'Phang Nga qoʻltigʻi', run:'Bang Rongdan', fish:'Barrakuda, trevalli, gruper, lutsian', how:'Kasting, tubdan ovlash', note:'Shamoldan pana suv — musson mavsumida zaxira reja, milliy bogʻ chegarasidan tashqarida.' },
    'similan':{ name:'Similan orollari', run:'Tap Lamudan 65–70 km', fish:'—', how:'Faqat toʻxtash va snorkeling', note:'Milliy bogʻ: baliq ovlash yil boʻyi taqiqlangan, jumladan Koh Bon va Koh Tachai atrofida ham. 16-maydan 15-oktyabrgacha yopiq.' },
    'surin':{ name:'Surin va Richelieu', run:'—', fish:'—', how:'—', note:'Milliy bogʻ: baliq ovlash taqiqlangan. May oʻrtasidan oktyabr oʻrtasigacha yopiq.' },
    'phiphi':{ name:'Phi Phi', run:'—', fish:'—', how:'—', note:'Noppharat Thara – Phi Phi milliy bogʻi: baliq ovlash taqiqlangan, jumladan Bamboo oroli va «4 orol» hududida ham.' },
    'shark':{ name:'Shark Point', run:'—', fish:'—', how:'—', note:'1992-yildan beri dengiz qoʻriqlanadigan hududi: baliq ovlash va langar tashlash taqiqlangan.' },
    'lanta':{ name:'Koh Rok · Hin Daeng', run:'—', fish:'—', how:'—', note:'Mu Ko Lanta milliy bogʻi. Biz uni taqiq hududi deb hisoblaymiz.' },
    'khaosok':{ name:'Khao Sok · Cheow Lan', run:'quruqlik orqali 2,5 soat', fish:'Ilonbosh, hampala, mahsir', how:'Spinning, longteyl qayigʻidan fly-fishing', note:'Faqat mahalliy longteyl qayiqlaridan ovlashga ruxsat beriladi.' }
  },
  season:{ sailfish:['Yelkanbaliq','trolling'], marlin:['Qora marlin','big game'], gt:['GT (karanks)','popping'], yellowfin:['Sariq qanotli tunets','popping, jig'], wahoo:['Vahu va korifena','trolling'], mackerel:['Qirol makreli','trolling'], reef:['Gruper, lutsian, barrakuda','rif'], fresh:['Chuchuk suv','koʻllar va daryolar'] },
  sea:['Sokin dengiz','Andaman'], levels:['yoʻq yoki kam','uchraydi','yaxshi','choʻqqi'],
  cal:{ kicker:'Baliq ovi kalendari', title:'*Oʻz baligʻingiz* uchun qachon borish kerak', lede:'Andaman dengizi: sokin mavsum — noyabr–aprel, musson — may–oktyabr. Ramka joriy oyni belgilaydi.',
    notes:[['May–oktyabr: musson','Toʻlqin 2–3 metr, uzoq chiqishlar koʻpincha bekor qilinadi. Shamoldan pana Phang Nga qoʻltigʻi, chuchuk suv va yaxshi ob-havo oynalari qoladi — prognozni siz uchun kuzatib boramiz.'],['Yelkanbaliq mavsumi yildan yilga farq qiladi','Kapitanlar choʻqqini yanvar–martda ham, iyun–noyabrda ham kuzatadi. Sanalaringizni ayting — soʻnggi hisobotlar asosida ayni paytda nima yaxshi ilinayotganini aytamiz.']] },
  flow:{ kicker:'Bu qanday ishlaydi', title:'Arizadan trofeygacha — *toʻrt qadam*', steps:[['60 soniyada ariza','Kviz yoki messenjerga xabar: sanalar, kimlar boradi, maqsad, byudjet.'],['15 daqiqada reja','Qayiq, nuqtalar, prognoz va qat’iy narx. Ish vaqtida, Bangkok vaqti bilan 09:00–22:00.'],['30% oldindan toʻlov bilan bron','Shartnoma va tasdiqnoma. 48 soat oldin — prognoz, chek-list va haydovchi kontakti.'],['Chiqish va video','Transfer, okeanda bir kun, 48 soat ichida foto va video, catch & release sertifikati.']] },
  guar:{ kicker:'Kafolatlar', title:'Xatarlar — *bizning zimmamizda*', items:[['100%','Ob-havo sababli bekor qilinsa, pul qaytariladi','Yoki bepul koʻchirish. Qarorni kapitan va prognoz belgilaydi.'],['7 kun','Bepul bekor qilish','Keyinroq — mavsum doirasida qoʻshimcha toʻlovsiz sanani koʻchirish.'],['0 THB','Pirsda qoʻshimcha toʻlov','Nimalar kiritilgani tasdiqnomada koʻrsatilgan.'],['48 soat','Kun davomidagi foto va video','Aks holda keyingi chiqishga 20% chegirma.']] },
  magnet:{ doc:'Qoʻllanma · Andaman', title:'Bepul: Andamanda qayerda qonuniy ovlash mumkin va *baliq qachon yaxshi ilinadi*', text:'Nuqtalar, oylar boʻyicha mavsumlar, oʻzingiz bilan nimalarni olish kerakligi va milliy bogʻda qanday qilib jarimaga tushmaslik. Messenjerga yuboramiz.', cta:'Qoʻllanmani olish' },
  quiz:{ kicker:'60 soniyada tanlov', title:'Sizning *ideal ov kuningizni* tuzamiz', lede:'Beshta savol — va konsyerj qayiq, nuqta, prognoz va narx bilan variant yuboradi.',
    q1:'Kim boradi?', h1:'Bitta variantni tanlang', q2:'Baliq ovidagi tajribangiz qanday?', h2:'Anjomlar va formatni tanlab beramiz', q3:'Siz uchun eng muhimi nima?', h3:'Qayiq va nuqtani maqsad belgilaydi', q4:'Qayerda boʻlasiz?', h4:'Hali qaror qilmagan boʻlsangiz — maslahat beramiz', q5:'Baliq ovi uchun byudjet', h5:'Keraksiz narsalarni taklif qilmaslik uchun', q6:'Reja va narxni qayerga yuboraylik?', result:'Sizga mos keladi',
    who:[['solo','Yolgʻiz oʻzim','yoki doʻstim bilan'],['couple','Juftlik','ikki kishi'],['family','Bolali oila','5 yoshdan katta bolalar'],['friends','4–8 kishilik davra','doʻstlar, erkaklar safari'],['corp','Korporativ 8+','jamoa, hamkorlar'],['vip','VIP-safar','hamma narsa uchun konsyerj kerak']],
    exp:[['zero','Hech qachon ovlamaganman','sinab koʻrmoqchiman'],['casual','Ba’zan baliq ovlayman','uyda va ta’tilda'],['pro','Tajribali spinningchi','popping, jig'],['trophy','Trofey ovchisi','big game, ekspeditsiyalar']],
    goal:[['fun','Dam olish va kechki ovqatga oʻlja','zoʻriqishsiz'],['gt','Trofey: GT va tunets','popping, jig'],['billfish','Yelkanbaliq yoki marlin','big game'],['fresh','Chuchuk suv gigantlari','laqqa, zogʻora, skat'],['event','Jamoa uchun tadbir','turnir va sovrinlar'],['all','Hammasi birdaniga','konsyerj bilan bir hafta']],
    where:[['phuket','Puket','Chalong, Rawai'],['khaolak','Khao Lak yoki Krabi','shimol va sharq'],['bkk','Bangkok yoki Pattaya','chuchuk suv va qoʻltiq'],['any','Hali qaror qilmadik','maslahat bering']],
    budget:[['b1','Bir kishi uchun 10 000 THB gacha','guruh bilan chiqish'],['b2','20 000–40 000 THB','bir kunlik xususiy qayiq'],['b3','50 000–200 000 THB','sportfisher, tunash'],['b4','Byudjet asosiy emas','eng yaxshi natija kerak']] },
  faqTitle:'*Siz soʻramasdan oldin* javob beramiz',
  faq:[
    ['Bu qonuniymi? Baliq ovi uchun hibsga olishlar haqida eshitganman.','Ha, va bu bizning asosiy tamoyilimiz. Turlarni litsenziyali operator oʻtkazadi, bortda — litsenziyali tailandlik gid, qayiqlarda Dengiz departamentining ruxsatnomalari bor. Biz dengiz milliy bogʻlarida (Similan, Surin, Phi Phi, Koh Rok, Hin Daeng) va qoʻriqlanadigan hududlarda ovlamaymiz — u yerda baliq ovlash qonun bilan taqiqlangan.'],
    ['Oʻzbekistondan qanday toʻlash mumkin?','Bron — 30% oldindan toʻlov bilan. Oʻzbekiston banklarining xalqaro Visa/Mastercard kartalari, USDT va joyida naqd pul (THB yoki USD) qabul qilinadi, kompaniyalar uchun hisob-faktura rasmiylashtiramiz. Qolgan summa — chiqish kuni. Hisob va tasdiqnoma — oʻz tilingizda.'],
    ['Boʻron boʻlsa-chi?','Dengizga chiqish haqidagi qarorni kapitan Tailand Meteorologiya departamentining prognozi asosida qabul qiladi. Agar chiqish ob-havo sababli bekor qilinsa — bepul koʻchirish yoki oldindan toʻlovni toʻliq qaytarish. Musson mavsumida shamoldan pana nuqtalarni yoki chuchuk suvni oldindan taklif qilamiz.'],
    ['Dengizda koʻnglim ayniydi. Menga mos keladimi?','Noyabr–aprelni, yarim kunlik xususiy chiqishni va keng korpusli qayiqni tanlang. Marshrutni qisqa oʻtishlar bilan rejalashtiramiz. Eng ta’sirchan odamlar uchun — chuchuk suvli koʻllar: u yerda umuman chayqalmaydi.'],
    ['Tajriba va oʻz anjomlarim kerakmi?','Yoʻq. Kapitan va matros hammasini sozlab, koʻrsatib beradi. Pro Day va ekspeditsiyalar uchun Shimano Stella va Daiwa Saltiga darajasidagi anjomlarni beramiz. Oʻz anjomlaringizni olib kelsangiz ham boʻladi — mavsumingizda nima asqotishini aytib beramiz.'],
    ['Oʻljani olib ketsa boʻladimi?','Iste’mol qilinadigan baliqni — ha: oshpaz bortning oʻzida sashimi va gril tayyorlaydi. Yelkanbaliq, marlin va yirik GT baliqlarini catch & release standarti boʻyicha qoʻyib yuboramiz: oʻlchaymiz, suratga olamiz va sertifikat beramiz.'],
    ['Bolalar bilan borsa boʻladimi?','Ha, 5 yoshdan — «Oilaviy kun» va «Ilk oʻlja» turlariga. Bortda bolalar nimchalari, yengil qarmoqlar, soya va hojatxona bor. Sportfisherga — 10 yoshdan.'],
    ['Viza kerakmi?','Oʻzbekiston fuqarolariga Tailandga kirish uchun viza kerak — turistik viza yoki e-Visa; hujjatlarni tayyorlashda yordam beramiz. 2026-yil 15-sentyabrdan koʻplab davlatlar fuqarolari 30 kun vizasiz kira oladi, uzoq dasturlar uchun esa DTV bor. Batafsil — vizalar boʻyicha qoʻllanmamizda.']
  ],
  legalNote:'Biz dengiz milliy bogʻlari va qoʻriqlanadigan hududlarda ovlamaymiz: Similan, Surin, Phi Phi, Koh Rok, Hin Daeng, Shark Point. Bu Tailand qonuni — va u sizni himoya qiladi.',
  tours:{
    'first-strike':{ title:'Ilk oʻlja', where:'Puket · Racha Yai', kind:'Guruh bilan chiqish',
      short:'Qulay qayiqda oltita baliqchigacha boʻlgan mini-guruh. Racha orollari yonida trolling va tubdan ovlash.',
      pitch:'Andaman dengizida baliq ovini sinab koʻrishning eng oson yoʻli. Ommaviy ekskursiyalardagidek 15–40 kishi emas, hojatxonasi va soyasi bor qayiqda koʻpi bilan oltita baliqchi.',
      species:['Barrakuda','Makrel','Lutsian','Gruper'],
      day:[['07:30','Puketdagi mehmonxonadan transfer'],['08:30','Chalongdan chiqish va instruktaj'],['09:15','Racha Yai tomon yoʻlda trolling'],['10:30','Riflarda tubdan ovlash va jig'],['12:30','Bortda tushlik: gril qilingan oʻlja, mevalar'],['14:00','Tushdan keyingi seans, xohishga koʻra snorkeling'],['16:00','Qaytish va mehmonxonaga transfer']],
      incl:['Puket mehmonxonalaridan transfer','Anjomlar va xoʻrak','Tushlik, suv, mevalar','Yoʻlovchilar sugʻurtasi','Bortda litsenziyali gid','Oʻlja suratlari chatga'],
      excl:['Alkogol','Xususiy qayiq — «Oilaviy kun»ga qarang'],
      upsell:[['Xususiy qayiq','Butun qayiq faqat sizniki — «Oilaviy kun»'],['Dron bilan video','Har bir chiqish uchun +4 500 THB'],['Bolalar toʻplami','Bepul: nimcha va yengil qarmoq']] },
    'family-half':{ title:'Oilaviy kun', where:'Puket · Racha Yai', kind:'Xususiy qayiq',
      short:'Qayiq faqat oilangiz uchun. Sokin suvda besh soat, kapitan bolalar va yangi boshlovchilarga yordam beradi.',
      pitch:'Sinov emas, baliq ovi kerak boʻlganlar uchun format. Dengiz sokin paytda ertalab chiqamiz, Racha Yai yonida ovlaymiz, oʻljadan tushlik qilamiz va jazirama boshlanmasdan qaytamiz.',
      species:['Barrakuda','Korifena','Lutsian','Trevalli'],
      day:[['08:00','Mehmonxonadan transfer'],['08:45','Chiqish va xavfsizlik boʻyicha instruktaj'],['09:15','Trolling: ilk ilinishlar'],['10:30','Rifda ovlash, bolalarga yordam'],['12:00','Oʻljadan sashimi va gril'],['13:30','Chalongga qaytish']],
      incl:['Kapitan va matros bilan xususiy qayiq','Borish-qaytish transferi','Kattalar va bolalar uchun anjomlar','Oʻljadan tushlik va ichimliklar','Bolalar qutqaruv nimchalari','Sugʻurta va litsenziyali gid'],
      excl:['Alkogol','Fotograf — soʻrov boʻyicha'],
      upsell:[['Bortda fotograf','+6 000 THB, 100+ kadr'],['Toʻliq kun','+12 000 THB, plyajda toʻxtash'],['Tort va bezak','Bortda tugʻilgan kun uchun']] },
    'pro-gt':{ title:'Pro Day: GT va jig', where:'Puket · Racha Noi · shelf', kind:'Spidbot · 4 baliqchigacha',
      short:'Gigant karanksga popping va Racha Noi suv osti tepaliklarida vertikal jig. Uddalaydigan va trofey istaganlar uchun.',
      pitch:'Tezyurar spidbot, popping boʻyicha mutaxassis kapitan va 30 kilogrammdan ogʻir GT bilan kurashda ham chidaydigan anjomlar. Nuqtalarni sanangizdagi suv koʻtarilishi va oy fazasiga qarab tanlaymiz — milliy bogʻlar chegarasidan tashqarida.',
      species:['GT (gigant karanks)','Sariq qanotli tunets','It tishli tunets','Amberjek','Gruper'],
      day:[['06:00','Transfer va bortda qahva'],['06:45','30 tugun tezlikda chiqish'],['07:30','Racha Noi riflarida ertalabki popping'],['10:00','60–120 metr chuqurlikda vertikal jig'],['12:30','Tushlik va oqimga qarab nuqtani almashtirish'],['14:00','Tushdan keyin, suv koʻtarilganda popping'],['16:30','Qaytish va kun tahlili']],
      incl:['Mutaxassis kapitan bilan spidbot','Shimano Stella / Daiwa Saltiga anjomlari, PE 6–10','Popperlar, stikbeytlar, 150–400 grammlik jiglar','Tushlik, suv, energetik ichimliklar','Litsenziyali gid va sugʻurta','Ekshn-kameralardan foto va video'],
      excl:['Uchtadan ortiq yoʻqotilgan xoʻraklar — tannarx boʻyicha'],
      upsell:[['Dronli operator','+9 000 THB, 48 soatda rolik'],['Ikkinchi kun','Ikki kun bron qilinsa −15%'],['Oʻz anjomlaringiz','3 000 THB chegirma']] },
    'bigame-day':{ title:'Sportfisherda Big Game', where:'Puket · shelf va FAD', kind:'44–50 futlik sportfisher',
      short:'Haqiqiy sportfisher kokpitidan yelkanbaliq va marlinga trolling. Baliq bilan kurashish kreslosi, autriggerlar, bortda shef-oshpaz.',
      pitch:'Trofey uchun asosiy format. Konditsionerli, baliq bilan kurashish kreslosi boʻlgan 44–50 futlik sportfisher va shu oyda yelkanbaliq shelfning qayerida turishini biladigan jamoa.',
      species:['Yelkanbaliq','Qora marlin','Vahu','Korifena','Tunets'],
      day:[['06:30','Biznes-klass avtomobilda transfer'],['07:00','Chiqish va shef-oshpazdan nonushta'],['08:00','Shelf va FAD boʻylab trolling'],['12:30','Tushlik: oʻljadan sashimi va issiq taom'],['13:30','Tushdan keyingi trolling seriyasi'],['17:00','Qaytish va birinchi yelkanbaliq sharafiga shampan']],
      incl:['Ekipaji bilan sportfisher','Bortda shef-oshpaz va toʻliq ovqatlanish','Big game anjomlari va kreslo','Biznes-klass transfer','Litsenziyali gid va sugʻurta','Kun davomidagi foto va qisqa video'],
      excl:['Premium alkogol — menyu boʻyicha','Milliy bogʻlarda toʻxtash yigʻimlari'],
      upsell:[['Shelfda tunash','«Shelfda tun»gacha uzaytirish'],['Dron bilan suratga olish','+9 000 THB'],['Trofey replikasi','Foto va oʻlchovlar asosida baligʻingizning toʻliq oʻlchamdagi nusxasi']] },
    'overnight-shelf':{ title:'Shelfda tun', where:'Andaman dengizi · 2 kun / 1 tun', kind:'Tunashli sportfisher',
      short:'Ikki ertalabki va bitta kechki ov aynan nuqtaning oʻzida. Tungi kalmar ovi, yulduzlar ostida kechki ovqat, shelfda tong.',
      pitch:'Eng samarali format: kuniga uch soatni yoʻlga sarflamaysiz, eng yaxshi ilinish paytini — tong va shomda — aynan nuqtaning oʻzida kutib olasiz.',
      species:['Yelkanbaliq','Marlin','Sariq qanotli tunets','Vahu','Kalmar'],
      day:[['1-kun · 07:00','Chiqish va shelf boʻylab trolling'],['1-kun · 18:00','Shef-oshpazdan kechki ovqat va tungi kalmar ovi'],['2-kun · 05:30','Tongdagi ov — yelkanbaliq uchun asosiy imkoniyat'],['2-kun · 12:00','Tushlik va soʻnggi seriya'],['2-kun · 17:00','Chalongga qaytish']],
      incl:['Kayutalari va dushi bor sportfisher','Shef-oshpaz va besh mahal ovqat','Barcha anjomlar va xoʻrak','Transferlar','Litsenziyali gid va sugʻurta','Kun davomidagi foto va video'],
      excl:['Premium alkogol','60 mildan uzoqqa chiqish uchun yoqilgʻi'],
      upsell:[['3 kun / 2 tun','+85 000 THB'],['Dronli operator','Safar haqida film'],['Chiqishdan keyin villa','Konsyerj bron qiladi']] },
    'expedition-khaolak':{ title:'Khao Lak ekspeditsiyasi', where:'Khao Lak · FAD va shelf · 4 kun', kind:'Liveaboard · bir baliqchi uchun',
      short:'Bortda toʻrt kun: Khao Lak va Similan orollari oraligʻidagi FAD maydonlarida popping va jig — qat’iy ravishda bogʻ chegarasidan tashqarida.',
      pitch:'Bir sutkada iloji boricha koʻp tashlashni istaganlar uchun ekspeditsiya. FAD maydonlari Tap Lamudan 6 km narida boshlanib, Similan orollari tomon choʻziladi. Shelfda ovlaymiz, langarda tunaymiz; bogʻda faqat dam olamiz — u yerda baliq ovlash taqiqlangan.',
      species:['GT','Sariq qanotli tunets','Korifena','Vahu','Qirol makreli'],
      day:[['1-kun','Puketdan transfer, Tap Lamudan chiqish, birinchi FAD nuqtalari'],['2-kun','Tongda popping, kunduzi 60–80 metr chuqurlikda jig'],['3-kun','Uzoqdagi FAD nuqtalari va yelkanbaliqqa trolling'],['4-kun','Ertalabki seans, qaytish va transfer']],
      incl:['Kayutali liveaboard kemasi','Toʻliq ovqatlanish','Premium darajadagi anjomlar','Puket — Tap Lamu transferi','Litsenziyali gid va sugʻurta','Ekspeditsiya foto va videosi'],
      excl:['Milliy bogʻda toʻxtash uchun yigʻim (kuniga 500 THB)','Alkogol','Ekipajga choychaqa'],
      upsell:[['Xususiy charter','Butun qayiq guruhingiz uchun'],['6 kungacha uzaytirish','Soʻrov boʻyicha'],['Mergui (Myanma)','Chegara ochiq boʻlsa, soʻrov boʻyicha ekspeditsiya']] },
    'gulf-private':{ title:'Siam qoʻltigʻi: Pattaya va Samui', where:'Pattaya · Koh Khram · Samui', kind:'Xususiy spidbot',
      short:'Qoʻltiq boʻyida yashaydigan yoki dam oladiganlar uchun. Orollargacha qisqa yoʻl, barrakuda, kobiya, qirol makreli.',
      pitch:'Pattayada eng yaxshi mavsum — oktyabrdan martgacha, Samuida — yanvardan maygacha. Koh Khram, Koh Phai va Samae San orollariga yoki Samui shimolidagi riflarga chiqamiz — baliq ovlash mumkin boʻlmagan Ang Thong milliy bogʻidan tashqarida.',
      species:['Barrakuda','Kobiya','Qirol makreli','Gruper','Kvinfish'],
      day:[['07:00','Mehmonxona yoki kondodan transfer'],['07:45','Spidbotda chiqish'],['08:30','Orollar tomon trolling'],['10:30','Riflarda jig va tirik xoʻrak'],['12:30','Bortda tushlik va choʻmilish'],['14:30','Qaytish']],
      incl:['Kapitan bilan xususiy spidbot','Transfer','Anjomlar va xoʻrak','Tushlik va ichimliklar','Litsenziyali gid va sugʻurta','Oʻlja suratlari'],
      excl:['Alkogol','Tungi kalmar ovi — soʻrov boʻyicha'],
      upsell:[['Tungi kalmar','Kechki ovqat bilan kechki chiqish'],['Arapaymali koʻl','Ikkinchi kun — chuchuk suv'],['Spidbot oʻrniga yaxta','12 mehmongacha boʻlgan davra uchun']] },
    'bangkok-monsters':{ title:'Bangkok gigantlari', where:'Bangkok · New Bungsamran', kind:'Chuchuk suv · bir kun',
      short:'Mamlakatning eng yaxshi koʻlida 30–100 kilogrammlik gigant Mekong laqqasi va Siam zogʻorasi. Bangkokdagi mehmonxonadan transfer.',
      pitch:'Bangkokda toʻxtab oʻtganda va dengiz notinch boʻladigan yomgʻirli mavsumda ayni muddao. 100 kilogrammgacha baliqli koʻl, konditsionerli shiypon va anjomlar hamda yemni tayyorlab beradigan gid.',
      species:['Mekong laqqasi','Siam zogʻorasi','Arapayma'],
      day:[['06:00','Bangkokdagi mehmonxonadan transfer (taxminan bir soat)'],['07:30','Shiypon, anjomlar, yem'],['08:00','Ov: gid kun boʻyi yoningizda'],['13:00','Koʻl restoranida tushlik'],['19:30','Trofeylar bilan suratga tushish va qaytish']],
      incl:['Bangkok mehmonxonalaridan transfer','Seans uchun chipta','Anjomlar va yem','Koʻlda gid','Konditsionerli shiypon','Trofeylar surati'],
      excl:['Koʻldagi ovqatlanish','Tungi seans — soʻrov boʻyicha'],
      upsell:[['Tungi seans','Kechasi yirik laqqa'],['Gigant skat','Ikkinchi kun Mae Klong daryosida'],['Daryo boʻyidagi mehmonxona','Konsyerj bron qiladi']] },
    'stingray':{ title:'Gigant skat', where:'Mae Klong daryosi · Samut Songkhram', kind:'Chuchuk suv · bir kun',
      short:'Mae Klong daryosida qayiqdan 100 kilogrammdan ogʻir chuchuk suv skatini ovlash. Catch & release.',
      pitch:'Sayyoramizdagi eng yirik chuchuk suv baliqlaridan biri. 2015-yilda Mae Klongda uzunligi taxminan toʻrt metr boʻlgan skat tutilib, qoʻyib yuborilgan. Bu sabr talab qiladigan ov va umrbod esda qoladigan yagona imkoniyat.',
      species:['Gigant chuchuk suv skati','Laqqa'],
      day:[['05:30','Bangkokdan transfer (taxminan 1,5 soat)'],['07:30','Daryoda qayiq va ogʻir anjomlar'],['08:00','Tirik xoʻrak bilan ov va ilinishni kutish'],['13:00','Daryoda tushlik'],['17:30','Bangkokka qaytish']],
      incl:['Transfer','Qayiq va mahalliy yoʻlboshchi','80–130 lb ogʻir anjomlar','Xoʻrak','Tushlik','Trofeyni suratga olish va oʻlchash'],
      excl:['Ilinish kafolati — bu yovvoyi baliq'],
      upsell:[['Ikkinchi kun','Imkoniyat ikki barobar ortadi'],['Bangkok gigantlari','Ikki kunlik kombo'],['Videoga olish','Qayiqda operator']] },
    'khaosok-jungle':{ title:'Khao Sok tropik oʻrmonida baliq ovi', where:'Cheow Lan koʻli · 2 kun', kind:'Suzuvchi uy · bir baliqchi uchun',
      short:'Karst qoyalari orasida ilonbosh va hampala. Koʻldagi suzuvchi uyda tun va tongdagi ov.',
      pitch:'Tailanddagi eng goʻzal baliq ovi. Mahalliy longteyl qayiqlaridan spinning va fly-fishing bilan ovlaymiz — koʻlga boshqa qayiqlar kiritilmaydi — va milliy bogʻ qoʻynidagi suzuvchi uyda yashaymiz.',
      species:['Gigant ilonbosh','Hampala','Mahsir','Laqqa'],
      day:[['1-kun · 07:00','Puket yoki Khao Lakdan transfer (taxminan 2,5 soat)'],['1-kun · 11:00','Longteyl va ilonboshga ilk urinishlar'],['1-kun · 17:00','Kechki ov va suzuvchi uyda kechki ovqat'],['2-kun · 06:00','Tongdagi ov'],['2-kun · 12:00','Tushlik va ortga transfer']],
      incl:['Transferlar','Ovqatlanish bilan suzuvchi uy','Mahalliy gid bilan longteyl','Milliy bogʻ yigʻimlari','Yengil anjomlar','Foto'],
      excl:['Fly-fishing anjomlari — oʻzingiznikini olgan ma’qul','Alkogol'],
      upsell:[['Uchinchi kun','Uzoqdagi qoʻltiqlar'],['Tropik oʻrmonda safari','Oila uchun'],['Xususiy suzuvchi uy','Butun uy siz uchun']] },
    'tournament':{ title:'Korporativ turnir', where:'Puket · 3–5 qayiq · 2 kun', kind:'Kompaniya · 8–30 mehmon',
      short:'Bir xil qayiqlarda hakam, nominatsiyalar va kuboklar bilan turnir. Villada ziyofat-marosim va 48 soatdan keyin film.',
      pitch:'Shunday tadbirki, undan keyin jamoa avtobus kutganini emas, kubok uchun qanday kurashganini eslaydi. Flot, hakamlik, sovrinlar, ziyofat, suratga olish va hujjatlar — bizning zimmamizda.',
      species:['Yelkanbaliq','Tunets','Barrakuda','Karanks'],
      day:[['1-kun · ertalab','Brifing va qayiqlarga taqsimlash'],['1-kun · kunduzi','Turnirning birinchi turi'],['1-kun · kechqurun','Villada kechki ziyofat va oraliq natijalar'],['2-kun · kunduzi','Final turi'],['2-kun · kechqurun','Marosim, kuboklar va film-tizer']],
      incl:['Ekipajlari bilan 3–5 qayiq','Hakam, qoidalar va bayonnomalar','Kuboklar va nominatsiyalar','Ziyofat-marosim va boshlovchi','Foto, dron va 48 soatda rolik','Kompaniya uchun shartnoma va hisob-faktura'],
      excl:['Turar joy — tanlab beramiz','Aviaparvozlar'],
      upsell:[['Brendlash','Logotipli futbolkalar, bayroqlar va kuboklar'],['Guruh uchun villa','Safarning barcha kunlariga'],['Hamkorlar uchun dastur','Spa, yaxta, shoping']] },
    'signature-week':{ title:'Signature Week', where:'Puket · Khao Lak · Bangkok', kind:'Konsyerj · 7 kun',
      short:'Tailanddagi eng yaxshi baliq ovi haftasi, toʻliq tashkil etilgan: villa, sportfisher, chuchuk suv gigantlari, shef-oshpaz, suratga olish va shaxsiy konsyerj.',
      pitch:'Vaqtini qadrlaydiganlar uchun. Dasturni maqsadlaringizga qarab tuzamiz: okeanda uch kun, shelfda bir tun, tropik oʻrmonda bir kun va rekordli koʻl. Siz villada yashaysiz, qolgan hamma narsani konsyerj hal qiladi.',
      species:['Yelkanbaliq','Marlin','GT','Mekong laqqasi','Ilonbosh'],
      day:[['1-kun','Aeroportda kutib olish, villa, shef-oshpazdan kechki ovqat'],['2–3-kunlar','Sportfisherda Big Game'],['4-kun','Shelfda tun'],['5-kun','Khao Sok tropik oʻrmoni'],['6-kun','Dam olish, spa, oila — xohishga koʻra'],['7-kun','Bangkok gigantlari yoki uchib ketish']],
      incl:['24/7 shaxsiy konsyerj','Basseynli villa','Barcha chiqishlar va qayiqlar','Shef-oshpaz','Foto, dron va safar haqida film','Barcha transferlar va VIP kutib olish'],
      excl:['Aviaparvozlar','Dasturdan tashqari shaxsiy soʻrovlar — smeta boʻyicha'],
      upsell:[['Gidrosamolyot','Nuqtalar orasida parvozlar'],['Oilaviy dastur','Baliq ovlamaydiganlar uchun'],['Trofey replikasi','Ish kabinetingiz uchun']] }
  }
};
